package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class alexRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_alex_rel);

        TextView relAlex = (TextView) findViewById(R.id.relAlex);
        TextView e6 = (TextView) findViewById(R.id.e6);

        relAlex.setText("Relatia dintre Alexandru Lapușneanu și Moțoc");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  Publicată în perioada paşoptistă, în primul număr al „Daciei literare”, nuvela ilustrează două dintre cele patru idei formulate de Mihail Kogălniceanu în articolul-program „Introducție”: promovarea unei literaturi originale şi inspirația din istoria naţională. Costache Negruzzi este întemeietorul nuvelei istorice româneşti și primul scriitor care valorifică, într-o creaţie literară, cronicile moldoveneşti. \n"+
                "  Relaţiile dintre personaje, precum Alexandru Lăpuşneanul şi Motoc sunt evidenţiate de tema luptei  pentru putere în epoca medievală (în Moldova, la mijlocul secolului al XVI-lea). Acţiunea se desfăşoară, în raport cu momentele subiectului, de la expoziţiune la deznodământ, punând în lumină tipul domnitorului tiran şi pe acela al boierului trădător, laş, intrigant. Conflictul nuvelei este complex. Principalul conflict, exterior, este de natură politică şi pune în evidenţă lupta pentru putere între domnitor şi boieri. Conflictul secundar, între domnitor şi Moţoc (boierul care-l trădase), evidențiază dorinţa de răzbunare a Lăpuşneanului, fiind conturat în primul capitol şi încheiat în capitolul al III-lea. Din construcţia subiectului, capitolul al III-lea este cel care evidenţiază faptul că cererea vindicativă a poporului („Capul lui Moţoc vrem...\") rezonează cu intenţiile criminale ale domnitorului. \n"+
                "  Alexandru Lăpuşneanul este personajul principal din nuvelă, personaj romantic, excepțional, eponim, care acționează în situaţii excepţionale (de exemplu, scena uciderii lui Moțoc). Întruchipează tipul domnitorului crud şi tiran, perfect integrat  în mentalitatea epocii, care guvernează absolutist într-o societate dominată de anarhie feudală. El este construit din contraste şi are o psihologie complexă, calități şi defecte, fiind un „damnat\" romantic. "+
                "  Autorul îi marchează destinul prin cele patru replici memorabile, plasate în fruntea capitolelor. Destinul său este de a impune autoritatea domnească prin orice mijloace. "+
                "  Afirmaţia: „Eu nu sunt călugăr, sunt domn!\" reflectă faptul că nu abdică de la propriul destin nici în faţa limitelor omeneşti (boala, moartea), schimbarea condiţiei sociale impunând anularea sa fizică. "+
                "  Crud, hotărăt, viclean, disimulat, inteligent, bun cunoscător al psihologiei umane, abil om politic, personajul este puternic individualizat şi memorabil. „Echilibrul între convenţia romantică şi realitatea individului, aceasta e minunea creaţiei lui Negruzzi: (G. Călinescu, „Istoria literaturii române de la origini până in prezent”). "+
                "  Sosit în ţară la adoua domnie, este întâmpinat de solia boierilor, din care face parte şi Moţoc. La replica voievodului: „- Am auzit, urmă Alexandru, de bântuirile țării şi am venit s-o mântui; ştiu că ţara m-aşteaptă cu bucurie”, Moțoc_ai întâi mieros, C.-~7•St,-.4: 4. apoi tranşant, vorbind în numele poporului: „- Să nu banuieşti Măria-Ta, zise Moţoc, ţara este liniştită şi poate că Măria-Ta ai auzit lucrurile precum nu sunt; căci aşa este obiceiul norodului nostru, să facă din ţânţar armăsar. Pentru aceea obştia ne-au trimis pre noi să-ţi spunem că norodul nu te vrea, nici te iubeşte şi Măria-Ta să te întorci înapoi ca...\" .\n"+
                "  Hotărârea de „a curăţi stupul\" este pusă în practică prin guvernarea cu ajutorul terorii, prin lichidarea posibilelor opoziţii, culminând cu uciderea celor 47 de boieri. Scena masacrului dovedeşte sângele rece al domnitorului, laşitatea şi servilismul lui Moțoc: „El râdea; iar Moţoc, silindu-se a râde ca să placa stăpânului, simțea părul zburlindu-i-se pe cap şi dinții săi clănțănind\". "+
                "  Decizia de a avea puterea este formulată implacabil prin răspunsul dat: „Dacă voi nu mă vreţi, eu vă vreau... şi dacă voi nu iubiţi, eu vă iubesc pre voi şi voi merge ori cu voia ori rară voia voastră. Să mă întorc? Mai degrabă-şi va întoarce Dunărea cursul indărăt.\" Moțoc, viclean, fals smerit şi văicăreţ, făcând apel la o retorică biblică, îşi joacă o ultimă carte: „Doamne! Doamne! Zise Moţoc, căzând în genunchi, nu ne pedepsi pre noi după fărădelegile noastre! Adă-ţi aminte că eşti pământean, adă-ti aminte de zisa Scripturei şi iartă greşiţilor tăi! Cruţă biata ţară! Doamne! sloboade oştile aceste de păgâni; vină numai cu câţi moldoveni ai pe lângă Măria-Ta şi noi chizleşuim că un fir de păr nu se va clinti din capul Înălțimei-Tale...”. Înfruntarea dintre cei doi este inegală, deoarece Lăpuşneanul se dovedeşte un bun cunoscător al psihologiei boierilor, caracterizându-l succint pe Moţoc: „Pesemne nu vă cunosc eu şi pre tine mai vărsos? Nu ştiu că, fiind mai mare peste oştile mele, cum ai văzut că m-au biruit, m-ai lăsat? Dar tu, Moțoace? Învechit în zile rele, deprins a te ciocoi la toţi domnii, m-ai vândut și pre mine, vei vinde pre Tomșa; spune-mi, n-aş fi un nătărău de frunte, când m-aş încrede în tine?\". Moțoc este cruţat de domnitor, acesta fiind conștient că  boierul îi va putea fi o unealtă utilă: „... îți făgăduiesc că sabia mea nu se va mânji de sângele tău; te voi cruţa, căci îmi eşti trebuitor, ca să mă mai uşurezi de blăstemurile norodului. Sunt alți trântori de care trebuie curățit stupul\". "+
                "  Voinţei neabătute i se asociază alte trăsături. Abilitatea în ceea ce priveşte umane, diplomaţia, cunoaşterea psihologiei umane sunt calităţi ale conducătorului, dar, folosite pentru consolidarea puterii absolute, devin mijloace perfide. El face promisiuni liniştitoare pentru ceilalţi, dar care ascund un plan de răzbunare. Acest plan este crud: Moțoc sfârşeşte sfâşiat de mulţime. Sacrificăndu-l pe boier domnitorul se răzbună pentru trădarea acestuia din prima domnie şi linişteşte (manipulează) mulțimea revoltată, de a cărei putere este conştient: \"- Proşti, dar mulţi\". Dialogul dintre cei doi, Lăpuşneanul şi Moţoc, arată, încă o dată, că acesta din urmă este tipul linguşitorului: „-Măria-Ta, ai urmat cu mare înţelepciune, răspunse mărşavul curtean; eu de mult aveam de gând să sfătuiesc pre Măria-Ta la aceasta, dar văd că înţelepciunea Măriei-Tale au apucat mai inainte şi ai făcut bine că i-ai tăiat.”Stăpânirea de sine, sângele rece sunt dovedite momentul pedepsirii lui Moţoc, pe care Lăpușneanu îl oferă gloatei ca ţap ispăşitor: „- Destul! strigă Lăpuşneanul, nu te mai boci ca o muiere! Fii român verde. Ce să te mai spoveduieşti? Ce să-i spui duhovnicului? Că eşti tâlhar şi un vânzător? Asta o ştie toată Moldova. Haide! luati-l de-l daţi norodului şi-i spuneţi că acest fel plăteşte Alexandru-vodă celor ce pradă ţara.” Portretul acestui personaj secundar se realizează prin prisma altor personaje (Alexandru Lăpuşneanul) sau prin anumite abateri ale naratorului de la obiectivitate: Moţoc „îi sărută mâna, asemenea cânelui care, în loc să muşce, linge mâna care-l bate\". \n"+
                "  Forţa excepţională a protagonistului domină şi relaţiile cu celelalte personaje. De  exemplu, relaţia cu doamna Ruxanda este construită pe antiteza romantică angelic-demonic. Diversitatea atitudinilor adoptate fată de aceasta dezvăluie falsitatea. Se căsătorise cu ea „ca să tragă inimile norodului, în care via încă pomenirea lui Rareş\". Nu o respectă nici pentru originea ei nobilă, nici pentru că îi este soţie sau mamă a copiilor săi. Doamna Ruxanda „ar fi voit să-l iubească, dacă ar fi aflat în el cât de puţină simţire omenească\". \n"+
                "  În opinia mea, relaţiile dintre Alexandru Lăpuşneanul şi Moţoc scot în evidență conflictul dintre domnitor şi boieri. Acesta este generat de dorința protagonistului de a întări autoritatea domnească, într-o perioadă istorică dominată de anarhie. "+
                "  În concluzie, nuvela aduce în atenția cititorului un personaj memorabil, care se impune în relaţiile cu toate celelalte personaje."
                ;

        stringBuilder.append(finallyEseu);
        e6.setText(stringBuilder.toString());
    }
}
