package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class alexTema extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_alex_tema);

        TextView eseuAlex = (TextView) findViewById(R.id.eseuAlex);
        TextView e4 = (TextView) findViewById(R.id.e4);

        eseuAlex.setText("Alexandru Lapusneanu, de Costache Negruzzi");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  Publicată in perioada paşoptistă, în primul număr al Daciei literare, nuvela ilustrează două dintre cele patru idei formulate de Mihail Kogălniceanul în articolul-program \"Introducţie\": promovarea unei literaturi originale şi inspiraţia din istoria natională. Din punct de vedere tematic, \"Alexandru Lăpuşneanul\" este o nuvelă istorică, deoarece reconstituie moment zbuciumat din istoria Moldovei secolului al XVI-lea, cea de-a doua domnie lui Alexandru Lăpuşneanul (1564-1569). Titlul nuvelei face trimitere la protagonist. \n"+
                "  Ca autor de proză romantică, Negruzzi e preocupat de prezentarea cadrului temporal, cu amănunte (imbrăcămintea domnească a protagonistului, eticheta şi felurile de la masa domnească) destinate să evoce culoarea de epocă. Aceeaşi funcţionalitate revine arhaismelor, pe care Negruzzi le foloseşte în alternantă cu neologismele, realizând astfel contraste pline de expresivitate.\n"+
                "  De factură romantică, prin modul de abordare a destinului protagonistului, prin atitudinea voluntară a unor personaje, prin patetismul gesturilor, nuvela aparţine prin observaţiile tipologice. Moţoc, de exemplu, reprezintă boierimea însetată de avere, linguşitorul; Ruxanda ilustrează gingăşia; Spancioc şi Stroici - boierii patrioti. Nuvela este clasică şi prin proporţia sau echilibrul compoziţiei.  "+
                "  Viziunea despre lume în acest discurs literar se bazează pe ideea că puterea pare fie urmărită de un soi de fatalitate, e condamnată să-şi ascundă vulnerabilitatea prin ostentație (vestimentaţia domnitorului la intâlnirea cu boierii, în biserică), iar pentru aceasta este condamnată să recurgă la violență. Din acest punct de vedere viziunea scriitorului prezintă interesante asemănări cu cele din dramele istorice ale ui Shakespeare, despre care vorbea criticul Jann Kott: orice suveran e un simplu instrument al puterii, aceasta având aspectul brutal al unui mecanism care îl dezumanizează pe  individul pus s-o servească.\n"+
                "  Costache Negruzzi este întemeietorul nuvelei istorice româneşti şi primul scriitor care valorifică, într-o creatie literară, cronicile moldoveneşti. Scriitorul declară ca izvor al nuvelei Letopisetul Țării Moldovei, de Miron Costin, de unde prelucrează, pentru episodul omorârii lui Moţoc din nuvelă, scena uciderii lui Batişte Veveli în timpul domniei lui Alexandru Iliaş."+
                "  În schimb, imaginea domnitorului este conturată în \"Letopisetul Ţării Moldovei\" de Grigore Ureche. Tot din cronica lui Ureche, Negruzzi preia scene, fapte şi replici (de exemplu, mottoul capitolului I şi al IV-lea), dar se distanţează de realitatea istorică prin apelul la ficţiune şi prin viziunea romantică asupra istoriei, influentată de ideologia paşoptistă. Dintre principalele evenimente consemnate de cronicar, autorul preia următoarele: împrejurările venirii lui Lăpuşneanul la a doua domnie, solia boierilor trimisă de Tomşa, uciderea celor 47 de boieri, arderea cetătilor Moldovei,boala, călugărirea şi moartea prin otrăvire a domnitorului. Negruzzi comprima, omite sau modifică unele fapte istorice (de exemplu, decapitarea lui Motoc la Liov). Scriitorul transformă evenimentele menţionate de cronicar în scene, cărora le conferă o desfășurare amplă, impusă de evoluția conflictului. Autorul modifică realitatea istorică, prin intermdiul ficțiunii, acțiunea nuvelei păstrându-se in limitele verosimilului. De exemplu, ca persoane, vornicul Moţoc, postelnicul Veveriţă şi spătarul Spancioc fugiseră la Liov, în Polonia, şi nu mai trăiau în timpul celei de-a doua domnii a lui Alexandru Lăpușeanu; ca personaje, însă, ele sunt prezente pentru a ilustra tipuri umane (boierul trădător şi boierii patrioţi). \n"+
                "  Nuvela este o specie a genului epic, cu un singur fir narativ, care prezintă, cel mai: adesea, fapte verosimile. Nuvela urmăreşte viaţa protagonistului, iar atitudinea naratorului este detaşată."+
                "  Compoziţional, Alexandru Lăpuşneanul este alcătuită din patru capitole cu „titluri\" sugestive, exprimate sub formă de motto: „Dacă voi nu mă vreti, eu vă vreu\", „Ai să dai sama, Doamnă!\", „Capul lui Moțoc îl vrem”, „De mă voi scula, pre mulți am să popesc şi eu!\". Momentele naraţiunii se succed gradat, ca intr-o operă dramatică: fiecare dintre cele patru capitole, asemenea actelor unei drame, se încadrează în structura compozițională unitară a nuvelei.\n"+
                "  Expoziţiunea şi intriga sunt prezentate în capitolul I, prin câteva secvenţe relevante. După uciderea lui Despot de către Stefan Tomşa, Lăpuşneanul se întoarce de la Constantinopole cu o armată turcească şi este întâmpinat de patru boieri: vornicul Moţoc, postelnicul Veveriţă, spătarii Spancioc şi Stroici, care-i sugerează că nu este dorit de către popor. Domnitorul nu renunţă insă la planurile sale. Hotărârea domnitorului de a rămâne în ţară constituie intriga. Desfăşurarea acțiunii este evocată în capitolele II şi III: domnitorul îi promite lui Moţoc că nu-l va ucicle dar hotărăşte să-i pedepsească pe boierii intriganţi, luându-le averile şi omorându-i.\n"+
                "  Singurii care ghicesc intentia lui Lăpusneanul și reusesc să părăsească ţara sunt Spancioc şi Stroici. La rugămintea unei jupânese văduve, Ruxanda, soţia domnitorului, îi cere acestuia să înceteze cu omorurile, el promiţându-i un leac de frică. Cu prilejul slujbei religioase, domnitorul le ține boierilor un discurs, făgăduindu-le că-i iartă şi invitându-i la un ospăţ. Cei patruzeci și șapte de boieri sunt măcelăriți, iar capetele lor sunt așezate în formă, de piramidă, în funcţie de rangul fiecăruia, acesta reprezentând punctul culminant al acţiunii. La vederea acestui „leac de frică\", doamna Ruxanda leșină. Mulţimea, alertată de slugile boieresti, se strânge la palat, cerând capul lui Moţoc. Acesta va fi linșat.\n"+
                "  În capitolul al IV-lea, asistăm la deznodământ: retras la cetatea Hotinului, domnitorul continuă represaliile asupra boierilor. Bolnav de friguri, Lăpusneanul cere să fie călugărit și, revenindu-și din boală, nu-și mai amintește de cererea sa, promiţând că se va răzbuna. După îndelungi ezitări, Ruxanda, sfătuită de cei doi boieri întorsi din pribegie, înţelege că trebuie să-și ucidă, soţul, întinzându-i o cupă cu otravă. Spancioc și Stroici duc la capăt fapta soţiei domnitorului. \n"+
                "  În orice nuvelă conflictul este concentrat. În Alexandru Lăpuşneanul, conflictul este generat de înfruntarea dintre boierii trădători şi domnitor.\n"+
                "  În nuvelă, spre deosebire de povestire, accentul cade mai mult pe conturarea portretului protagonistului decât pe acțiune. Faptele voievodului ajuns din nou pe tronul Moldovei (campania de exterminare a boierilor, iertarea pe care o cere cu umilință acestora, leacul de frică oferit domniței, aruncarea lui Moțoc în măinile mulțimii) pun în lumină un domn absolut, un tiran al epocii medievale, care acționează pentru întărirea autoritătii domneşti şi slăbirea puterii boleri. Prin puterea de evocare a dialogului printr-o fină observație a gesturilor, a mimicii, se dezvăluie toată mișcarea psihologică a viitorului tiran, încă din primul capitol. Scena dialogată a întâlnirii dintre domnitor şi solia de boieri conturează conflictul puternic, evidențiind trăsătura fundamentală a Lăpuşneanului: voinţa neclintită de a domni. În partea a II-a, se observă două însuşiri ale protagonistului: impulsivitatea şi cruzimea: „strigă... sărind în picioare, şi mâna lui, prin deprindere, se răzimă de junghiul său\"."+
                "  În partea a III-a, în timpul slujbei, este evidenţiat faptul că Lăpuşneanul dă dovadă de capacitate de disimulare, dovedindu-se un bun actor. Scriitorul își lasă eroul să se miște singur fără nicio intervenție, obiectivând total acțiunile acestuia. Luciditatea, sângele rece, tonul sarcastic în fata scenei sângeroase a măcelăririi lui Moţoc dezvăluie un om diabolic. În scena finală a bolii şi a otrăvirii sale, personajul trăieşte cu intensitate  atât umilinţa, cât şi revolta împotriva celor care l-au călugărit, apoi groaza în faţa morţii. În privința\\tehnicii narativei finalul fiecărui capitol anunță întâmplările ce vor urma: de exemplu, o legătură firească este asigurată de replicile de la sfarşitul capitolului al doilea: „Dar oare va veni?”, îl intreabă domnitorul pe armaş. „Vor veni!\", răspunde înaltul dregător, şi cititorul este pregătit să asiste la intâmplările sângeroase din următorul capitol. "+
                "  Registrul stilistic este obiectiv: „Ceea ce izbuteşte în chip uimitor Negruzzi în Alexandru Lăpuşneanul este desăvârşita eliminare a propriei sale imagini din naraţiunea pe care o intreprinde\" (T. Vianu, Arta prozatorilor români). Cu alte cuvinte, relatarea se realizează la persoana a III-a (perspectivă narativă obiectivă), impersonalismul fiind o trăsătură a realismului, dar şi a acestei specii literare. Aşa cum sesiza G. Călinescu: „judecăţile de valoare ale scriitorului sunt rare, ca de pildă când ne vorbeşte despre urâtul caracter al domnitorului sau despre deşănţata-i cuvântare\". \n"+
                "  Acţiunea nuvelei este spectaculoasă la modul romantic, ea cuprinde scene senzaţionale (piramida de capete) şi răsturnări de situaţie (transformarea protagonistului din călău în victimă). Deşi a fost asimilată de unii comentatori (Tudor Vianu) realismului, pentru obiectivitatea discursului narativ, opera lui Negruzzi rămâne esentialmente romantică. \n"+
                "  În acelaşi spirit romantic, autorul îl înzestrează pe protagonistul nuvelei cu defect excepţionale. Modalităţile de caracterizare a protagonistului sunt diverse. El reprezintă o ipostază a demonului romantic, „un damnat, osândit de Providentă să. verse sânge şi să năzuie spre mântuire\" (G. Călinescu). Mustrările de conştiintă, teama de pedeapsa divină îl determină să se călugărească, lăsându-i domnia fiului său, dar personajul e prea setos de putere pentru a renunţa cu uşurinţă la tron. Din acest moment, Lăpuşneanul devine un suflet dedublat (motiv prin excelență romantic)care oscilează între dorinta de putere şi setea de mântuire despre care vorbea Călinescu, făcând-o pe doamna Ruxanda să se teamă pentru viaţa fiului ei.\n"+
                "  În viziunea lui Negruzzi, puterea pare să fie urmărită de un soi de fatalitate, e condamnată să-şi ascundă vulnerabilitatea prin ostentaţie (vestimentatia domnitorului la intâlnirea cu boierii, în biserică), iar pentru aceasta este condamnată să recurgă la violentă. Din acest punct de vedere, viziunea scriitorului prezintă incitante similitudini cu cea din dramele istorice ale lui Shakespeare, despre care vorbea criticul Jann Kott: orice suveran e un simplu instrument al puterii, aceasta având efectul brutal al unui mecanism care dezumanizează pe individul pus s-o servească. „Răul puterii\" este dublat, în viziunea lui Negruzzi, de un „rău al istoriei\", care îi contaminează şi pe inocenţi. Această idee este sugerată de procedeul „punerii în abis\", în scena masacrării boierilor, prin imaginea vinului amestecat cu sânge care acoperă duşumeaua sălii de ospăţ şi devine pregnantă în capitolul final. Lăpuşneanul e criminal şi această criminalitate le molipseşte şi pe celelalte personaje, de exemplu, pe Spancioc și pe Stroici. Toate aceste elemente se articulează coerent intr-o viziune pesimistă asupra istoriei, care o anticipează pe cea a lui Eminescu.\n"+
                "  În opinia mea, o caracteristică a acestei nuvele este faptul că, în ceea ce priveşte construcţia, ea poate a fi asemănată cu aceea a unei piese de teatru:„Opera trăieşte prin construcţia dramatică, personajele se mişcă, vorbesc, autorul nu intervine decât atunci când este necesară explicarea scenelor dialogate\" (T. Vianu, Arta prozatorilor români). Criticul G. Călinescu, numind-o fără ezitare „o capodoperă\", o aşeza în imediata descendenţă estetică şi valorică a tragediei shakespeariene Hamlet, „dacă literatura română ar fi avut prestigiul unei limbi universale\".  \n"+
                "  În concluzie, prin structura ei simetrică şi echilibrul solid, nuvela se înscrie în clasicism, în vreme ce psihologia protagonistului o situează în sfera romantismului. Realismul nuvelei este evidenţiat de adevărul istoric al evoluţiei lui Alexandru Lăpuşneanul pe parcursul celei de-a doua domnii. "
                ;

        stringBuilder.append(finallyEseu);
        e4.setText(stringBuilder.toString());
    }

}
