package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class baltagRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_baltag_rel);

        TextView relBaltag = (TextView) findViewById(R.id.relBaltag);
        TextView e15 = (TextView) findViewById(R.id.e15);

        relBaltag.setText("Relația dintre Vitoria și Gheorghiță");
        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  Tradiţionalist şi modernist în acelaşi timp, Mihail Sadoveanu este autorul unei opere de peste o sută de volume. „Baltagul\" este una dintre capodoperele sale, fiind caracterizat prin concizie, dinamism şi armonie compoziţională. Apărut în 1930, „Baltagul\" reprezintă sinteza naturii artistice a prozatorului. "+
                "  Analizând această operă, criticul Al. Paleologu (în „Treptele lumii\" sau calea către sine a lui Mihail Sadoveanu) propune o viziune inedită de receptare, ce diferă de interpretarea clasică a romanului, ca o continuare a „Mioriței\". Călătoria Vitoriei în căutarea rămăşiţelor pământeşti ale lui Nechifor este povestealui Isis în căutarea trupului dezmembrat al lui Osiris. Prima aluzie, practic imperceptibilă la Osiris, autorul o face abia la sfârșitul capitolului XI, când spune că „trebuia să afle dacă Lipan s-a înăltat în soare ori a curs pe o apă\". Osiris, ca divinitate, reprezintă soarele care apune şi răsare, adică moare şi reînvie. "+
                "  Isis-Vitoria este însoțită în căutarea soţului mort de fiul ei, Gheorghiță-Horus şi de caine, Lupu-Anubis, al cărui chip este asociat, simbolic, funcţiei de ghid şi păzitor al sufletului după moarte. Rolul decisiv al câinelui Lupu, în deznodământul romanului, este indicat de prezența mottoului: „Stăpăne, stăpane, /Mai cheamă ş-un câne...\". Mihail Sadoveanu transpune în roman toate elementele accesorii scenariului osirian; „poclada\" pe care Vitoria aşază osemintele lui Nechifor; „betişorul alb\" pe care-l poartă eroina; baltagul purtat de Gheorghiţă-Horus (spre deosebire de mit, unde acesta îi revine lui Anubis). "+
                "  Relațiile dintre Vitoria şi Gheorghiţă sunt evidenţiate de marile teme sadoveniene dezvoltate aici: viaţa păstorilor, natura, miturile. Acţiunea reflectă arhitectura complexă a operei, generată de parcurgerea drumului de reconstituire a faptelor care au dus la moartea bărbatului Vitoriei Lipan. Conflictul exterior este de natură să evidențieze împrejurările crimei, săvârșite din motive economice, iar conflictul interior evidențiază frământările Vitoriei în așteptarea soțului, dar și în efortul restabilirii adevărului. Construcţia subiectului se desfăşoară cronologic, urmărind momentele subiectului și relațiile puternice dintre mamă și fiu, căci Vitoria ține să-l determine pe fiul său  a înțelege tragismul existenței. Pentru Gheorghiță călătoria are rolul de inițiere.\n"+
                "  Romanul Baltagul rămâne o scriere memorabilă, nu numai prin conținutul şi multitudinea semnificaţiilor, ci şi prin personajele sale, printre care un loc important îl ocupă Vitoria Lipan, protagonista acestei opere, ea fiind prezentă în toate momentele acţiunii și polarizând în jurul ei celelalte personaje. "+
                "  Autorul îi schiţează, în expoziţiune, prin caracterizarea directă, portretul fizic, care cucereşte prin frumuseţe şi farmec, căci, la cei aproape patruzeci de ani ai săi, ochii ei căprui „aprigi şi încă tineri\", „răsfrângeau lumina castanie a părului\". "+
                "  Împovărată de griji şi de nelinişti, pe lângă manifestările ei exterioare, Vitoria trăieşte un zbucium interior devastator, căci nu mai ştia nimic despre soţul ei, Nechifor, care plecase la iernat cu oile. Femeia se simte „plină de gânduri, de patimă şi de durere\". Bănuiala o mănâncă întocmai „ca un vierme neadormit\" şi ea „se desfăcuse încet-încet de lume şi intrase oarecum în sine\". În relaţia cu Gheorghiţă, se dovedeşte tolerantă şi face din acesta un bărbat curajos, pentru că vrea să-l educe în spiritul tradiţiei, pornind de la îmbrăcăminte, preocupări şi comportament moral, ea urmărind ca fiul să ajungă un gospodar cu avere şi casă. "+
                "  Aceste trăsături morale, redate prin caracterizarea directă, au ca punct de plecare dragostea pe care i-a purtat-o dintotdeauna soţului ei; „Abia acum întelegea că dragostea ei se păstrase ca-n tinereţe\". Femeia găseşte tăria morală de a se rupe din gânduri şi din sirgurătatea ei, pentru a pleca în căutarea acestuia, aşa cum reiese indirect din spusele ei: „N-am să mai am hodină cum n-are pârâul Tarcăului, pân' ce l-oi găsi pe Nechifor Lipan\". În acest scop îşi cheamă fiul, pe Gheorghiţă, faţă de care dă dovadă de dragoste maternă şi de mândrie şi, de aceea, îl primeşte aşa cum se cuvine, arătându-se o gospodină desăvârşită. Pornind de la dialogul pe care-l poartă cu băiatul ei, eroina impresionează prin luciditate şi stăpânire de sine, căci, deşi iniţial hotărăşte să-l trimită doar pe Gheorghiță în căutarea lui Nechifor, îşi dă seama că acesta are nevoie de mintea şi de experiența ei de viaţă, şi pleacă împreună. Este înzestrată cu o inteligenţă ieşită din comun, prezentată indirect, în diverse împrejurări."+
                "  Reuşeşte să-l convingă pe Gheorghiță de necesitatea plecării la drum, aducându-i argumentele cele mai potrivite: „De-acu trebuie să te arăți bărbat. Eu n-am alt sprijin şi am nevoie de brațul tău\". "+
                "  Ordonată, meticuloasă, cu un deosebit simţ practic, înainte de plecare, ea rânduieşte totul cu abilitate şi exactitate, încât niciunul dintre amănunte nu-i scapă. Întreprinzătoare şi prevăzătoare, vinde produsele pe care le mai avea, dar duce peste noapte banii la preot pentru a nu fi prădată. Conştientă de pericolele care-i pândesc pe drum, îi face lui Gheorghiţă un baltag pe care preotul îl sfinteşte, iar pentru sine ia puşca, gândind s-o folosească în caz de nevoie. "+
                "  Fiind o femeie credincioasă, înainte de a pleca, se sfătuieşte cu preotul, merge la mănăstirea Bistrița, unde se roagă la icoana Sfintei Ana, ţine post douăsprezece vineri, se spovedeşte şi se împărtăşeşte, face daruri bisericii. \n"+
                "  Totodată, este şi superstiţioasă, căci ea crede în vise și în semne, în descântece şi în vrăji şi, de aceea, merge la baba Maranda, pentru a afla despre soţul ei. Visul în care Lipan apare întors cu spatele trecând peste o apă neagră şi cântecul cocoşului răsunând o singură dată, cu pliscul întors către poartă, o obsedează şi-i întăresc convingerea că bărbatul ei nu se mai întoarce. Culege cu abilitate informații de la cei din jur, pe care-i iscodeşte, căci dovedeşte o mare pricepere în a intui sufletul oamenilor, pricepere în slujba căreia pune felul său de a vorbi cu aceştia. Aşa cum remarca exegetul Nicolae Manolescu, eroina „trece de la agresivitate la dulceață, e văicăreață  din ipocrizie, intrigantă din calcul, stăpână pe nervii ei şi neobosită\". "+
                "  Felul ei de a vorbi dovedeşte, incontestabil, o inteligență nativă; uneori cuvintele ei sunt veritabile maxime: „Eu te citesc pe tine, măcar că nu ştiu carte\", „Cine nu cearcă nu izbuteşte\", „Toate pe lumea asta arată ceva\", „Cel ce spune multe ştie puține\" etc.; alteori, evidenţiază umor şi ironie, când se adresează argatului Mitrea, ori chiar lui Gheorghiță. Când e cazul, vorba Vitoriei devine ascuțită şi întrebătoare, iar pe cel care nu-i oferă o informaţie pentru atingerea scopului ei îl consideră duşman; „Pe aici te uiţi şi treci, a grăit cu buzele subțiate şi apăsate nevasta. Pe acest dintâi duşman îl dorea mort şi îngropat sub ochii săi''."+
                "  Îi drumul ei intâlneşte o cumetrie şi o nuntă şi, de fiecare dată, respectă tradiția şi obiceiurile strămoşeşti, aşa cum îndeplineşte, mai târziu, toate cele creştineşti pentru înmormântarea şi pomenirea lui Nechifor Lipan. Deşi intâmpină greutăţi în „investigațiile\" făcute, dovedeşte dârzenie, tenacitate şi voință de neînfrânt, deoarece nu renunță şi îşi realizează dorinţa de a-şi găsi bărbatul şi de a-i pedepsi pe ucigaşi. Astfel, spiritul ei justițiar învinge şi, odată ce scopul este atins, Vitoria revine la vechile îndeletniciri, căci viaţa îşi urmează cursul normal."+
                "  Din dragoste pentru soţ, izvorăşte şi setea de viață a Vitoriei, care este copleşitoare, deoarece, odată cu reînvierea naturii, simte că „trupul ar fi vrut să cânte şi să inmugurească.\". Această poftă de viaţă şi de iubire se transmite şi generatiilor viitoare, căci Minodora îi cere mamei să n-o dea „după bătrân şi după urât\". "+
                "  Femeia comunică pe căi neştiute cu elementele naturii care o îndrumă, prin semne, pe calea cea bună. Munteanca îi uimeşte pe cei din jurul său prin însuşirile ei deosebite şi, de aceea, celelalte personaje îşi exprimă punctul de vedere, evidenţiindu-i, prin caracterizare directă, calităţile. Astfel, Gheorghiţă cugetă cu mirare: „mama asta trebuie fermecătoare, cunoaşte gândul omului\". La rândul lui, Calistrat Bogza este la fel de uluit de exactitatea cu care Vitoria a reconstituit totul, aşa cum reiese din mărturia lui de dinainte de a muri: „Și să se ştie că a fost întocmai cum a arătat femeia mortului\". Vitoria Lipan este un personaj complex şi, de aceea' părerile referitoare la ea sunt diferite. Criticul G. Călinescu asociază numele personajului cu cel al lui Hamlet. Alteori este considerată „un suflet tenace şi aspru de munteancă\", „un aspru caracter, de o voinţă aproape sălbatică, aproape neomenoasă (Perpessicius) sau „nereligioasă, vicleană și rea\" (Nicolae Manolescu). \n"+
                "  Acţiunile eroinei şi comportamentul ei relevă toate aceste calităţi şi defecte; astfel, se structurează un caracter complex, în care defectele nu anulează calităţile, ci le impun în realizarea scopului şi a responsabilităţii pe care personajul şi le asumă. "+
                "  Paul Georgescu (în „Polivalenţa necesară\") şi Alexandru Paleologu (în „Treptele lumii sau calea către sine\" a lui Mihail Sadoveanu) au sesizat faptul că Sadoveanu ilustrează, in Baltagul, pasiunea nestinsă, fiind un roman foarte apropiat de structura unei tragedii antice. Eroina îşi concentrează energia în forma morală a datoriei de a elucida ce i s-a întâmplat soţului ei; în acest sens, ea poate fi comparată cu eroinele tragice ale lui Sofocle şi Euripide. "+
                "  Raportat la personajul secundar, Gheorghiţă, „Baltagul\" este un român iniţiatic. Arma, „baltagul\", purtat de Gheorghiţă, are o întrebuinţare simbolică şi magică, rămânând pur, nepătat de sânge. Procesul iniţiatic al fiului presupune o moarte simbolică, adică o coborâre în prăpastia infernală, acolo unde neofitul (neiniţiatul) va fi supus unor încercări-limită, confruntându-se cu imaginea îngrozitoare a rămăşiţelor părintelui său. Gheorghiţă iese din labirintul iniţiatic un om format şi intră într-o nouă etapă existenţială, fiind capabil să preia conducerea familiei. Băiatul de optsprezece ani porneşte pentru prima dată într-o călătorie mai lungă şi decisivă pentru viaţa lui. La sfârşitul cărtii, el intră într-un alt fel de existenţă, cu alte responsabilităţi. Ultima pagină diferă de restul romanului prin faptul că aici, pentru prima dată, Vitoria îi vorbeşte fiului ei, folosind persoana I plural: „Facem cu domnul Toma toate socotelile şi-i plătim cinstit, mulțămindu-i frumos. Plătim preoţilor, oamenilor care s-au ostenit şi tuturora. Pe urmă, stăm şi ne hodinim trei zile, după care facem parastasul întâi tatălui tău\". Pentru a locul tatălui său, Gheorghiţă. are de invaţat o mulţime de lucruri. Deşi vorbeşte la persoana I plural, Vitoria continuă să-i dea sfaturi. Din discursul ei final, băiatul pricepe că trebuie: să-şi plăteasca toate  datoriile, să respecte datinile, să fie gospodar şi prevăzător (cunoaşterea turmelor şi tocmirea păşunii). "+
                "  Gheorghiță parcurge următoarele trepte ale inițierii: copilăria fericită („Pârâul cu bulboanele au fost ale lui. Potecile la zmeură şi mai sus la afine...Poveştile la stână, sara...Ştia să cheme în amurgit ieruncile și căpriorii\"); drumul/labirintul (oboseala, oamenii necunoscuți, lucruri noi, învățături noi) și participarea la evenimente decisive (botez, nuntă, înmormântare, în ordinea firească a viții); veghea înspăimântată (rămâne singur, noaptea, în munte cu osemintele tatălui său, probă de bărbăție echivalentă luptei cu zmeul); lovirea lui Bogza (este gestul revanșator pe care numai bărbatul din familie îl putea face); preluarea responsabilităților (se face treptat și sub stricta supraveghere a mamei). "+
                "  Treptele inițierii din „Baltagul\" se aseamănă foarte mult cu cele din basmul popular. Eroul are aceeaşi vârstă, este supus unor probe pe care le trece cu succes, apoi va lua locul unui conducător. Privind personajele lui Sadoveanu din alt punct de vedere, constatăm că ele corespund celor şase tipuri de poli actanți ai lui Greimas, din Semantică structurală: subiect (Vitoria), obiect de valoare (Nechifor), opozanți (Bogza şi Cuţui), adjuvant (Lupu), destinator (spiritul lui Nechifor) şi destinator (Gheorghiţă). Existenţa actanţilor este strict necesară, deoarece, fără prezenţa lor în text, universul diegetic nu ar prezenta suficient interes. "+
                "  În opinia mea, modul în care tema textului narativ se reflectă în evoluţia relaţiei dintre cele două personaje se bazează pe faptul că Vitoria reconstituie crima pe baza propriilor deducţii, dar şi cu ajutorul lui Gheorghiță, care trebuie să ia locul tatălui dispărut. "+
                "  În concluzie, personajele, deşi nu sunt numeroase, ca în alte romane, capătă valori simbolice prin complexitatea şi consistenţa lor. Structura psihică a ţăranului moldovean este evidențiată de M. Sadoveanu prin surprinderea relaţiilor acestuia cu oamenii, cu lucrurile, cu tradiţiile şi obiceiurile.\n";

        stringBuilder.append(finallyEseu);
        e15.setText(stringBuilder.toString());
    }
}
