package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class baltagCaract extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_baltag_caract);

        TextView caractBaltag = (TextView) findViewById(R.id.caractBaltag);
        TextView e14 = (TextView) findViewById(R.id.e14);

        caractBaltag.setText("Caracterizare Vitoria Lipan");
        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  Tradiţionalist şi modernist în acelaşi timp, Mihail Sadoveanu este autorul unei creații de peste o sută de volume. „Baltagul\" este una dintre capodoperele sale, fiind caracterizat prin concizie, dinamism şi armonie compoziţională. Apărut în 1930, când Sadoveanu se afirmase pe deplin ca scriitor cu o mare capacitate de evocare a lumii satului, „Baltagul\" reprezintă sinteza naturii artistice a prozatorului. "+
                "  Analizând acesată operă, criticul Al. Paleologu propune o viziune inedită de receptare, ce diferă de interpretarea clasică a romanului, ca o continuare a „Mioriței\". Pornind de la un mit esenţial, acela al lui Isis şi Osiris, Paleologu demonstrează că „Baltagul\" este un bildungsroman, cu o accentuată notă iniţiatică, şi observă că mitul acesta se suprapune peste subiectul românesc într-o manieră desăvârşită, până în cele mai mici detalii, povestea Vitoriei în căutarea rămăşiţelor pământeşti ale Nechifor fiind aceea a lui in căutarea trupului risipit în bucăţi al lui Osiris. \n"+
                "  Romanul „Baltagul\" rămâne o scriere memorabilă, nu numai prin conținutul şi multitudinea semnificaţiilor sale, ci şi prin personajele sale, printre care un loc aparte îl ocupă Vitoria Lipan, protagonista acestei opere, ea fiind prezentă în toate momentele acţiunii şi polarizând în jurul ei celelalte personaje. Vitoria Lipan este un personaj complex, şi, de aceea, părerile referitoare la ea sunt diferite. Criticul G. Călinescu asociază numele personajului cu cel al lui Hamlet (din opera omonimă a lui W. Shakespeare). Alteori, este considerată „un suflet tenace şi aspru de munteancă\", „un aspru caracter, de o voinţă aproape sălbatică, aproape neomenoasă\" (Perpessicius) sau „nereligioasă, vicleană şi rea\" (Nicolae Manolescu). "+
                "  Prin caracterizarea directă realizată de către narator, i se schițează, în expozițiune, portretul fizic, care cucereşte prin frumuseţe şi farmec, căci, la cei aproape patruzeci de ani ai săi, ochii ei căprui „aprigi şi încă tineri\", „răsfrângeau lumina castanie a părului\". Împovărați de griji şi de nelinişti, pe lângă manifestările exterioare, Vitoria trăieşte un zbucium interior devastator, căci nu mai ştia nimic despre soţul ei, Nechifor, care plecase la iernat cu oile. Femeia se simte „plină de gânduri, de patimă şi de durere\". Bănuiala o mănâncă întocmai „ca un vierme neadormit\" şi ea „se desfăcuse încet-încet de lume şi intrase oarecum sine\". "+
                "  Aceste trăsături morale, redate prin caraterizare directă, au ca punct de plecare dragostea pe care i-a purtat-o dintotdeauna soţului ei: „Abia acum înţelegea că dragostea ei se păstrase ca-n tinerețe\". Femeia găseşte tăria morală de a se rupe din gânduri şi din singurătatea ei, pentru a pleca în căutarea acestuia, aşa cum reiese din autocaracterizare: „N-am să mai am hodină cum n-are pârâul Tarcăului pân' ce l-oi găsi pe Nechifor Lipan''. În acest scop, îşi cheamă fiul, pe Gheorghiţă, faţă de care dă dovadă de dragoste maternă şi de mândrie şi, de aceea îl primeşte aşa cum se cuvine, arătându-se o gospodină desăvârșită. "+
                "  Pornind de dialogul pe care-l poartă cu băiatul ei, eroina impresionează prin luciditate şi stăpânire de sine, căci, deşi iniţial hotărăşte să-l trimită doar pe Gheorghiță în căutarea lui Nechifor, îşi dă seama că acesta are nevoie de mintea şi de experienţa ei de viață și pleacă împreună. Este înzestrată cu o inteligenţă ieşită din comun, prezentată indirect, în diverse împrejurări. Reuşeşte să-l convingă pe Gheorghiţă de necesitatea plecării la drum, aducându-i argumentele cele mai potrivite: „De-acu trebuie să te arăţi bărbat. Eu n -am alt sprijin şi am nevoie de braţul tău''.\n"+
                "  Ordonată, meticuloasă, cu un deosebit simţ practic, înainte de plecare, ea rânduieşte totul cu abilitate şi exactitate, încât niciunul dintre amănunte nu-i scapă. Întreprinzătoare şi prevăzătoare, vinde produsele pe care le mai avea, dar duce peste noapte banii la preot, pentru a nu fi prădată. Conştientă de pericolele care pândesc pe drum, îi face lui Gheorghiţă un baltag pe care preotul  sfinţeşte, iar pentru sine ia puşca, pe care s-o folosească în caz de nevoie. "+
                "  Fiind o femeie credincioasă, înainte de a pleca, se consultă cu preotul, merge la mănăstirea Bistriţa, unde se roagă la icoana Sfintei Ana, ţine post douăsprezece vineri, se spovedeşte şi se împărtăşeşte, face daruri bisericii. Totodată, este şi superstiţioasă, căci crede în vise şi în semne, în descântece şi în vrăji şi, de aceea, merge la baba Maranda, pentru a afla ceva despre soţul ei. Visul în care Lipan apare întors cu spatele trecând peste o apă neagră şi cântecul cocoşului, rostit o singură dată, cu pliscul întors către poartă, o obsedează şi-i întăresc convingerea că bărbatul ei nu se mai întoarce, deoarece a fost ucis."+
                "  Culege cu abilitate informaţii de la cei din jur, pe care-i iscodeşte, căci dovedeşte o mare pricepere în a intui sufletul oamenilor, pricepere în slujba căreia pune felul său de a vorbi cu aceştia. Aşa cum remarcă Nicolae Manolescu, eroina „trece de la agresivitate la dulceață, e văicăreaţă din ipocrizie, intrigantă din calcul, stăpână pe nervii ei şi neobosită\". Felul ei de a vorbi (caracterizare indirectă) dovedeşte, incontestabil, o inteligenţă nativă uneori cuvintele ei sunt veritabile „Eu te citesc pe tine, măcar că nu ştiu carte\", „Cine nu încearcă nu izbuteşte\", „toate pe lumea asta arată ceva\", „cel ce spune multe ştie puţine\" etc.; alteori, evidenţiază umor şi ironie, când i se adresează argatului Mitrea ori chiar lui Gheorghiţă. Când e cazul, vorba Vitoriei devine ascuțită şi întrebătoare, iar pe cel care nu-i oferă o informaţie pentru atingerea scopului ei îl consideră duşman: „Pe aici te uiţi şi treci, a grăit cu buzele subţiate şi apăsate nevasta. Pe acest dintâi duşman îl dorea mort şi îngropat sub ochii săi\". "+
                "  În drumul ei, femeia întâlneşte o cumetrie şi o nuntă şi, de fiecare dată, respectă tradiţia şi obiceiurile strămoşeşti, aşa cum îndeplineşte, mai târziu, toate cele creştineşti pentru înmormântarea şi pomenirea lui Nechifor Lipan. "+
                "  Deşi întâmpină greutăţi în investigaţiile făcute, dovedeşte dârzenie, tenacitate şi voinţă de neînfrânt, deoarece nu renunţă şi îşi realizează dorinţa de a-şi găsi bărbatul şi de a-i pedepsi pe ucigaşi. Astfel, spiritul ei justiţiar învinge şi, odată scopul atins, Vitoria va reveni la vechile îndeletniciri, căci viaţa îşi urmeză cursul normal. "+
                "  În relaţia cu propriii copii, se dovedeşte tolerantă cu Gheorghiţă şi face din acesta un bărbat curajos, pentru că vrea să-l educe în spiritul tradiţiei, pornind de la îmbrăcăminte, preocupări şi comportament moral, urmărind ca acesta să ajungă un gospodar, având casă şi avere. Din dragoste pentru soţ, izvorăşte şi setea de viață a Vitoriei, care este copleşitoare, deoarece, odată cu reînvierea naturii, simte că „trupul ei ar fi vrut să cânte şi să înmugurească\". Această poftă de viată si de iubire se transmite şi generaţiilor viitoare, căci Minodora îi cere mamei ei să n-o dea „după bătran şi după urât\"."+
                "  În cel de-al doilea capitol al romanlui „Baltagul\" se evidențiază stăpânirea de sine a Vitoriei, forţa acesteia de a-şi ascunde îngrijorarea, păstrând echilibrul şi măsura în toate. Îi cere Minodorei să mănânce şi să nu ia în considerare frământările ei: „- Ba tu să mă laşi cu ale mele şi să mănânci. Tu nu ştii câte am eu, nici câte gândesc.[...] Mănâncă şi mai ales nu te gândi la lunganul acela al dascălului [...]. Cand îl văd că se mai desmiardă cu cântece şi cu vorbe delicate pe-acolo de prin străinătăți, mă bucur care nu se mai află\". Aceste cuvinte atestă şi umorul Vitoriei, dar şi un ascuțit spirit de observaţie. Minodora este apostrofată de mamă, spre a-şi vedea de treburile gospodăreşti, căci: „Oi găsi eu un român aşezat, cu casă nouă în sat şi cu oi în munte, să i te dau şi să scap de tine.\""+
                "  Femeia comunică, pe căi neştiute, cu elementele naturii, care o îndrumă, prin semne, pe calea cea bună. Munteanca îi uimeşte pe cei din jurul său prin însuşirile ei deosebite şi, de aceea, celelalte personaje îşi exprimă punctul de vedere, evidențiindu-i, prin caracterizare directă, calitățile. Astfel, Gheorghiță cugetă, cu mirare: „mama asta trebuie să fie fermecătoare, cunoaşte gândul omului\". La rândul său, Calistrat Bogza este la fel de uluit de exactitatea cu care Vitoria a reconstituit totul, ca în momentul morții să recunoască: „Si să se ştie că a fost întocmai cum a arătat femeia mortului\". "+
                "  Acţiunile eroinei şi comportamentul relevă toate aceste calităţi şi defecte; astfel, se structurează, un caracter complex, în care defectele nu anulează calităţile, ci le impun în realizarea scopului şi a responsabilităţilor pe care personajul şi le asumă. De remarcat este şi diversitatea procedeelor de caracterizare folosite de scriitor: directă, prin descriere, prin părerea celorlalte personaje sau indirectă, prin fapte, prin atitudine, prin relaţia cu celelalte personaje şi prin felul de a vorbi. "+
                "  Confruntarea dintre Vitoria Lipan şi Calistrat Bogza demonstrează inteligență şi energia protagonistei, dar şi încheierea procesului de maturizare a lui Gheorghiță. Vitoria urmăreşte împlinirea legii nescrise pentru pedepsirea ucigaşilor. Atunci când Bogza cere înapoi baltagul, Vitoria întreabă pe fiul ei dacă nu poate citi ceva pe această armă. Scena devine dramatică: Calistrat îşi pierde cumpătul şi se repede la Gheorghiţă să-i smulgă baltagul. Îl loveşte cu pumnul în frunte pe Cuţui, căci „în gospodarul cel mare izbucnise crâncenă mânie\". Vitoria cere să dea drumul câinelui, care era legat, iar Lupu rupe lanțul. Pentru că Bogza s-a năpustit să smulgă baltagul de la Gheorghiţă şi să se apere de câine, „feciorul mortului simți în el crescând o putere mai mare şi mai dreaptă decât a ucigaşului\" [...] Apoi îl lovi scurt cu muchea baltagului, în frunte\". Calistrat Bogza este culcat de oameni pe prispa casei şi, pentru că simte că se stinge, mărturiseşte: „Eu am pălit intr-adevăr pe Nechifor Lipan şi l-am prăvălit în râpă, după cum a dovedit nevasta lui\". "+
                "  Paul Georgescu şi Alexandru Paleologu au sesizat faptul că Sadoveanu ilustrează în „Baltagul\" pasiunea nestinsă, acesta fiind un roman foarte apropiat de structura unei tragedii antice.\n"+
                "  În opinia mea, eroina concentrează energia în forma morală a datoriei de a elucida ce i s-a întâmplat soţului ei. În acest sens, ea poate fi comparată cu eroinele tragice ale lui Sofocle şi Euripide. \n"+
                "  În concluzie, exponentă a unui străvechi spaţiu spiritual, Vitoria este un personaj memorabil. Ea oscilează între superstiţii și creştinism, în sufletul ei fiind prezentă, ca în cazul Antigonei, voinţa de a-şi implini destinul: „Nu stăm, umblăm până găsim ce căutăm. Altă rânduială n-avem.\" ";

        stringBuilder.append(finallyEseu);
        e14.setText(stringBuilder.toString());
    }
}
