package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class baltagTema extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_baltag_tema);

        TextView eseuBaltag = (TextView) findViewById(R.id.eseuBaltag);
        TextView e13 = (TextView) findViewById(R.id.e13);

        eseuBaltag.setText("Baltagul, de Mihail Sadoveanu");
        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  Tradiţionalist şi modernist, în acelaşi timp, Mihail Sadoveanu este autorul unei creaţii de peste o sută de volume. Baltagul este una dintre capodoperele sale, romanul fiind caracterizat prin concizie, dinamism şi armonie compoziţională. Apărut în 1930, când Sadoveanu se afirmase pe deplin ca scriitor cu o mare capacitate de evocare a lumii satului, Baltagul reprezintă sinteza naturii artistice a prozatorului. \n"+
                "  Baltagul a fost interpretat de critica literară ca un roman tradiţional, din punctul de vedere al inventiei narative. Discursul aparţine unui narator auctorial, extradiegetic si omniscient. De cele mai multe ori, asistăm şi la o focalizare internă, întrucât naratorul extradiegetic urmăreşte gândurile protagonistei, pătrunde în conştiința ei şi oferă posibilitatea de a-i înțelege psihologia din interior: „Vasăzică, feciorul dascăltalul  Andrei, care face slujba milităriei la Piatra, tot nu se astâmpără şi tulbură mintile fetei. Vinovat e şi el; vinovată e şi maică-sa, dăscăliţa, căreia are să-i spuie ea cele de cuviință.\""+
                "  Viziunea despre lume pe care o propune M. Sadoveanu în Baltagul porneşte de la întrepătrunderea aspectelor realiste cu cele mitice. \n"+
                "  Titlul romanului face aluzie la securea cu două tăişuri, arma ce va restabili dreptatea. Construcția narativă polifonică face posibilă interpretarea multiplă a discursului narativ, aşa cum observa criticul Paul Georgescu în „Polivalenţa necesară\". Prin urmare, Baltagul poate fi interpretat ca roman mitic, roman social /monografic, roman poliţist, roman iniţiatic, roman de dragoste. "+
                "  Acțiunea romanului este simplă, urmărind un singur fir epic: drumul Vitoriei Lipan în căutarea soţului ei, Nechifor. Structurată în şaisprezece capitole romanul are o acţiune clară cu repere temporale (de toamna până primăvara, cu momente, precum: Sf. Andrei, Postul Mare) şi spaţiale bine determinate (Măgura Tarcăului, Călugăreni, Farcaşa, Borca, Cruci, Vatra Dornei, Broşteni, Sabasa, Suha)."+
                "  În expoziţiune, este evocată imaginea Vitoriei Lipan, îngrijorată din pricina intârzierii soţului ei. Intriga intervine când Vitoria înţelege că Nechifor Lipan „nu vine\", căci semnele rău-prevestitoare nu sunt puţine. Desfăşurarea acţiunii ilustrează drumul parcurs de munteancă alături de fiul ei, Gheorghiţă, în căutarea celui dispărut. Punctul culminant coincide cu scena demascării ucigaşilor, la parastasul lui Nechifor. Deznodământul îl infăţişează pe Calistrat Bogza mărturisind că, împreună cu Ilie Cuţui, l-a ucis pe Nechifor „ca să-i luăm oile\"."+
                "  Analizând această operă, criticul Al. Paleologu propune o viziune inedită de receptare, ce diferă de interpretarea clasică a romanului, ca o continuare a „Mioriței\" . Pornind de la un mit esențial, acela al lui Isis şi Osiris, Paleologu demonstra că Baltagu este un bildungsroman, cu o accentuată notă iniţiatică, şi observă că mitul acesta se suprapune peste subiectul românesc într-o manieră desăvârşită, până în cele mai mici detalii, povestea Vitoriei în căutarea rămăşiţelor pământeşti ale lui Nechifor fiind aceea a lui Isis în căutarea trupului risipit în bucăţi al lui Osiris. "+
                "  Ca roman social a fost interpretat mai ales de Nicolae Manolescu, în „Arca lui Noe\" (cap. O femeie în ţara bărbaţilor), datorită faptului că din el aflăm aproape totul despre felul cum trăiesc muntenii, în zilele de sărbătoare sau de lucru, o existență ancestrală ce se desfăşoară după reguli ce nu pot fi încălcate: „N-ai mai învăţat rânduiala? Nu mai ştii ce-i curat, ce-i sfânt şi ce-i bun de când îţi umblă gărgăuni prin cap şi te cheamă domnişoară!\". Mama refuză categoric valsul, cocul şi bluza, dar mai ales nu acceptă că fata ei s-ar putea mărita cu cineva din afara satului. Cei mai importanţi sunt oamenii pe care  naratorul îi prezintă cu deosebită simpatie: „Locuitorii aceştia de sub brad sunt nişte făpturi de mirare. Iuţi şi nestatornici ca apele, ca vremea; răbdători în suferinţi ca şi-n ierni cumplite, fără griji în bucurii ca şi-n arşiţele lor de cuptor, plăcându-le dragostea şi beţia şi datinile lor de la începutul lumii, ferindu-se de alte neamuri şi de oamenii de la câmpie şi venind la bârlogul lor ca fiara de codru\". "+
                "  Baltagul poate fi considerat roman poliţist din perspectiva cercetărilor întreprinse de Vitoria. Criticul George Călinescu afirma: „În căutarea bărbatului, Vitoria pune spirit de vendetta şi aplicaţie de detectiv\". Opera lui Sadoveanu respectă cu fidelitate schema unui roman poliţist clasic: crima (asasinarea lui Lipan), ancheta (investigaţiile Vitoriei), detectivul (Vitoria Lipan), criminalul (Calistrat Bogza), complicele (Ilie Cuţui), mobilul (banii /oile), rezolvarea cazului şi demascarea vinovaţilor. "+
                "  Romanul iniţiatic (bildungsroman) are în vedere drumul labirintic al lui Gheorghită, al băiatului de optsprezece ani, către cunoaşterea de sine şi cunoaşterea lumii. „Treptele iniţierii din Baltagul se aseamănă foarte bine cu cele din basmul popular. Eroul are aceeaşi vârstă, este supus unor probe pe care le trece cu succes... \"(E. Boghiu, L. Mutoiu). \n"+
                "  Scena coborârii lui Gheorghiţă în prăpastie validează faptul că Baltagul este un bildungsroman: Procesul iniţiatic al fiului presupune o moarte simbolică, adică o coborâre în prăpastia infernală, acolo unde neofitul (neiniţiatul) va fi supus unor încercări limită, se confruntă cu imaginea îngrozitoare a rămăşiţelor părintelui său. Gheorghiţă iese din labirintul iniţiatic un om format şi intră într-o nouă etapă existenţială, fiind capabil să preia conducerea familiei. Băiatul de optsprezece ani porneşte pentru prima dată într-o călătorie mai lungă şi decisivă pentru viaţa lui. La finalul romanului, el intră într-un alt fel de existenţă, cu alte responsabilități. \n"+
                "  Confruntarea dintre Vitoria Calistrat Bogza demonstrează inteligenţa și energia protagonistei, dar şi încheierea procesului de maturizare a lui Gheorghiţă. Vitoria urmăreşte împlinirea legii nescrise pentru pedepsirea ucigaşilor. Atunci când Bogza cere înapoi baltagul, Vitoria îl întreabă pe fiul ei dacă nu poate citi ceva pe această armă. Scena devine dramatică: Calistrat îşi pierde cumpătul şi se repede la Gheorghiţă să-i smulgă baltagul. Îl loveşte cu pumnul în frunte pe Cuţui, căci „în gospodarul cel mare izbucnise crâncenă mânie\". Vitoria cere să dea drumul câinelui, care era legat, iar Lupu rupe lanțul. Pentru că Bogza s-a năpustit să smulgă baltagul de la Gheorghiță şi să se apere de câine, „feciorul mortului simţi în el crescând o putere mai mare şi mai dreaptă decât a ucigaşului. [...] Apoi îl lovi scurt cu muchea baltagului, în frunte\". Calistrat Bogza este culcat de oameni pe prispa casei şi, pentru că simte că se stinge, mărturiseşte: „Eu am pălit într-adevăr pe Nechifor Lipan şi l-am prăvălit în râpă, după cum a dovedit nevasta lui\". Având în vedere mobilul care o determină pe Vitoria să intreprindă cercetări, dragostea pentru soţul său. Baltagul poate fi interpretat şi ca un roman de dragoste. Acest sentiment este trecut prin focul convieţuirii. În ciuda unor certuri şi vorbe iuţi, femeia îşi iubeşte soţul şi ştie că este iubită. Ideea că Lipan s-ar fi putut opri la altă femeie i se pare imposibilă: „Mai bine astfel, într-o privință; să-l ştie mort, deci părăsit de casa lui, în braţele alteia şi în aşternut străin\". Ea nu se sfieşte să-şi mărturisească iubirea: „Căci eu, dragă cucoană Marie, am trăit pe lumea asta numai pentru omul acela al meu\".\n"+
                "  Personajele lui Sadoveanu, aşa cum observau Emilia Boghiu şi Lăcrămioara Mutoiu, oscilează între tipicitate şi atipicitate, în sensul că unele reprezintă tipuri umane: nevasta credincioasă, fata de măritat, flăcăul.\n"+
                "  În opinia mea, tema şi viziunea despre lume ilustrează, în acest roman, o societate rurală, cu obiceiurile şi mentalitatea specifice acestui spaţiu. Altfel spus, este o monografie a lumii pastorale, care ilustrează o filosofie şi un mod de viaţă ancestrale. \n"+
                "  În concluzie, „Baltagul\" este o scriere despre vechile norme de civilizatie, despre confruntarea dintre modern şi arhaic, cu triumful acestuia din urmă. Atmosfera roma-nului este mitică, amintind uneori de aceea din „Creanga de aur\". ";

        stringBuilder.append(finallyEseu);
        e13.setText(stringBuilder.toString());
    }
}
