package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class eliadeRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_eliade_rel);

        TextView relEliade = (TextView) findViewById(R.id.relEliade);
        TextView e21 = (TextView) findViewById(R.id.e21);

        relEliade.setText("Relația dintre Allan și Maitreyi");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  Apărut în anul 1933, romanul „Maitreyi\" reflectă, tema iubirii şi motivul cuplului, un roman pe jumătate autobiografic\", preciza Mircea Eliade. El cuprinde o mitologie a voluptăţii, în care senzualitatea este transfigurată. Povestea este simplă, dar frumusețea ei, seducătoare. Cartea păstrează caracterul unui jurnal, de experienţă trăită. În acest roman, cunoaşterea se realizează printr-o experienţă erotică. E un „amestec de asceză, exaltare metafizică și sexualitate\" (Mircea Eliade). "+
                "  Acţiunea este plasată în India (unde autorul a studiat orientalistică) şi redă experiența trăită de autor în casa profesorului Dasgupta. Cele două, personaje care alcătuiesc cuplul romanului sunt Allan, inginerul european venit la Calcutta, şi Maitreyi, fiica inginerului Narendra Sen."+
                "  Relațiile dintre personajele Maitreyi şi Allan sunt evidenţiate de tema iubirii incompatibile. Acţiunea proiectează relaţiile celor doi în planul diferenţei de mentalități, orientală şi occidentală, diferenţă devenită clară de la mutarea lui Allan în casa lui Sen până la alungarea acestuia de către tatăl fetei. Conflictul interior este generat de raportul dintre intensitatea iubirii tânărului pentru Maitreyi şi luciditatea autoanalizei. Construcţia subiectului pune în evidenţă, dintr-o dublă perspectivă temporală (contemporană şi ulterioară) relaţiile dintre tânărul inginer englez şi adolescenta Maitreyi. \n"+
                "  Allan, bolnav de malarie, este internat în Calcutta, într-un spital de boli tropicale. La ieşirea din febră şi din starea de inconştientă, are sentimentul înstrăinării. În perioada convalescenţei este invitat să locuiască în casa inginerului Narendra Sen, unde o intâlneşte pe Maitreyi, fiica acestuia, adolescentă de 16 ani. \n"+
                "  Experienţa în lumea erotică este asemenea unei călătorii în labirint, un fel de încercare iniţiatică. La Mircea Eliade, erosul, acel preaplin al sufletului şi al biologicului, este o confruntare între voinţă şi experimentare morală. Maitreyi este o poveste de iubire trăită până la starea de divinizare, fiindcă personajele aspiră spre absolut. E un jurnal interior al descoperirii iubirii. Pentru Allan, Maitreyi este iubirea unică a vieţii. Tânăr fiind, el parcurge drumul labirintului, al inițierii, iar setea de cunoaştere se manifestă pe mai multe planuri. \n"+
                "  Maitreyi este un amestec de contraste: sobră, indiferentă, dispreţuitoare, provocatoare, profundă, complexă, plină de poezie şi deschidere spre jocul intelectual. Elanurile adolescentine ale Maitreyiei (gestul aruncării florii în care era împletit un fir din părul ei) sunt pentru indiancă „semne\", „hazard\" ce semnifică şi prefigurează destinul misterul se menţine şi în profan, nu numai in sacru. \n"+
                "  Allan are conştiinta mereu alertată: când este un observator rece, când exaltat, când copleşit de plenitudine.  Dominantă rămâne luciditatea personajului - privirea trează asupra sa şi a celor din jur. Personalitatea inginerului Narendra Sen îl marchează definitiv pe Allan, chiar se stabileşte între ei o comuniune deosebită. Eroul îşi caută identitatea, el este un tânăr cu o complexă viață lăuntrică. Este inteligent, însetat de viață, de cunoaştere, de munca pasionantă şi care se exprimă prin realizări concrete, durabile, chiar eterne. Cunoaşterea drumului prin labirint cere sacrificii, fiindcă acumularea unor experienţe se realizează, prin dăruire de sine, prin renunțări, ca un martiraj. Claustrarea îl surmenează. Fiinţa sa e duală, contradictorie, frământată, prea scindată, fiindcă, pe plan psihologic, se dă, o crâncenă luptă. Locuind în casa inginerului Narendra Sen, Allan a receptat realitatea ca un european şi şi-a stabilit unele neconcordanţe cu lumea din Calcutta. Lui i s-a părut că, toți încurajează apropierea dintre el şi Maitreyi, fecioara indiană, senzuală, deşi pură, ca o sfântă. Intuind miracolul femeii indiene, Allan îi dăruieşte lotuși. Lotusul este floarea sublimului, a elevaţiei în India. Maitreyi simbolizează mentalitatea indiană, cu rădăcini într-o cultură foarte veche, cu un fond filosofic. \n"+
                "  În acest roman, sunt relevate fazele aprinderii, instalării, creşterii şi apoteozării unei iubiri năruite brutal şi abrupt din afara cuplului. Realitatea l-a descumpănit pe Allan căci drumul cunoaşterii rămâne contradictoriu, cu enigme. Iubirea celor doi este descoperită inconştient de Chabu, sora de 11 ani a Maitreyiei. \n"+
                "  Pentru ceremonia logodnei, desfășuratăîn parc, seara, este pregătit un inel ce prezintă doi șerpi împletiți(din fier și aur), unul simbolizând virilitatea, altul feminitatea. Această logodnă este una cosmică, o nuntă în cer ce duce la eliberarea de obsesia păcatului. \n"+
                "  Noțiunea de iubire la indieni este mult mai cuprinzătoare decât la europeni. Dovada sunt: ataşamentul pentru un copac de care Maitreyi şi Chabu sunt îndrăgostite, fascinaţia Maitreyiei pentru Tagore, care îi fusese guru, părinte spirituat. Este, în ambele cazuri, un fel de dragoste mistică, o iubire dusă până la divinizare."+
                "  Allan dorea să treacă la hinduism, spre a înlătura orice piedică în drumul iubirii cu Maitreyi. Aceasta aparţine unor orizonturi geografice și spirituale încărcate de semnificații. India nu a părăsit, cum a făcut Occidentul, puterea intuitivă, elanul mistic. În India, cultul pentru femeie atinge supremaţia spirituală. Orice femeie este o DEVI, o zeiţă; ea întruchipează jertfa creatoare, mama. Orice femeie este adorată pentru că este sau va fi mamă. Viaţa femeii este determinată de ursită, de karma, iar integrarea lui Allan în ritmurile spiritualităţii indiene face din Maitreyi o devi. \n"+
                "  Atracţia europeanului faţă de exotismul culturii, al mitologiei, al filosofiei indiene, faţă de mentalitățile erotice cu inserție în secret sunt evidente. Această inserție de secret determină evadarea lui Allan spre o lume a sublimului magic. \n"+
                "  Când, într-un stadiu al erosului, îşi atingeau mâinile ori picioarele, conform unei tradiții (gest de prietenie), Maitreyi era câstigată, numai de joc, de voluptatea amăgirii, nu de ispită. Treptat, se produc mutaţii, emoţia erotică a fetei suspendă provizoriu jocul, dar numai pentru o clipă. Jocurile Maitreyiei ţin de ritualul erotic şi mistic, îmbogățesc pasiunea. Maitreyi creează, prin ritualul ei solemn, iluzia obţinerii absolutului. Distincţia, intelectualismul, elevarea spirituală o caracterizează pe adolescentă. Prin Maitreyi, paradisul pierdut rămâne o aspiraţie, acesta este dorit, căutat şi descoprit în eul său prin spiritualizare. Eroina își făureşte o mitologie a ei, creaţia aceasta emană  din infinită iubire. Pentru ea, într-o ipostaziere sacră, Allan este: „soare\", „aer\", „floare\", „zeu de aur şi din pietre scumpe\", este proiecţia universală şi sacră intangibilă. Este, deci, o permanentă aspiraţie spre absolut. \n"+
                "  Allan este o natură dilematică, dar frământarea sa este, obiectiv, întreţinută de realităţi care necontenit îl descumpănesc. Elementul principal, de perpetuă contrariere a lui Allan, este chiar manifestarea Maitreyiei, pe care el o resimte ca fiind altceva decât obişnuita strategie feminină de aţâţare, căci exprimă un suflet bogat singular. Sunt urmărite meandrele, infinitele nuanţe ale unui comportament care intrigă, provoacă, promite, retrage ceea ce avansase, rectifică ceea ce păruse spus limpede şi definitiv, trecând totul în domeniul unei ambiguităţi simbolice. \n"+
                "  Scriitorul nu evocă, ci invocă o experienţă profundă pe care o retrăieşte prin povestire. Tehnica narativă folosită de Mircea Eliade face ca personajul Maitreyi să apară ca într-o scenă, prin prezenţă nemijlocită sau prin evocare. \n"+
                "  Voit, romanul păstrează, până la sfârşit, un fel de voalare a portretului eroinei, dezvăluind trăsături care se sustrag elucidării. Misterul Maitreyiei este infinit şi curge în tainele universale. Imposibila clarificare, pe calea lucidității, îi întreţine lui Allan o dorință vie, o patimă a descifrării.\n"+
                "  Nuanţele comportamentale, meandrele existențiale îi produc derută. El se află pe terenul unor ambiguități simbolice, al unor mituri şi concepții filosofice nepătrunse de el. Remarcabile sunt şi următoarele trăsături: tehnica narativă a confesiunii, farmecul liric, autenticitatea, sinceritatea, vocabularul bogat, plin de nuanțe, nervozitatea tonului, divagațiile culturale. \n"+
                "  Romanul ilustrează şi caracterul nefast al pasiunii. Căderea e stranie, aduce supliciul, martirajul. Este o carte „cu destin de miracol în cariera unui scriitor şi chiar a unei generaţii\", afirma Pompiliu Constantinescu: „Este cea mai frumoasă, şi mai tristă carte\" (Mihail Sebastian), ordinea artisticului absolut, Maitreyi rămâne totuşi scrierea sa cea mai bună... prin linia ei de simplitate expresivă, prin tensiunea înaltă a evocării poetice şi capacitatea de a fi impus în literatura română un personaj feminin a cărui putere de seducţie rămâne aceeaşi după. decenii.\" (Gabriel Dimisianu) \n"+
                "  În opinia mea, modul in care tema textului narativ se reflectă în evolutia relaţiei dintre cele două personaje se bazează, pe concepţia despre iubire a celor doi tineri, exponenți ai unor mentalităţi diferite: orientală şi occidentală. \n"+
                "  În concluzie, în stilul autenticităţii promovate în epoca interbelică, Mircea Eliade analizează, revelaţiile tulburătoare ale omului care întâlneşte iubirea autentică. ";
        stringBuilder.append(finallyEseu);
        e21.setText(stringBuilder.toString());
    }
}
