package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class eliadeTema extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_eliade_tema);

        TextView eseuEliade = (TextView) findViewById(R.id.eseuEliade);
        TextView e19 = (TextView) findViewById(R.id.e19);

        eseuEliade.setText("Enigma Otiliei, de G. Călinescu");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  Critic şi istoric literar, dar şi romancier, poet şi dramaturg, G. Călinescu este o personalitate remarcabilă a literaturii române. El s-a diferenţiat programatic de scriitorii epocii sale, devenind autorul primelor romane citadine de factură clasică, nu analitice, nici psihologice, aşa cum au scris Camil Petrescu, H. Papadat-Bengescu, Anton Holban. "+
                "  Publicat în 1938, „Enigma Otiliei\" apare la sfârşitul perioadei interbelice, de puternică afirmare a acestei specii. Opera lui George Călinescu este un roman realist, de tip balzacian. Astfel realismul se concretizează prin: temă, simetria semnificativă (structură închisă), specificul secvenţelor narative, portretizarea personajelor. Balzacianismul este ilustrat chiar de la început prin grija pentru precizarea locului şi a timpului acţiunii: „Într-o seară de la începutul lui iulie 1909, cu puţin înainte de orele zece, un tânăr de vreo optsprezece ani, îmbrăcat în uniformă de licean, intra în strada Antim...\". Tot de balzacianism ţin si tehnica detaliului semnificativ, precum si structura personajelor, încadrate în tipare caracterologice. Felix Sima este tânărul onest; moș Costache Giurgiuveanu este tipul avarului; Stănică Raţiu este arivistul, în timp ce Otilia ilustrează feminitatea, fără a putea fi încadrată într-o formulă limitativă. O trăsătură a formulei estetice moderne este ambiguitatea personajelor. Moş Costache nu este un avar dezumanizat. El nu şi-a pierdut instinctul de supravieţuire (cheltuieşte pentru propria sănătate) şi nutreşte o iubire paternă sinceră pentru Otilia. El este o combinație între două caractere balzaciene: avarul (moş Grandet) şi tatăl (moş Goriot). Pascalopol o iubeşte pe Otilia, în acelaşi timp, patern şi viril. Felix nu este ambiţiosul lipsit de scrupule, ci un adolescent orfan, capabil de a iubi dezinteresat, dar hotărât să-şi facă o carieră; se bazează pe luciditate şi pe profunzime intelectuală. Arivistul Stănică Raţiu este şi un demagog al ideii de paternitate, escroc şi pretins principial, hoţ și sentimental. Un alt aspect modern (naturalismul) este interesul pentru procesele psihice deviante, motivate prin ereditate şi mediu: alienarea și senilitatea. Simion Tulea reprezintă categoria estetică a urâtului, grotescul. Titi, fiul retardat care se îndreaptă spre demenţă, este o copie a tatălui. Aurica, fata bătrână, invidioasă şi rea, este o copie degradată a mamei; obsesia fiicei (căsătoria) se aseamănă. (prin faptul că îi guvernează existenţa) cu obsesia mamei (moştenirea). "+
                "  Romantismul textului este susţinut de gruparea antitetică a personajelor (de exemplu, moş Costache şi Pascalopol), de analiza sentimentului erotic ce implică accente lirice în cazul iubirii dintre Felix şi Otilia, de câteva descrieri livreşti într-un registru fantastic (de exemplu, descrierea câmpiei Bărăganului). \n"+
                "  Compoziţional, discursul narativ este structurat în douăzeci de capitole, numerotate cu cifre, fără titluri. Prin temă, romanul este balzacian şi citadin, deoarece se constituie ca o frescă a burgheziei bucureştene de la începutul secolului al XX-lea, prezentată în aspectele ei esenţiale, sub determinare social-economică (banul ca valoare într-o societate degradată moral). Imaginea societăţii constituie fundalul pe care se proiectează formarea unui tânăr. Romanul e realist-balzacian prin cultivarea unor detalii, ca motivul moştenirii şi al paternităţii. \n"+
                "  Titlul iniţial al romanului, „Părinţii Otiliei\", ilustra motivul literar al paternitătii, întocmai ca în romanul lui Balzac, Moş Goriot. Editorului i s-a părut mai sugestiv titlul Enigma Otiliei, deşi G. Călinescu însuşi precizează că: „...nu Otilia are vreo enigmă, ci Felix crede o are. Pentru orice tânăr de douăzeci de ani, enigmatică va fi, în veci, fata care îl va respinge, dându-i, totuşi, dovezi de afecţiune.\" \n"+
                "  Discursul urmăreşte mai multe planuri narative, care vizează destinul unor personaje, prin acumularea detaliilor: destinul Otiliei, al lui Felix, al membrilor clanului Tulea, al lui Stănică Raţiu etc. Unul dintre planurile operei ilustrează lupta dusă de membrii familiei Tulea pentru obținerea moștenirii lui Costache Giurgiuveanu, în detrimentul Otiliei Mărculescu. Al doilea plan prezintă destinul lui Felix Sima, care, rămas orfan, vine la Bucureşti pentru a studia medicina şi locuieşte la tutorele său. El trăieşte iubirea adolescentină pentru Otilia, simţindu-se derutat de atenţia pe care aceasta i-o acordă lui Pascalopol. \n"+
                "  Succesiunea momentelor epice este redată prin înlănțuire (respectarea cronologiei faptelor), dar şi de inserţia unor micronaraţiuni. Se remarcă realizarea scenică a unor fragmente, precum acela din capitolul al XVIII-lea, în care se evocă reacţiile diverselor personaje la „atacul\" suferit de moş Costache. În acest context, dialogul conferă veridicitate si concentrare epică.\n"+
                "  „Enigma Otiliei\" poate fi interpretat ca roman al educaţiei sentimentale, limitând aspectul moral la personajul principal şi transformând restul protagoniştilor în apariţii tipice. Incipitul romanului realist-balzacian ilustrează descinderea în timp („într-o seară de la începutul lui iulie 1909\") şi spaţiul (descrierea străzii Antim şi a casei lui moş Costache Giurgiuveanu). Tot acum sunt prezentate, întocmai ca pe o scenă aglomerată, principalele personaje, sugerându-se astfel conflictul. Finalul se realizează simetric, evocându-se din nou strada Antim: „Prefacerile nu schimbaseră cu totul caracterul străzii. Casa lui moş Costache era leproasă, înnegrită. [...]. Nu mai părea să fie locuită\". Această simetrie semnificativă este realizată din perspectiva personajului raissoneur, în două momente ale existenţei sale (pe când era „un tânăr de vreo optsprezece ani\" şi aproximativ zece ani mai târziu, după război). "+
                "  Acţiunea romanului începe cu evocarea lui Felix, orfan, absolvent al Liceului Internat din Iaşi, care vine la Bucureşti, în casa unchiului şi a tutorelui său legal, pentru a urma Facultatea de Medicină. Costache Giurgiuveanu este stăpânit de instinctul avariţiei, astfel că ezită să-l primească pe Felix. Bătrânul o creşte pe fiica sa vitregă, având intenţia de o înfia, dar se teme de Aglae, „baba absolută fără cusur în rău\", care urmăreşte in de aproape fiecare mişcare ce ar putea pune în pericol moştenirea fratelui ei. "+
                "  Expoziţiunea este realizată prin fixarea acţiunii în timp şi spaţiu, în manieră balzaciană. Strada, dar şi casa lui moş Costache sunt descrise minuţios, prin prezentarea amănuntelor arhitecturale, aparţinând unor stiluri diferite. Casa bătrânului este veche, părăginită, decoraţiunile sunt ieftine, ceea ce sugerează unele trăsături ale proprietarului: incultura, zgârcenia, delăsarea. Familiarizarea lui Felix cu acest mediu se realizează prin procedeul restrângerii treptate a cadrului, de la străzi, la case, la interioare, la fizionomia si gesturile locatarilor (tehnica focalizării). \n"+
                "  Felix este intâmpinat într-un mod bizar de moş Costache, căci acesta pretinde a nu şti cine este tânărul „Nu-nu-nu ştiu... nu-nu-stă nimeni aici, nu cunosc\". Proprietarul imobilului din strada Antim este „un omuleţ subţire şi puţin încovoiat\", având capul „atins de o calviţie totală\" şi faţa „aproape spână\". \n"+
                "  Sub pretextul unui joc de table, sunt reunite aproape toate personajele în salonul bătrânului Sunt realizate portretele fizice şi vestimentare ale personajelor, portrete ce vor fi dezvoltate pe parcursul operei. Bătrânul avar, „clanul\" Tulea, Pascalopol, Otilia sunt ipostaze evocate sugestiv, creionate prin statutul lor în familie sau prin alte detalii biografice. \n"+
                "  Intriga se dezvoltă pe două planuri: unul dezvoltă istoria unei moşteniri, iar celălalt ilustrează destinul lui Felix Sima. Lupta pentru intrarea în posesia averii lui moş Costache aminteşte de afirmația lui Balzac: „Zeul la care se închină toţi este banul\".Bătrânul, proprietar de imobile, restaurante, acțiuni nu îndrăzneşte s-o infieze pe Otilia, pentru că, se teme de ura Aglaei, dar şi de cheltuială. Într-adevăr, „clanul\" Tulea vânează banii lui moş Costache, iar sora bătrânului reacţionează exclusiv sub imboldul setei de înavuțire. Cu un instinct feroce de proprietate, Aglae consideră firească deteriorarea sentimentelor de familie. Unul dintre intruşii romanului, Stănică Raţiu, va intra, în final, în posesia bunurilor lui moş Costache, pe care îi ia de sub salteaua acestuia, provocându-i moartea. Stănică dă dovadă de ubicuitate şi susține intriga romanului, până la rezolvarea în deznodământ: Stănică o părăseşte pe Olimpia, Aurica nu se căsătoreşte, iar Otilia îl acceptă drept soţ pe Pascalopol, în defavoarea lui Felix.\n"+
                "  Planul formării tânărului Felix urmăreşte experienţele trăite de acesta de la venirea în casa tutorelui său. Tânărul se îndrăgosteşte de Otilia, care, văzută cu ochii lui, este o enigmă. Felix doreste să-şi facă o carieră şi surprinderea gândurilor sale este edificatoare: „De duşmănia sorții mi-e frică. Mi-e frică să rămân egal cu Titi, cu Stănică, cu ceilalți, să mă confund cu ei, să fiu , prin forța împrejurărilor, silit să mă aplec în fața lor. Trebuie să mă deosebesc, neapărat, prin ceva\". Otilia îl iubește pe Felix, dar, după moartea lui moș Costache, pleacă împreună cu Pascalopol, se căsătoreste cu el, lăsându-i tânărului libertatea de a-și realiza ambițiile. Felix reprezintă omul superior, capabil să se desprindă de contingent spre a se înălța în lumea ideilor. \n"+
                "  În epilog, se evocă intâlnirea lui Felix cu Pascalopol „în tren, în drum spre Constanţa\". Moşierul mărturiseşte că i-a redat Otiliei libertatea de a-și trăi tinerețea, iar aceasta a devenit soţia unui „bărbat exotic\". Felix si Otilia sunt vocile simbolice ale autorului, ipostaze ale condiţiei umane oscilând între rațiune și sentiment. \n"+
                "  Conflictul romanului se bazează, deci, pe relaţiile dintre două familii înrudite, a lui Costache Giurgiuveanu şi a Aglaei, un conflict de natură succesorală, aşa cum s-a văzut. Conflictul erotic priveşte rivalitatea adolescentului Felix şi a maturului Pascalopol pentru mâna Otiliei. Pornind de la teza „obiectul romanului este omul ca fiinţă morală.\", G. Călinescu distinge două feluri de indivizi, în funcţie de capacitatea de adaptare la lume: cei care se adaptează moral (au o concepţie morală asupra vieţii: Pascalopol, Felix) şi cei care se adaptează automatic, instinctual (organizaţi schematic şi ilustrând câte un tip uman: cocheta, fata bătrână, avarul, „baba absolută\", dementul senil). \n"+
                "  „Enigma Otiliei\" rămâne un „roman critic prin excelenţă\" (Nicolae Manolescu), deoarece autorul are vocaţia de a comenta viaţa. Scriitorul a dorit să demonstreze vitalitatea formulei balzaciene, într-un moment în care romanul nostru se îndrepta spre formula lui Proust sau a lui Gide, considerând că romanul românesc n-ar putea fi decât epic şi obiectiv. \n"+
                "  Pentru portretizarea personajelor, autorul alege tehnica balzaciană a descrierii mediului şi a fizionomiei, făcând posibilă deducerea trăsăturilor de caracter. Portretul balzacian pornește de la caracterele clasice, cărora realismul le conferă dimensiune socială și psihologică. Romanul realist- tradițional devine o adevărată comedie umană, plasând, deci, în context social, personaje tipice. Călinescu depăşeşte, însă, estetica realistă şi pe cea clasică. \n"+
                "  În mod direct, naratorul oferă detalii despre starea civilă și gradele de rudenie ale personajelor, reunite, sub pretextul jocului de table, la începutul romanului. Singurii intruşi portretizaţi acum sunt Felix şi Pascalopol. Prin caracterizare indirectă (fapte, gesturi, vestimentaţie, replici), se completează „fişele\" biografice ale personajelor. \n"+
                "  O excepţie de la „determinismul\" balzacian o constituie portretul Otiliei, realizat prin tehnici moderne: comportamentismul şi reflectarea poliedrică. Otilia este fascinantă si exercită o atracţie irezistibilă pentru majoritatea celor din jur. Ea este expansivă, capricioasă, dar şi onestă. Îi declară lui Felix că îl iubeşte, dar oscilează între acest sentiment şi nevoia de echilibru. \n"+
                "  În ansamblu, caracterizarea personajelor se bazează pe ideea balzaciană, potrivit căreia mediul işi pune amprenta asupra evoluţiei individului. Tipurile (personajele tipice) întruchipează: avarul, arivistul, fata bătrănă, „baba absolută\", moşierul rafiant, maniacul,  „eternul feminin\". Acestea sunt construite progresiv, pornind de la detalii exterioare: descrierea locuinţei, a fizionomiei, a gesturilor, în ideea de a sugera faptul că detaliile oferă posibilitatea de a înţelege întregul. Secvenţa din incipit este realizată prin metoda realist-balzaciană: situarea exactă în timp şi spaţiu, veridicitatea, susţinută prin detaliile topografice, notarea detaliului semnificativ. Intrarea în universul cărţii se realizează printr-o tehnică a cercurilor concentrice prin care ne apropiem, prin mişcări succesive, de un spaţiu și un orizont existențial din ce în ce mai îngust. Descrierii care porneşte de la o geografie reală îi urmează o secvenţă-cheie, reunind toate personajele romanului. Secvenţa reuniunii familiale din salonul casei Giurgiuveanu prilejuieşte prezentarea personajelor în ipostaze definitorii, surprinderea relaţiilor dintre ele, fixarea conflictului. \n"+
                "  În opinia mea, arta călinesciană reprezintă sinteza unor formule, de unde impresia de tradiţie şi de inovaţie, în acelaşi timp. „Enigma Otiliei\" este o operă pe care Mircea Cărtărescu o consideră metaroman (roman despre roman) şi care anticipează postmodernismul. \n"+
                "  În concluzie, „Enigma Otiliei\" este un roman realist (balzacian), dar depăşeşte modelul realismului clasic; este, după cum s-a spus, de un balzacianism fără Balzac, prin spiritul critic şi polemic, prin valorificarea unor elemente ale modernităţii. \n";
        stringBuilder.append(finallyEseu);
        e19.setText(stringBuilder.toString());
    }
}
