package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class harapRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_harap_rel);

        TextView relHarapAlb = (TextView) findViewById(R.id.relHarapAlb);
        TextView e3 = (TextView) findViewById(R.id.e3);

        relHarapAlb.setText("Relatia dintre Harap-Alb si Span");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  ,,Povestea lui Harap-Alb\" a apărut la 1 august 1877,  în ,,Convorbiri literare\", fiind reprodusă, în același an, în ,,Timpul\". Povestea e apreciată pentru ,,ritmul trepidant al narațiunii, gigantescul viziunii, umor\" (V. Streinu), este o sinteză de ,,realism și fabulos\" (G. Călinescu).\n"+
                "  Ion Creangă respectă forma obligatorie a unui basm, dar inovează și o contrazice. Opera poate fi interpretată ca o creație realistă (așa cum este abordată de G.Călinescu), sau ca una cu substrat mititc (Vasile Lovinescu - Creangă și creanga de aur).\n"+
                "  Personajele sunt ,,ființe de hârtie\", cum le numea Roland Barthes. Trăiesc numai în lumea ficțiunii, nu au consistență, dar mimează realitatea și uneori ,,concurează starea civilă\". Referindu-se strict la personajele de poveste, Vladimir Propp, în ,,Morfologia basmului\", găsea șapte mari tipuri: răufăcătorul, donatorul/furnizorul, ajutorul, fata de împărat (personajul căutat) și tatăl ei, trimițătorul, eroul, falsul erou.\n"+
                "  Cercetătorul specifică faptul că într-un basm nu este obligatoriu să apară toți acești actanți și că un actor poate însuma mai multe roluri. Schema actanților în ,,Povestea lui Harap-Alb\" este următoarea: Harap-Alb etse eroul; Spânul este răufăcătorul , dar și trimițătorul; calul este ajutorul; Sfânta Duminică este donatorul; frații sunt falșii eroi; se adaugă la această schemă fata împăratului Roș și tatăl ei.\n"+
                "  Relațiile dintre personaje, precum Harap-Alb și Spânul, sunt evidențiate de însăși tema basmului, constituită de lupta dintre bine și rău. Acțiunea cuprinde, în desfășurarea sa, încercările prin care trece fiul de crai, înainte și după ce Spânul îl subjugă. Întregul conflict este generat de relațiile dintre mezinul craiului și antagonist. Construcția subiectului, de la expozițiune la deznodământ, evidențiază două părți distincte, care conțin confruntarea cu Spânul, ce implică și o altă forță a răului, precum Împăratul Roș.\n"+
                "  Din perspectiva formării protagonistului, ,,Povestea lui Harap-Alb\" este un bildungsroman. Astfel, o probă a curajului, condiție obligatorie pentru cel care va urma Împăratului Verde la tron, este aceea a podului. Acest element simbolic evidențiază trecerea către o altă etapă a vieții și mezinul depășește acest obstacol cu ajutorul calului, cu puteri miraculoase, care ,,dă năvale asupra ursului\" (ursul fiind craiul însuși , deghizat, spre a proba destoinicia fiilor). O altă scenă simbolică pentru evoluția protagonistului este aceea a coborârii în fântână. În acest spațiu, în care unii comentatori au văzut un corespondent al peșterii din interiorul labirintului, se produce o schimbare a identității celui care intră ca fiu de crai și iese în ipostază de slugă. Bildungsromanul se încheie prin aducerea elementelor magice ce vor contribui la învierea lui Harap-Alb de către fata Împăratului Roș. Fiul de crai s-a maturizat, a renăscut, părăsind identitatea de Harap-Alb și transformându-se într-un erou ce a parcurs calea inițierii. În opera lui Ion Creangă, dialogurile însuflețesc scenele în care figurează mai mulți actori, ca de exemplu, în scena în care, închiși în casa de aramă închisă, cei cinci tovarăși încep să se certe. În acest context, Gerilă, tipul omului cârcotaș, își arată nemulțumirea față de condiția alor săi: ,,-Numai din pricina voastră am răcit casa; căci pentru mine era numai bună, cum era\". Gerilă, căruia i se atribuie porecla Buzilă, se situează în opoziție cu ceilalți(Harap-Alb, Setilă, Ochilă, Pasări-Lăți-Lungilă, Flămânzilă), cărora li se adresează prin epitetele ,,mangosiților și farfasiților\". Îngăduința lui Harap-Alb, faptul că acesta nu-l apostrofează pe cârcotaș sunt elemente care contribuie la un portret favorabil al protagonistului. Gerilă însuși sugerează în finalul scenei: ,,Într-un gând să ne unim, pe Harap-Alb să-l slujim și tot prieteni să fim\".\n"+
                "  La început, prin viclenie și lingușiri, Spânul reușește să-l convingă pe Harap-Alb să îl însoțească la drum. Din momentul în care Spânul îl păcălește pe eroul să intre în fântână, atitudinea lui se modifică: devine ăporuncitor și autoritar, dezvăluind adevărul său caracter.\n"+
                "  Harap-Alb, asemenea oricărui Făt-Frumos din basmul popular, este personajul principal. Numele lui este un oximoron; ,, Harap\", însemnând ,,negru\", poate trimite la ideea de rob, în timp ce ,,Alb\" e atributul stăpânului. "+
                "  Spânul este un personaj fantastic, este ,,omul însemnat\" prin acre răul acționează, mimând atributele binelui. Deși este un exponent al spiritului diavolesc, personajul are un comportament care nu se abate de la logica firescului. El caută să-l convingă pe Harap-Alb sa-l ia ca tovarăș de drum, folosindu-se de persuasiune și inteligență vicleană."+
                "  Harap-Alb, al cărui nume este format din două nonculori, unește în el răul și binele, întunericul și lumina. Se poate observa că eroul este atipic, deoarece reunește, spre deosebire de Făt-Frumos obișnuit(din basmele populare), atât calitățile, cât și defecte. \n"+
                "  Eroul are multiple însușiri: inteligență(la întrebarea ironică a tatălui, ,,Dar aista cal ți l-ai ales?\", baiatul răspunde învăluit, în aceeași manieră în care i s-a pus întrebarea, că merge printre străini și nu vrea să bată la ochi); înțelepciune - la propunerea calului,  să-l ducă ,,ori ca vântul, ori ca gândul\", preferă prima variantă, considerând că ,,dacă mi-i duce ca gândul, mi-i prăpădi\"; bunătate, căci face stup albinelor, ocolește nunta de furnici; sociabilitate (se împrietenește ușor cu personajele monstruoase); fire veselă (,,Râzi , tu, râzi, Harap-Alb!\");fidelitate, fiindcă își respectă jurământul și nu divulgă identitatea Spânului, aduce capul cerbului, deși i se fac oferte extrem de tentante.\n"+
                "  Harap-Alb întruchipează înaltele prinipii morale cultivate de orice basm, adevărul, dreptatea, cinstea, curajul, trăsăturile ce reies indirect, din întâmplari, din propriile vorbe și gânduri, și direct, din ceea ce alte personaje spun despre el. Probele la care este supus reprezintă un drum inițiatic, ,,Povestea lui Harap-Alb\" putând fi interpretată și ca bildungsroman.\n"+
                "  Harap-Alb este un personaj rotund, și nu plat (ca în basmul popular): deși se manifestă în toate secvențele aparent la fel, în fond, suportă progresul inițierii. De asemenea, Harap-Alb este tridimensional (W.Booth), în sensul că iese din tipar, surprinde cititorul, ca atunci când îi dă calului cu frâul în cap sau când se amuză, cu ceilalți tovarăși, de Gerilă.\n"+
                "  Protagonistul poarta mască, este personna. După ce Spânul îi schimbă identitatea el nu este ce pare a fi, dar cititorul competent ghicește adevăratul lui chip."+
                "  Apariția defectelor este o altă surpriză adusă de basmul cult, inovație a lui Ion Creangă: Harap-Alb dovedește nesupunere, căci nu respectă porunca tatălui de a nu se însoți cu omul spân si cu omul roș; naivitate (se lasă păcălit de Spân); manifestează slăbiciune (nu trece proba labirintului/pădurea).\n"+
                "  Spânul nu are bibliografie, deoarece nu este om, este spiritul demonic deghizat, căci, în cele trei apariții, el își schimbă înfățișarea. La cea de-a treia apariție, Spânul nu apelează la supranatural, ci se comportă conform noii sale identități. Harap-Alb îl acceptă pe Spân, pentru că rătăcise drumul. Realist este momentul cănd Spânul îl supune pe Harap-Alb, lipsindu-l de apă, atrăgându-l în fântână, aceasta simbolizând lumea de dincolo.\n"+
                "  Obraznic și prost-crescut, cum vede că ,,i s-au prins minciunile de bune\" și că este primit cu toate onorurile de către Împăratul Verde, devine amenințător cu sluga, îi dă o palmă, cu scopul ,,să facă pe Harap-Alb ca sa-i ieie mai mult frica\". Văzându-se urmaș la tronul împărătesc, Spânul devine arogant și lăudăros, însușindu-și toate meritele lui Harap-Alb, ba mai mult, fălindu-se că știe sa-și strunească slugile:,,Nu știți dumneavoastră ce poama-a dracului e Harap-Alb aista\".\n"+
                "  Dacă acceptăm asimilarea călătoriei lui Harap-Alb cu o lecție de viață, atunci toate personajele din jurul lui sunt niște ,,pedagogi\". Spânul este pedagogul rău, neiertător care îl va pune mereu în primejdie pe Harap-Alb. Spânul va face din el un erou. De altfel, calul va spune despre Spân: ,,și unii ca aceștia sunt trebuitori pe lume câteodată, pentru că fac pe oameni să prindă la minte.\"\n"+
                "  În opinia mea, modul în care tema textului narativ se reflectă în evoluția relației dintre cele două personaje se bazează pe întrepătrunderea realului cu fabulosul. Dacă fiul craiului are, de la început, un statut bine determinat, Spânul ilustrează manifestări ale fabulosului, în ipostaza stranietății sau a maleficului, căci își schimbă înfățișarea, în cele trei apariții succesive.\n"+
                "  În concluzie, ilustrând forțele binelui, protagonistul împrumută din înțelepciunea lumii în evoluția sa. Experiențele parcurse de erou evidențiază un destin excepțional.\n"
                ;

        stringBuilder.append(finallyEseu);
        e3.setText(stringBuilder.toString());
    }
}
