package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class ionRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ion_rel);

        TextView relIon = (TextView) findViewById(R.id.relIon);
        TextView e12 = (TextView) findViewById(R.id.e12);

        relIon.setText("Relatia dintre Ion si Ana");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  Romanul „Ion\" este structurat pe baza a două forme de ficțiune în proză (element de modernitate): „romanul\" (N. Frye, Anatomia criticii), urmărind primul plan al diegezei, destinul personajului eponim/titular, Ion; „anatomia\" (N. Frye), urmărind relaţiile interumane şi realizând o frescă, a vieţii satului. "+
                "   Relaţiile dintre Ion şi Ana sunt evidenţiate de tema operei, aceea a luptei ţăranului pentru pământ într-o lume în care singura măsură a valorii individului este averea. Acțiunea relevă, încă de la început, conflictul operei. Este semnificativă hotărârea lui Ion de a o lua pe Ana cea bogată la joc, deşi o place pe Florica cea săracă. Conflictul central este cel exterior, social, între Ion şi Vasile Baciu, Ana devenind, în acest context, o biată victimă. Conflictul interior, între glasul pământului şi glasul iubirii, demonstrează faptul că Ion îi face curte Anei doar pentru pământul-zestre. Construcţia subiectului evidențiază, de la expozițiune la deznodământ, drama ţăranului sărac ce antrenează şi prăbuşirea unora dintre cei bogaţi, precum Ana sau Vasile Baciu. "+
                "   Personajul central, Ion, este urmărit din perspectiva mai multor instanțe narative (părerile altor personaje), dar motivat auctorial (prezentarea impersonală a naratoru-lui), el beneficiind de o construcţie complexă. "+
                "   Încă din incipit este anunţată pendularea personajului între „glasul pământului\" şi „glasul iubirii\": „şoseaua ...întovărăşind Someşul, când în dreapta, când în stânga\". Descrierea casei lui Ion Pop al Glanetaşului abundă în elemente conotative: „uşa e închisă cu zăvorul\", semn al unui suflet închis, imprevizibil; „acoperişul de paie parcă e un cap de balaur\", fapt ce sugerează impactul nefast pe care-l va avea acest personaj asupra altora. Un alt detaliu semnificativ, „peretii văruiţi de curând de-abia se văd prin „spărturile gardului\" ar putea pune sub semnul întrebării hărnicia personajului. "+
                "   Naratorul realizează numeroase „imersiuni psihologice\" (Norman Friedman), alcătuind o adevărată fişă cazuistică personajului, justificând actele acestuia printr-un complex psihologic cu rădăcini sociale, de exemplu, hotărârea lui Ion de a o alege pe Ana „Florica era săracă...Ana avea locuri si case si vite multe\". Ideea seducerii Anei nu-i aparţine lui Ion; i-o va da, involuntar, Titu, lucru care demonstrează îngustimea minţii lui Ion, urmările acestui fapt validând-o pe Ana ca personaj „pacient\" (personaj care suportă des urmările actelor altor persoane). Incidentul cu Vasile Baciu atestă statutul ingrat pe care-l aveau oamenii săraci, orgoliul exacerbat al protagonistului, iar bătaia dintre Ion şi George Bulbuc relevă violență și caracterul impulsiv."+
                "   Prezentarea unei zile de muncă evidențiază atât hărnicia flăcăului, cât şi patima pentru , pământ a acestuia: „pământul îi era drag ca ochii din cap\"; „Glasul pământului pătrundea năvalnic în sufletul flăcăului, ca o chemare, copleşindu-l. Se simţea mic şi slab, cât un vierme.\" \n"+
                "   Fiinţă primară, renunţă la şcoală pentru a munci pământul: „De ce să-şi sfărâme capul cu atâta şcoală?... şi apoi îi era mai drag să păzească vacile pe câmpul pleşuv..., să fie veşnic însoţit cu pământul\". Secvența muncii evidenţiază şi caracterul oscilant al flăcăului. În timp ce cosea, o întâlneşte pe Ana, despre care gândeşte: „Tare-i slăbuţă şi urâţică, săraca de ea!\" şi pe Florica, pe care „o luă în braţe, o strânse şi-o inăbuşi şi o sărută pe gură cu o patimă sălbatică\". \n"+
                "   În capitolul Ruşinea, asistăm la o pauză descriptivă care pregăteşte punctul culminant: „Ca nişte păsări speriate alergau ţipetele fetei, se risipeau chemătoare prin sat...\". Apoi, ca să-i înăbușe vaietele, o trânti cu capul \"în zăpada care se înroși îndată de sângele ce o podidi pe gură şi pe nas, pe când pieptul ei tot mai horcăia de gemetele neputincioase\". Caracterul violent al lui Ion este sugerat de atitudinea pe care o are în raport cu suferința Anei: „Lasă că bine-i face! Las' s-o bată zdravăn, că i se cade! adăugă Ion cu un rânjet răutăcios care-i înnegri fata\". Denotativele concretizatoare folosite de narator punctează infatuarea și lipsa de scrupule, caracteristice personajului: „Ion se uită la dânsa și-i cântări burta cu o privire triumfătoare\". Faptul că, în spaţiul rural, căsătoria este văzută ca un contract social este relevată de vorbele aruncate către Ana: ,,...cu tine n-am ce să mă sfătuiesc, dar cu dumnealui om vorbi si ne-om chibzui, de s-o putea, că doar oameni suntem... Dar fără tocmeală cum să ne-nvoim?\" \n"+
                "   Atitudinea violentă, a lui Ion, în raport cu Ana, se validează si după ce se căsătoreşte cu ea: „cu o poftă neînfrânată ridică mâna si o lovi greu peste obrazul drept\". G. Călinescu opinează că „in societatea ţărănească femeia reprezenta două braţe de lucru, o zestre și o producătoare de copii. Odată criza erotică trecută, ea încetează de a mai reprezenta ceva pentru feminitate\". Chiar si în momentul în care e pe cale să nască, Ana nu are întelegere din partea lui Ion: „Afurisită muiere! bombăni Ion... ştie că-i soseste ceasul Si vine să fete pe câmp! Bată-i Dumnezeu socotelile de toantă!\". După numai o clipă de bucurie provocată de naşterea copilului, „nicio săptămână n-apucă să treacă şi Ion găsi pricină să-şi snopească iar nevasta\". Ana conştientizează că. pentru Ion a fost doar o modalitate de a intra în posesia pământului: „Prefăcătorie a fost dulceaţa, precum prefăcătorie a fost până și îmbrăţişarea lui cea dintâi... până ce i-a mâncat norocul şi viaţa\" Si în minte i se insinuează gândul sinuciderii. Odată averea obţinută, Ion se dezinteresează total de ceea ce reprezintă nevasta sau copilul său: „- Am să mă omor, Ioane! - Da' omoară-te, dracului, că poate aşa am să scap de tine! mormăi apoi nepăsător, scoţând pe gură şi pe nas fuioare albe de aburi, ca un balaur intărâtat\". "+
                "   Liviu Rebreanu se dovedeşte a fi un fin psiholog, scena spânzurării Anei fiind ilustrativă: „Limba i se umflă, îi umplu gura, încât trebui s-o scoată afară. Apoi un fior o furnică prin tot corpul. Simţi o plăcere grozavă, ameţitoare, ca şi când un ibovnic mult aşteptat ar fi imbrăţişat-o... Ca o fulgerare îi mai trecu prin creieri noaptea, cuptorul, durerea, plâcerea... Pe urmă toate se-ncâlciră\". \n"+
                "   Portretul personajului se conturează nu numai din perspectiva auctorială, ci şi din părerile altor personaje: „Ion e arţăgos ca un lup nemâncat\" (George); „calic ţanţos\" (Vasile Baciu). Sfârşitul protagonistului nu are valenţe justiţiare, ca romantism, este doar un mod de rezolvare, de stopare a unei ascensiuni imposibil de stăvilit altfel. \n"+
                "   În opinia mea, modul in care tema textului narativ se reflectă în evoluţia relaţiei dintre cele două personaje se bazează pe incălcarea unor norme sau legi nescrise: în lumea satului românesc tradiţional, căsătoriile se încheiau în funcţie de avere şi cu îngăduinţa părinţilor, iar fetele trebuiau să-şi păstreze virtutea. Prin depăşirea acestor repere morale, Ana va ajunge să fie dispreţuită nu numai de Ion, ci şi de tatăl ei. \n"+
                "   În concluzie, obsesia de a obţine cât mai mult pământ îl face pe Ion să fie lipsit de afecţiune in relaţiile cu celelalte personaje."
                ;
        stringBuilder.append(finallyEseu);
        e12.setText(stringBuilder.toString());
    }
}
