package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class ionTema extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ion_tema);

        TextView eseuIon = (TextView) findViewById(R.id.eseuIon);
        TextView e10 = (TextView) findViewById(R.id.e10);

        eseuIon.setText("Ion, de Liviu Rebreanu");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = " Specie a epicii de mare întindere, cu numeroase personaje, romanul comunică, indirect, mesajul autorului, prin intermediul naratorului obiectiv, omniscient şi omniprezent, dar şi al personajelor numeroase, implicate într-o acţiune polifonică. "+
                "   Roman realist-obiectiv, Ion se constituie într-o naraţiune la persoana a III-a nonfocalizată (focalizare zero). Viziunea dindărăt implică un narator obiectiv, detaşat, omniscient şi omniprezent, ceea ce-l determină pe Nicolae Manolescu să observe: „Rebreanu este neîndoielnic un artist obiectiv [...]. Romancierul vrea să creeze impresia că e un observator (atât şi nimic mai mult). Un observator omniscient, desigur, dar lipsit de voce proprie (Arca lui Noe). Naratorul infăţişează realitatea plăsmuită nu ca pe o succesiune de evenimente imprevizibile, ci ca pe un proces logic; înlănţuite cauzal şi temporal, faptele sunt credibile, verosimile.\n"+
                "   Tema romanului o constituie lupta ţăranului de la începutul secolului al XX-lea pentru pământ, în societatea transilvăneană.  În aceste conditii, romanul devine o monografle a satului, reflectând mentalitatea colectivă, dar şi obiceiuri legate de marile evenimente din viaţa omului (nașterea, nunta, înmormântarea), relațiile sociale influențate de anumite diferenţe economice sau culturale, relaţiile de familie. Temei centrale i se adaugă aceea a iubirii, dar și aceea a destinului. Prin aceste repere tematice, romanul râmâne ancorat în actualitatea vieţii sociale și ilustrează o lume complexă, în care ţăranul, învățătorul, preotul devin imagini memorabile. "+
                "   Construcția discursului narativ este simetrică, de corp sferoid şi se realizează prin descrierea drumului, din incipit şi final, separând viaţa cititorului de viaţa ficţională a personajelor din roman. Sursa de inspiraţie, specifică prozei realiste, o reprezintă câteva scene de viață care l-au impresionat pe romancier: este vorba despre un ţăran sărac harnic, dar fără pământ şi o tânără, alungată de acasă de tatăl ei. "+
                "   Reperele temporale şi spațiale sunt bine precizate: satul transilvănean Pripas, la începutul secolului al XX-lea. Titlul operei este dat de personajul principal, eponim, sugerând caracterul comun al numelui propriu Ion. Apărut în 1920, romanul „Ion\" de Liviu Rebreanu este structurat în două părți, ale căror titluri sugerează coordonate ale evoluţiei interioare a protagonistului: Glasul pământului şi Glasul iubirii. Titlurile celor 13 capitole (număr nefast) sunt sugestive, dintre acestea putând fi amintite: Începutul, Iubirea, Nunta, Vasile, George, Sfârşitul. Viata ţărănimii si a intelectualității sunt ilustrate prin tehnica planurilor paralele. Trecerea de la un plan narativ la altul se realizează prin alternanţă, iar progresia faptelor este redată prin înlănţuire (respectarea cronologiei evenimentelor narative). Cele două planuri interferează: de exemplu, drama lui Ion este dictată de o vorbă aruncată, inconştient, de Titu Herdelea (personaj raisonneur): „Dacă nu vrea el să ţi-o dea de bunăvoie, trebuie să-l sileşti!\". O altă tehnică literară este aceea a contrapunctului, prin care se ilustrează aceeaşi temă în planuri diferite (nunta ţărănească a Anei corespunde, în planul intelectualităţii, cu nunta Laurei). "+
                "   Acţiunea romanului începe într-o zi de duminică. Incipitul prezintă drumul până la Pripas şi se continuă cu descrierea horei, care se desfășoară în curtea Todosiei, văduva lui Maxim Oprea. În acest moment, al expoziţiunii, sunt ilustrate principalele personaje, detalii spaţio-temporale, de unde veridicitatea romanului. Este momentul în care se reflectă relaţiile sociale, prin însăşi aşezarea privitorilor la horă. Ion o pofteşte pe Ana cea bogată la joc, deşi o place pe Florica, iar acesta este începutul conflictului. Sosirea lui Vasile Baciu, tatăl Anei, la horă şi faptul că îl jigneşte pe Ion este surprins de Liviu Rebreanu astfel că „Flăcăul primi ocara ca o lovitură de cuţit\". Vasile Baciu îl numeşte pe flăcău „sărăntoc\", „tâlhar\", și astfel se conturează intriga romanului. Aşa, Ion va dori să își răzbune rușinea și o va compromite pe Ana, lăsând-o însărcinată, pentru a-l determina pe tatăl fetei să accepte căsătoria. "+
                "   Desfăşurarea acțiunii se organizează în jurul ideii de luptă pentru pământ în satul tradițional, unde posesiunea averii condiţionează respectul. Drama lui Ion este tipică pentru lumea ţărănească. Instinctul de posesiune a pământului şi sărăcia intăresc dorinţa de a alege averea Anei, şi nu iubirea pentru Florica. Astfel, conflictul exterior, social este dublat de conflictul interior, de „glasul iubirii\". Nu lipsesc nici conflictele secundare precum acela dintre Ion şi Simion Lungu, căruia protagonistul luase câteva brazde de pământ, astfel încât: „Inima îi tremură de bucurie că și-a mărit averea\".\n"+
                "   Dincolo de aceste aspecte, se poate vorbi şi despre conflictul tragic dintre om şi o forţă stihială, pământul,Iimpresionantă fiind scena în care Ion îngenunchează şi îl sărută. Memorabil este momentul în care Ion „îşi coborî fruntea şi-şi lipi buzele cu voluptate de pământul ud\". "+
                "   La nunta cu Ana, Ion nu cere acte pentru pământ, dar se simte înşelat, o jigneşte şi o bate pe Ana, îl amenință pe Vasile Baciu. Intră în posesia pământurilor, dar atitudinea sa faţă de Ana nu se schimbă. Sinuciderea Anei este o consecinţă a dezumanizării lui Ion. Acesta nu mai era capabil să vadă în soţia şi fiul său decât garanţia proprietăţii asupra pământurilor.\n"+
                "   Moartea lui Petrişor nu îl oprește pe protagonist să-și retrăiască pasiunea pentru Florica, măritată acum cu George Bulbuc. Se poate spune că deznodământul este previzibil, iar uciderea lui Ion de către soţul Floricăi reprezintă un ecou al brutalității protagonistului. George, simbolizând forţa des-tinului, este arestat, Florica rămâne singură, iar averea rămâne bisericii. "+
                "   Liviu Rebreanu se dovedeşte a fi un fin psiholog, scena spânzurării Anei fiind ilustrativă pentru realismul romanului (scriitorul realist oferă o reprezentare veridică a realităţii): „Limba i se umfiă, îi umplu gura, încât trebui s-o scoată afară. Apoi un fior o furnică prin tot corpul. Simţi o plăcere grozavă, ameţitoare, ca şi când un ibovnic mult aşteptat ar fi îmbrăţişat-o... Ca o fulgerare îi mai trecu prin creieri noaptea, cuptorul, durerea, plăcerea... Pe umnă toate se-ncâlciră\". \n"+
                "   Este sugestivă scena în care protagonistul se apleacă şi sărută pământul: coborî fruntea şi-şi lipi buzele cu voluptate de pământul ud\". Se evidenţiază astfel conflictul tragic dintre un țăran și o forță pe care nu o poate stăpâni: pământul-stihie, pămăntul-ibovnică, pământul-mamă (scena validează intreaga acţiune a romanului). O asemenea atitudine justifică obsesia lui Ion de a obţine repede pământ mult. \n"+
                "   În planul intelectualității ţărăneşti, rivalitatea dintre preot şi învăţător pentru autoritate în sat este defavorabilă lui Zaharia Herdelea. Acesta cunoaşte numeroase dificultăţi materiale, are soţie, două fete de măritat fără zestre, Laura şi Ghighi, precum și un băiat, tânărul entuziast Titu. Învăţătorul zidise casa pe lotul biserici și, cu toate că obținuse încuviințarea preotului, este îngrijorat, când simte că ar putea rămâne pe drumuri. Această ameninţare se datorează degradării relaţiilor dintre Belciug şi Herdelea, căci cei doi au o atitudine complet diferită faţă de faptele lui Ion. Împăcarea acestor intelectuali ai satului se va produce odată cu sfinţirea bisericii, visul împlinit al preotului Belciug. \n"+
                "   Naraţiunea la persoana a III-a ilustrează un roman obiectiv, caracterizat prin neimplicarea afectivă a autorului. Implicit, acesta păstrează veridicitatea subiectului. Sub aspect stilistic, autorul preferă, după propria mărturisire din articolul „Cred\" (1924), „expresia bolovănoasă\", în locul „strălucirilor stilistice\". Precizia, sobrietatea si concizia sunt evidentiate ca trăsături ale operei realiste.\n"+
                "   În opinia mea, prezentarea verosimilă a evenimentelor oferă iluzia realităţii, fapt susţinut şi de stilul neutru, impersonal. Ion rămâne, în literatura naţională, prin protagonistul său, o „figură simbolică\", „erou frust şi voluntar\" (E. Lovinescu). "+
                "   În concluzie, personajele rebreniene acţionează liber, manifestând uneori tensiuni dramatice. Respectul pentru adevăr generează obiectivarea şi realismul romanului. \n"
                ;
        stringBuilder.append(finallyEseu);
        e10.setText(stringBuilder.toString());
    }
 }
