package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class moaraTema extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_moara_tema);

        TextView eseuMoara = (TextView) findViewById(R.id.eseuMoara);
        TextView e7 = (TextView) findViewById(R.id.e7);

        eseuMoara.setText("Moara cu noroc, de Ioan Slavici");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  Ioan Slavici este unul dintre scriitorii care au introdus în literatura română filonul popular al povestirii şi universul satului românesc transilvănean. Scriitorul este un creator de personaje memorabile, un observator lucid şi moralist cu vocaţie de pedagog. Astfel, în nuvela „Moara cu noroc\", Ioan Slavici ilustrează virtuți morale, precum: sinceritatea, cinstea, cumpătarea. \n"+
                "  Viziunea scriitorului are drept fundament convingerea că banul are un efect dezumanizant asupra fiinţei umane (aspect evocat şi în alte nuvele, precum „Comoara\"). Esențială rămâne, în „Moara cu noroc\", confruntarea dintre două caractere puternice, Ghiţă şi  Lică. Se constată, în nuvelă, un transfer al categoriei tragicului, din genul dramatic, în genul epic: Ghiţă este un personaj tragic, el încearcă să-şi depăşească limitele de om neinsemnat şi, pe măsură ce-şi sporeşte câştigul, el crede că n-ar mai fi om dacă ar renunţa. \n"+
                "  „Moara cu noroc\" , alcătuită din șaptesprezece capitole, are o compoziție de tip clasic, unitară, cu acțiune gradată, punct culminant în capitolul al șaisprezecelea, cu deznodământ dramatic, succesiunea momentelor subiectului evidențiind psihologii compleze. Prin procedeul analizei pshihologice, este ilustrat conflictul interior al protagonistului, care trăiește o dramă generată de contradicția dintre dorința de înavuțire și aceea de a-și păstra integritatea."+
                "  Subiectul ar putea fi rezumat astfel: cizmarul Ghiță arendează cârciuma şi hanul de la Moara cu noroc, pentru ca, strângând bani buni, să-şi poată deschide în câţiva ani, la oraş, un atelier mare. Lică îi condiţionează rămânerea la han de colaborarea în afacerile lui necurate. Cârciumarul nu acceptă inițial, nici nu refuză, însă jefuirea unui arendaş şi asasinarea unei femei în preajma hanului îl implică în ochii oamenilor şi ai justiției. Ghiță devine asociatul lui Lică, dar numai pentru a-l da pe mâna jandarmilor. Hotărârea lui, atât de fermă la început, pare a slăbi, moleşită de patima banului uşor câştigat şi de o spaimă insinuantă. Voind să-l vindece de orice duplicitate nedecisă, Lică îl convinge să-i lase pentru o seară nevasta. Ghiţă acceptă, plecând după jandarmi. La întoarcere, nu-l mai găseşte pe Lică şi atunci îşi omoară soţia. Lică se răzbună, ucigându-l şi dând foc casei, ca să nu se afle nimic, apoi se sinucide, lovindu-se cu capul de un stejar. "+
                "  Nuvela „Moara cu noroc\" este de factură realistă, fapt pus în evidenţă de tehnica înlănţuirii cauzale şi temporale. Caracterul realist este evidenţiat şi de surprinderea relațiilor capitaliste, incipiente în satul transilvănean. \n"+
                "  Tema nuvelei o reprezintă consecinţele nefaste ale setei de înavuţire, de unde şi caracterul moralizator al nuvelei. Prin această nuvelă, Ioan Slavici a introdus formula realismului obiectiv, într-un moment în care cel mai frecvent model era proza romantică sau aceea tezistă, de tipul romanului „Ciocoii vechi şi noi\", de Nicolae Filimon.\n"+
                "  Acţiunea se desfăşoară într-un spaţiu şi un timp bine precizate: în ţinuturile din zona Aradului, lângă Şiria şi Ineu, în a doua jumătate a secolului al XIX-lea."+
                "  În expoziţiune, se ilustrează detaliat reperele spaţiale: Moara cu noroc se află în valea dintre dealuri, la o răscruce, pe unde treceau turme de porci spre şi dinspre târg-. „Ori din care parte ar veni, drumeţul se bucură când o zăreşte din culmea dealului pleşuv, căci,venind dinspre locurile rele, ea îl vesteşte că a scăpat norocos, iară mergând spre ele, la Moară poate să găsească ori să aştepte alți drumeți, ca să nu plece singur mai departe\".\n"+
                "  Intriga se declanşează odată cu apariția la Moara cu noroc alui Lică Sămădăul, „om cu stare, care poate să plătească grăsuni pierduți ori pe cei furați\". Desfășurarea acţiunii urmăreşte procesul alienării lui Ghiță. Acesta înțelege că trebuie să accepte implicarea în afacerile necinstite ale lui Lică, astfel că devine „mai de tot ursuz\" faţă de Ana şi copii; el „nu mai zâmbea ca mai inainte\"."+
                "  Punctul culminant îl constituie momentul în care Ghiță acceptă (pentru că „aşa mi-a fost rânduit\") să plece de la han, lăsând-o pe Ana cu Lică. Deznodământul aduce moartea Anei, a lui Ghiță şi a lui Lică, în mod violent, dar ilustrează şi felul în care se mistuie Moara cu noroc, sub acţiunea focului purificator."+
                "  Conflictul este puternic, ceea ce conferă un caracter psihologic acestei opere literare. Apariția lui Lică la moară declanşează acest conflict, ale cărui surse sunt multiple: avariția dezumanizantă a personajului, indecizia sa, faptul că acesta se află la o încrucişare de tentații (conflict de motivații).\n"+
                "  Un prim conflict este acela dintre Ghiţă şi opinia lumii. Sămădăul, dând ordine printre supușii săi, comportă ca un stăpân. Scriitorul ciocneşte cele doua forțe care şi-l dispută pe Ghiţă: este evidentă atracţia acestuia pentru Lică, dar mai puternică este opinia lumii, pe care Ghiţă o simte ca pe o constrângere. \n"+
                "  Există un conflict şi între Ghiţă şi familie: soția, bătrâna, copiii încep să-i apară lui Ghiţă ca nişte duşmani, cu atât mai mult cu cât sunt ființe inocente, fragile şi cer ocrotirea.Pornirea împotriva lor e tulbure, necontrolată. El ceartă slugile, e mohorât şi violent, îi plac jocurile crude şi primejdioase, are gesturi de o brutalitate neinţeleasă faţă de Ana.\n"+
                "  Conflictul dintre Ghită şi Lică ar putea fi rezolvat pozitiv, prin asociere şi acord, din moment ce toate celelalte relaţii sunt resimţite ca obstacole. Colaborarea dintre cei doi, lipsită, o vreme de accidente sociale şi morale, ar fi intrat în ordinea lucrurilor, dar ceea ce schimbă sensul relației este marea vanitate a cârciumarului, care se opune voinței de putere a Sămădăului. Principalul conflict al nuvelei nu este cel între iubire şi arghirofilie, dintre virtute şi păcat, ci dintre vanitate (ca manifestare a individualizare)  şi negarea ei, prin constrângere autoritară.\n"+
                "  Scena depoziției şi a judecăţii are rostul de a demonta mecanismul de pârghii al al faptelor dirijate de mintea diabolică a unui om în stare să-l cuprindă în desfăşurarea lui Lică a jefuit şi şi-a creat un alibi, dar atât de puternic, încât sub pavăza lui mai poate înfăptui, nepedepsit, o crimă. Reuşeşte, în acelaşi timp, să-şi inculpe duşmanii direcţi, pe Săilă şi pe Buză-Ruptă, şi să-l treacă sub bănuială pe Ghiţă. Totul se petrece in răstimpul unei zile şi nopţi, când Sămădăul pradă, ucide, îi lichidează pe duşmani, îl aserveşte pe Ghiţă, îl dezarmează pe urmăritorul Pintea, facându-l ridicol. Orientarea morală a faptelor se menține în umbră şi admirabilă rămâne explozia de putere: Sămădăul ia forma umană a destinului, el este unealta prin care soarta îşi împlineşte cursul. Personajele lui Slavici au convingerea că soarta lor este dinainte stabilită: „Cine poate să scape de soarta ce-i este scrisă?\" se întreabă Ghiță care, de altfel, menționează adeseori convingeri Lică cere lui Ghiță care, de altfel, menționează adeseori convingeri ca: Așa mi-a fost rânduit\", „dacă e rău ce fac, nu puteam să fac altfel\". \n"+
                "  Lică ii cere lui Ghiţa să i-o lase pentru o noapte pe Ana. Ca să-l prindă şi să zădărnicească planurile omului care îl adusese în starea de cumplit impas, bărbatul îşi aruncă drept momeală nevasta, cu speranța că ea va rezista tentației. Această scenă dezvăluie ultima fază a degradării morale a lui Ginţă. Relevantă este afirmația lui Pintea, care-l descalifică pe Ghiță: „Tare om eşti tu, Ghiţă, grăi Pintea pe gânduri. Și eu îl urăsc pe Lică; dar n-aş fi putut să-mi arunc o nevastă ca a ta drept momeală în cursa cu care vreau să-l prind\". "+
                "  Pe parcursul nuvelei, se poate observa existența mai multor faze ale conflictului. Primul gest, după ce sămădăul îi impune lui Ghiţă legea locului, este unul de organizare a defensivei: pune la adăpost femeile, se înarmează şi cumpără doi câini. Ana simte că el s-a schimbat, a devenit ursuz, nu mai zâmbea, ci râdea cu hohote, iar când se mai juca, rar, cu Ana „îşi pierdea lesne cumpătul şi-i lăsa semne vinete pe brațe\". Sămădăul nu apare des, dar regizează o înscenare a fricii insinuante: vine pe furiş, prin locuri neumblate, îmblânzeşte câinii şi se împrieteneşte cu slugile (faza aşteptării). Când Ghiţă este epuizat de aşteptare, Sămădăul atacă. Revoltându-se împotriva constrângerii morale, cârciumarul îi cere lui Lică, agresiv şi umil, nu să-l lase în pace, ci să-l elibereze de constrângere, să-i îngăduie să vină la el în chip liber. El cere condiţii de reciprocitate făţişă. Acum Sămădăul îi aplică lovitura: el îi ia banii adunaţi pînă atunci, dar pretinde că nu îl tâlhăreşte, ci că se „împrumută\". Situaţia devine dilematică pentru Ghiță dacă-l denunţă pe Lică, nu-şi va recapata banii, dacă nu-l denunţă, este obligat să accepte colaborarea cu răul. Ghiţă se simte anihilat."+
                "  Protagonistul se consideră furat şi, perseverând, se amăgeşte prin credinţa că nu face altceva decât să-şi redobândească bunul luat pe nedrept (aceasta este, de fapt, etapa obişnuirii cu răul). Sămădăul distruge imaginea celorlalți despre Ghiță: pune la cale înscenarea prin care cârciumarul urma să apară în ochii lumii drept vinovat (atacul banditesc de la casa arendaşului, uciderea unei femei în apropierea morii). Deşi nu săvârşise niciun rău, Ghiţă este acuzat şi eliberat pe cauţiune. Ca urmare, individualitatea acestuia se prăbuşeşte, iar personajul se dedublează, se înstrăinează de sine. Uciderea Anei este salvatoare, Ghiță încercând să scoată din rău, printr-un alt rău violent, pe fiinţa împinsă de el însuşi în păcat: este, aici, nevoia de a-l suprima pe cel care îi anihilase voinţa, sau pe înlocuitorul lui, adică pe femeia care, prin păcat, se identificase cu seducătorul ei: „Dacă mai adineaoră l-aş fi găsit aici, poate că nu te-aş fi ucis» Esențială rămâne, în „Moara cu noroc\", confruntarea dintre două caractere puternice, Ghiţă şi Lică. Se constată, în nuvelă, un transfer al categoriei tragicului, din genul dramatic, în genul epic: Ghiţă este un personaj tragic, el încearcă să-şi depăşească limitele de om neînsemnat şi, pe măsură ce-şi sporeşte câştigul, el crede că n-ar mai fi om dacă ar renunţa. Ghiţă pare a ilustra definiţia pe care Gabriel Liiceanu o dădea categoriei tragicului: „dacă-ţi depăşeşti limitele, eşti pedepsit, dacă nu ţi le depăşeşti, nu eşti om.\" („Tragicul sau fenomenologia depăşirii\"). "+
                "  În opinia mea, prozatorul realist Ioan Slavici este autorul unei opere complexe, în care sufletul omenesc este înfăţişat din perspectiva unei concepții morale bine conturate. Prin opera acestui scriitor pătrunde în literatura română, analiza psihologică, element definitoriu al prozei moderne."+
                "  În concluzie, rămâne remarcabilă arta scriitorului de a construi dialogul şi monologul interior, dar şi de a analiza gândurile şi trăirile interioare ale personajelor. Toate acestea sunt redate în mod clar, cu o concizie clasică.\n"
                 ;

        stringBuilder.append(finallyEseu);
        e7.setText(stringBuilder.toString());
    }
}
