package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class moaraCaract extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_moara_caract);

        TextView caractMoara = (TextView) findViewById(R.id.caractMoara);
        TextView e8 = (TextView) findViewById(R.id.e8);

        caractMoara.setText("Caracterizarea lui Ghiță");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  „Moara cu noroc\", alcătuită din şaptesprezece capitole, are o compoziţie de tip unitară, cu acţiune gradată, punct culminant în capitolul al şaisprezecelea, cu deznodământ dramatic, succesiunea momentelor subiectului evidenţiind psihologii complexe. Prin procedeul analizei psihologice, este ilustrat conflictul interior al protagonistului, care trăieşte o dramă generată de contradicţia dintre dorinţa de înavuţire şi aceea de a-şi păstra integritatea. \n"+
                "  Personaj principal şi mobil, Ghită ilustrează teza, potrivit căreia dorinţa necontrolată de înavuţire prin concesii poate avea, adeseori, consecinţe nefaste. Personaj rotund, acesta evoluează de la tipicitate la individualizare, devenind, dintr-un simplu cizmar, cu o existenţă modestă, un cârciumar dominat de seducţia sub influența distructivă a unui individ ca Lică Sămădăul, om rău şi primejdios. Acesta este un personaj imobil şi rotund, având ca atribut forţa negativă prin care acționează asupra celor din jurul său. Relaţia dintre cele două personaje evidenţiază, în mod indirect, influența negativă a Sămădăului asupra lui Lică. Ghiţă trăieşte drama alienării, astfel că îşi pierde stăpânirea de sine, încrederea soției, dar şi a altora. Acesta doreşte să strângă bani pentru a-şi angaja zece calfe, ca să repare cizmele oamenilor, căci este un om harnic şi cumsecade. El intuieşte caracterul malefic al sceleratului Lică, atunci când acesta îi cere bani şi informaţii despre turmele de porci şi despre porcarii care trec pe la Moara cu noroc, acesta cedează, aşa cum rezultă din monologul interior: ,,... se gândea la câştigul pe care l-ar putea face în tovărăşia lui Lică\". Oscilând între cele două sensuri existenţiale, reprezentate de personajul feminin Ana, simbol al iubirii, al familiei şi al liniştii, şi nelegiuitul şef al porcarilor, Ghită trăieşte o dramă psihologică. "+
                "  Ghiţă concentrează, în evoluţia sa, întreaga problematică a operei, ce stă sub semnul unei idei morale exprimate la începutul nuvelei prin replica bătrânei: „Omul să fie mulțumit cu sărăcia sa, căci, dacă e vorba, nu bogăţia, ci liniştea colibei tale te face fericit.\". "+
                "  Drumul parcurs de Ghiţă inaintează spre un sfârşit tragic, în ciuda avertismentului soacrei. G. Călinescu arăta că „drama lui este analizată magistral\"; se dezvăluie, în mod indirect, prin acţiune și prin gândurile personajului și în mod direct, prin observațiile celorlalte personaje. Ghiţă este protagonistul unei nuvele psihologice, astfel încât nu este perceput ca prezenţă fizică. Conflictul interior constituie teza morală pe care Ioan Slavici îşi propune o să evidenţieze: Ghiţă trebuie să respecte angajamentul asumat față de familia sa, să figureze ca onest în opinia colectivă, insă el cedează perspectivei ademenitoare pe care i-o oferă Sămădăul. "+
                "  Ghiță pleacă din lumea satului către oraş, părăsind „coliba\", simbol al liniştii patriarhale, şi oprindu-se la Moara cu noroc („trei ani, măcar trei ani să pot sta aici\"). Relaţiile temporale şi spaţiale sunt elemente ce contribuie la conturarea destinului acestui personaj. El parcurge un drum simbolic, lasă în urmă sate şi locuri bune şi apoi coboară către un popas unde „locurile sunt rele\". Acest spaţiu îl dezumanizează pe Ghiţă, iar cârciuma se va dovedi, ea însăşi, un simbol al pierzaniei, nu al protecţiei, ca la Mihail Sadoveanu. "+
                "  Naratorul obiectiv, omniscient, omniprezent surprinde gesturile şi gândurile personajului, toate trădând starea de nesiguranţă, de teamă şi suspiciune. Ghiţă merge la Arad să-şi cumpere două pistoale, îşi face rost de doi câini şi-şi angajează o slugă credincioasă. Toate acestea atestă o stare de tensiune, iar o asemenea situaţie îl înstrăinează de propria familie. Ajunge să regrete faptul că are nevastă şi copii şi ar fi dorit să poată zice: „Prea puţin îmi pasă!\". "+
                "  Autocaracterizarea ilustrează dorinţa lui Ghiță de a se autodisculpa. Acest fapt evocă un fond de umanitate încă nealterat: „Iartă-mă, Ana! îi zise el. Iartă-mă cel puţin tu, căci eu n-am să mă iert cât voi trăi pe faţa pământului...\". Într-un alt moment, sărutându-l pe unul dintre copii, mărturiseşte: „Sărmanilor mei copii, voi nu mai aveţi un tată om cinstit. Tatăl vostru e un ticălos \". Îşi caută sprijinul în jandarmul Pintea, însă îi oferă dovezi numai atunci când îşi poate opri jumătate din banii aduşi de Sămădău."+
                "  Monologul interior-autocaracterizarea evidenţiază efortul personajului de a justifica pentru sine complicitatea cu Lică: „Aşa m-a lăsat Dumnezeu. Ce să-mi fac, dacă e ceva în mine mai tare decât voinţa mea?\". "+
                "  Caracterizarea indirectă pune în lumină momentul culminant al degradării morale a lui Ghiţă: de sărbătoarea Paştelui, acesta o ucide pe Ana. Gestul ar putea avea explicaţia în gelozia şi furia generată de faptul că Ana şi-a petrecut noaptea cu Lică. Însă, protagonistul însuşi o aruncase drept momeală în cursa în care dorea să-l prindă pe Sămădău. Cârciumarul este împuşcat şi el de Răuţ, la porunca lui Lică. "+
                "  Scena depoziţiei şi a judecății are rostul de a demonta mecanismul de pârghii al fatalităţii, al faptelor dirijate de mintea diabolică a unui om în stare să-l cuprindă în desfăşurarea lui: Lică a jefuit şi şi-a creat un alibi atât de puternic, încât sub pavăza lui mai poate înfăptui, nepedepsit, o crimă. Reuşeşte, în acelaşi timp, să-şi inculpe duşmanii direcţi, pe Săilă şi pe Buză-Ruptă, şi să-l treacă sub bănuială pe Ghiţă. Totul se petrece în răstimpul unei zile şi nopţi, când sămădăul pradă, ucide, îi lichidează pe duşmani, îl aserveşte pe Ghiţă, îl dezarmează pe urmăritorul Pintea, făcându-l să pară ridicol. Orientarea morală a faptelor se menţine în umbră şi admirabilă rămâne explozia de putere: Sămădăul ia forma umană a destinului, el este unealta prin care soarta îşi împlineşte cursul. Personajele lui Slavici au convingerea că soarta lor este dinainte stabilită: „Cine poate să scape de soarta ce-i este scrisă.?\" se întreabă Ghiţă care, de altfel, menționează adeseori convingeri, ca: „Aşa mi-a fost rânduit\", „dacă e rău ce fac, nu puteam să fac altfel\"."+
                "  Lică îi cere lui Ghiţă să i-o lase pentru o noapte pe Ana. Ca să-l prindă şi să zădărnicească planurile omului care îl adusese în starea de cumplit impas, bărbatul îşi aruncă drept momeală nevasta, cu speranţa că ea va rezista tentației. Această scenă dezvăluie ultima fază a degradării morale a lui Ghiţă. Relevantă este afirmaţia lui Pintea, care-l descalifică pe Ghiță: „Tare om eşti tu, Ghiţă, grăi Pintea pe gânduri. Și eu îl urăsc pe Lică; dar n-aş fi putut să-mi arunc o nevastă ca a ta drept momeală în cursa care vreau să-l prind\". \n"+
                "  În opinia mea, valoarea deosebită a acestei nuvele constă în modul de realizare a personajelor, în analiza psihologică ce porneşte de la descrierea generală a stărilor psihice, spre a ajunge la observații de mare fineţe. Ioan Slavici transfigurează o lume care şi-a pierdut echilibrul patriarhal, folosind mijloacele prozei realiste, dar recurgând şi la sondajul psihologic al personajelor."+
                "  În concluzie, opera scriitorului ardelean evidenţiază o lume complexă, căreia normele etice îi dau sensul. De altfel, scriitorul afirma: „în gândul meu rostul scrierii a fost întotdeauna spre o viețuire potrivită cu firea omenească.\" („Lumea prin care am trecut\").\n"
                ;

        stringBuilder.append(finallyEseu);
        e8.setText(stringBuilder.toString());
    }
}
