package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class moaraRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_moara_rel);

        TextView relMoara = (TextView) findViewById(R.id.relMoara);
        TextView e9 = (TextView) findViewById(R.id.e9);

        relMoara.setText("Relația dintre Ghiță și Lică");

        StringBuilder stringBuilder = new StringBuilder();

        String finallyEseu = "  „Moara cu noroc\", alcătuită din 17 capitole, are o compoziţie de tip clasic, unitară cu acţiune gradată, punctul culminant regăsindu-se în capitolul al XVI-lea. Deznodământul este dramatic, succesiunea momentelor subiectului dezvăluind psihologii complexe. \n"+
                "  Ioan Slavici este un adept al lui Confucius şi, sub înrâurirea ideilor acestuia, va aplica şi in nuvela „Moara cu noroc\" principalele virtuți morale analizate de filosoful chinez: sinceritatea, cinstea, cumpătarea. Opera devine o pledoarie pentru echilibru moral, înţelepciune, respectarea legilor. În finalul nuvelei, potrivit esteticii romantice (deşi nuvela aparţine realismului), răul este pedepsit. \n"+
                "  Relaţiile dintre personaje, precum Lică şi Ana, sunt evidenţiate de tema operei: oglindirea vieţii sociale, în contextul societăţii ardeleneşti de la sfârşitul secolului al XIX-lea. Acţiunea surprinde prăbuşirea unei familii, prin nerespectarea preceptului moral rostit de mama Anei la începutul nuvelei: „Omul să fie mulţumit cu sărăcia sa, căci, dacă e vorba, nu bogăţia, ci liniştea colibei tale te face fericit\". În timp ce conflictul exterior ilustrează confruntarea lui Ghiţă cu personajul antagonist, Lică Sămădăul, conflict ce o implică pe Ana ca simbol al consecinţelor degradării morale, conflictul interior trăit de Ghiţă este prezentat din perspectiva obsesiilor acestuia pentru relatiile cu Lică, dar şi cu Ana. Construcţia subiectului evidenţiază replicile bătrânei (din prolog şi epilog), care încadrează discursul narativ; această construcţie simetrică, circulară evidentiază eşecul relațiilor dintre cele două personaje. "+
                "  Farmecului straniu ce îl înconjoară pe Lică, personajul negativ al nuvelei, i se adaugă seducţia inteligenţei, misterul puterii sufleteşti. Portretul individual al lui Lică este realizat pe baza „interpretării fiziognomice\" (Silviu Angelescu, „Portretul literar\"), centrat pe determinismul specific balzacian, fiecărui element fizic, corespunzându-i unul moral: „Lică, un om ca de treizeci şi şase de ani... cu ochii mici şi verzi şi cu sprâncenele dese şi împreunate la mijloc. Lică era porcar, insă dintre cei ce poartă cămaşă subţire şi albă ca floricelele\". Ochii mici sugerează răutatea, iar sprâncenele împreunate la mijloc relevă caracterul malefic al personajului, punctat şi în capitolul al XV-lea: „Lică gonea... încât trecea ca blestămul pământului\". Preocuparea deosebită pentru indument, în ciuda unei profesii ca aceea de porcar, sugerează vanitatea, orgoliul excesiv al personajului. "+
                "  În capitolul al XIV-lea, naratorul focalizează atenţia cititorului asupra chimirului porcarului, acesta urmând să fie cauza sfârşitului său (îl uită pe patul Anei şi se întoarce, fiind surprins pe drum de Pintea şi nevoit să, se sinucidă, deoarece nu poate accepta o astfel de înfrângere.): „Lică scoase peste câtva timp din şerparul său plin cu bani patru hârtii, scuipă pe ele şi lipi pe fruntea fiecăruia dintre ţigani câte una\". Ioan Slavici surprinde, cu o mare intuiţie psihologică, sufletul feminin, Ana rămânând un personaj memorabil, mobil, rotund (cf. E. M. Forster). Procesul de transformare a Anei apare ca o trezire a forțelor feminine, puternice şi ascunse. Scriitorul surprinde fascinaţia pe care Lică o va exercita asupra Anei, reacţiile acesteia la vederea sămădăului fiind de teamă, uimire şi admiraţie: „Si cum el împletea, ea privea la degetele lui care strângeau pleata [...] privea la mâna lui care nu atinsese niciodată sapa, nici coarnele plugului, ci numai biciul ușurel și frâul calului, la mâna lui albă şi la degetele lui subţiri si lungi, privea la cămaşa lui albă cu floricele, la faţa lui rasă neted, la mustaţa lui lungă și la ochii lui verzui\". Prin interiorizarea reacţiilor Anei, Slavici surprinde începutul unei afinități a acesteia faţă de Lică, relaţia viitoare (accidentală, totuşi) dintre aceştia fiind anunțată în capitolul al III-lea doar la nivel conotativ: „Ana rămase privind ca un copil uimit la călărețul ce stătea ca un stălp de piatră înaintea ei... privea oarecum speriată de bărbăţia înfăţişării lui\"."+
                "  Sămădăul este un om temut, care supraveghează totul, ştie locurile bune şi rele şi poate „să afle urechea grăsunului pripăşit chiar şi în oala cu varză\". El este, deci, un vârf ierarhic şi justițiar. Tactica sămădăului este de a respinge obişnuitul relaţiilor şi a le impune pe cele specifice lui (momentul în care „imprumută\" banii de la Ghiţă). O altă caracteristică a comportamentului său este promptitudinea adecvării, mobilitatea reacțiilor. \n"+
                "  Sămădăul reprezintă încarnarea unui principiu, a voinţei de putere, dar el nu este instrumentul orb al unei pasiuni mortale, ci o inteligenţă lucidă, stăpână pe actele sale şi pe consecinţele lor. Orgoliul lui este unul de stăpân, care nu doar îşi subordonează oamenii, dar se substituie destinului lor, ţinând locul unui Demiurg pătimaş, batjocoritor şi sadic. Lungul capitol al depoziţiei şi al judecăţii are rostul de a demonta mecanismul de pârghii al fatalităţii, al faptelor dirijate de mintea diabolică a unui om în stare să-l cuprindă în desfăşurarea lui: Lică a jefuit şi şi-a creat un alibi atât de puternic, încât sub pavăza lui mai poate înfăptui, nepedepsit, o crimă. Reuşeşte, în acelaşi timp, să-şi inculpe duşmanii direcți, pe Săilă şi pe Buză-Ruptă şi să-l treacă sub bănuială pe Ghiţă. Totul se petrece în răstimpul unei zile şi nopţi, când sămădăul pradă, ucide, îi lichidează pe duşmani, il aser-veşte pe Ghită, îl dezarmeazăpe urmăritorul Pintea, făcându-l ridicol. Orientarea morală a faptelor se menține în umbră şi admirabilă rămâne explozia de putere. Sămădăul ia forma umană a destinului, el este unealta prin care soarta işi implineşte cursul. "+
                "  Odată cu prăbuşirea autorității soţului său, femeia se simte eliberată de control şi constrângere și singură nu se mai poate domina. Intransigentă şi neiertătoare, ea suportă influenţa inversă a ororii: obişnuinţa cu prezenta răului, prin simplul fapt că cel de lângă ea îl practică. Acum intervine şi influenţa lui Lică. Ieşind de sub autoritatea bărbatului care îi fusese soţ şi aproape părinte, Ana trece sub autoritatea lui Lică, deoarece ea simbolizează femeia supusă, ce nu se poate lipsi de protecţie. \n"+
                "  Sămădăul acţionează, ca în toate situaţiile, printr-o frustrare violentă: n-o bagă în seamă pe Ana, nu-i vorbeşte, n-o priveşte ca pe o femeie frumoasă. Când vrea s-o câştige, întoarcerea de atitudine este spectaculoasă, iar femeia răspunde printr-o efuziune umilă şi recunoscătoare. "+
                "  La primul chef cu lăutari, Lică dansează cu Ana, se infierbântă sau simulează infierbântarea, transmiţându-i femeii o stare de exuberanţă. Este primul şoc de satisfacţie al femeii care se simte dorită de alt bărbat decât al ei. Respinsă de soţul său, care nu face din ea o confidentă, Ana se lasă atrasă de celălalt, care ia locul protectorului. Sămădăul are inteligenţa de a pricepe că, pentru a o câştiga, trebuie să joace un rol aproape patern. El se arată duios faţă de copii, mimează cu o discreţie subtilă figura pasionatului, care se abţine de la avansuri pentru a nu o speria. Femeia sesizează nuanţa şi crede în sinceritatea gesturilor (în fond, false). "+
                "  Lică o invaţă pe Ana viciul, atunci când dansează cu Uţa, prefăcându-se a se abține de la un dans la fel de scandalos şi cu soţia lui Ghiţă, iar acest sacrificiu măguleşte femeia. Ana, aşezată în concurenţă cu o altă femeie, îndârjită să arate ce poate, învață să glumească deocheat. Ea confundă depravarea cu joaca, iubirea pentru altul cu grijă față de soțul ei și rămîne la cârciumăca să se răzbune pe indiferență acestuia din urmă."+
                "  În opinia mea, modul în care tema textului narativ se reflectă în evoluţia relaţiei dintre cele două personaje se bazează pe faptul că decăderea Anei este o nebunie a neînţelegerii, a inocenţei care nu ştie să identifice răul şi, necunoscându-i puterea, şi-l însuşeşte cu o convingere, neîntâlnită la un vicios adevărat. Uciderea ei de către Ghiţă reprezintă finalizarea unui destin care, prin eroare şi confuzie, şi-a pierdut esenţa. "+
                "  În concluzie, opera scriitorului ardelean evidenţiază o lume complexă, căreia normele etice dau sensul. De altfel, scriitorul afirma: „în gândul meu, rostul scrierii a fost întotdeauna spre o vieţuire potrivită cu firea omenească.\" („Lumea prin care am trecut\").  "
                ;

        stringBuilder.append(finallyEseu);
        e9.setText(stringBuilder.toString());
    }
}
