package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class morometiiCaract extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_morometii_caract);

        TextView caractMorometii = (TextView) findViewById(R.id.caractMorometii);
        TextView e26 = (TextView) findViewById(R.id.e26);

        caractMorometii.setText("Caracterizarea lui Ilie Moromete");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  Ilie Moromete este un personaj exponential, arhetip al ţăranului, al cărui destin exprimă moartea unei lumi: „cel din urmă ţăran\" (după cum a fost numit de Nicolae Manolescu) .El reprezintă concepția tradiţională, ţărănească, față de pământ şi faţă de familie; criza satului arhaic reflectă în conştiinţa unui personaj confruntat, tragic, cu legile implacabile ale istoriei, cu timpul nerăbdător. \n"+
                "  Aflat între tinereţe şi bătrâneţe, când „numai nenorociri sau bucurii mari mai pot schimba viata cuiva\", Ilie Moromete este preocupat de conservarea propriului echilibru lăuntric, fiind mulţumit de condiţia sa economică. "+
                "  Originalitatea tipului de țăran creat de Marin Preda este realizată pornind de la atitudinea faţă de pământ spre deosebire de țăranul lui Liviu Rebreanu, dornic de a dobândi pământul, care înseamnă demnitate socială şi umană. Moromete trebuie doar să-l păstreze; pământul reprezintă; pentru Moromete, garanţia unităţii familiei şi şansa de a se manifesta contemplativ sau senin, cu acele bucurii ale spiritului (de exemplu, politica) în care s-a refugiat, din dorinţa unei relații superioare cu lumea. El este particularizat printre ceilalţi ţărani, prin trăsăturile care îi aduc prestigiul în sat: bucuria contemplaţiei, plăcerea de a vorbi, darul povestirii, sociabilitatea, inteligenţa, fantezia, umorul, ironia. El are capacitatea de a-şi dismula gândurile şi sentimentele, de aceea ceilalţi consideră că are un comportament care determină înstrăinarea de familie."+
                "  Cele două ipostaze diferite, înfăţişate în cele două volume, sunt motivate de confruntarea personajului cu timpul. Moromete este portretizat în mişcare, prin acumularea detaliilor sugestive. Obiectivitatea observaţiei (vorbirea, gestica şi mimica, comportamentul) este dublată de fineţea analizei interioare, de prezentarea jocului gândurilor lui Moromete. "+
                "  Ilie Moromete este un personaj dominant, simbolic. „Filosof\", „naiv\", „actor\", „inocent\", „disimulant\" sunt câteva epitete care se asociază în mod curent cu acest personaj. Actor, Moromete îşi exprimă uimirea, nedumerirea sau supărarea, calculând efectul fiecărui cuvânt, modelându-şi intensitatea vocii, căutând clipa potrivită pentru a-şi lansa replica. Moromete are şi o mare capacitate de disimulare, ilustrative fiind secvențele în care hotărăşte vânzarea salcâmului sau în care îl înfruntă pe agentul fiscal. Astfel, reacţiile sale sunt, uneori, imprevizibile: „Paraschiv nu-i răspunse; nici nu se vedea unde este Moromete rămase câteva clipe cu spatele întors spre cei doi de pe prispă, apoi deodată se răsuci pe călcâie şi strigă: «N-am!»\". Ilie Moromete este un stăpân neînduplecat, vocea lui (caracterizare indirectă) răsună într-o variată tonalitate, la fineţea ironică la sarcasmul ucigător. „- Unde vii, mă, cu ei, Nilă? îl întrebă batjocoritor. / -Cum unde viu? răspunse Nilă nedumerit./ - Adică da! exclamă Moromete. Treci cu ei încoa, să cadă salcâmul pe ei.\" "+
                "  Scena ploii, când Moromete este udat până la piele de „o ploaie repede şi caldă\", este revelatoare. Monologul său interior arată efortul permanent al lui Moromete de a înţelege lumea, schimbările satului. O întragă filosofie de viață se cuprinde în gândurile rostite de Moromete; părăsit de fiii cei mari,  se consolează cu faptul că şi-a făcut datoria de părinte: „Tot am făcut ceva, am crescut şase copii şi le-am ţinut pământul până în momentul de față, deşi ei au fugit ca nişte trădători şi n-au vrut să-l muncească\". "+
                "  Caracterizarea directă, particularitate a naratorului obiectiv, surprinde drama pierderii salcâmului, adevărat axis mundi. Lucrurile, oamenii par a nu-şi mai găsi rostul: „Grădina, caii, Moromete însuşi arătau bicisnici\"."+
                "  Nimic nu se intâmplă în gospodărie fără încuviințarea lui prealabilă. Idealul de viaţă moromeţian este condiționat de aceeaşi conştiintă patriarhală. Nu îi este suficient să trăiască, ci vrea să fie respectat şi chezăşia respectului o asigură statutul social. De aceea,  Moromete doreşte păstrarea integrităţii pământului. El nu este un spirit activ, ci un contemplativ căruia îi place să-şi analizeze faptele în singurătate: „Cineva îl întrebase odată în glumă de ce vorbeşte singur și Moromete îi răspunse serios că asta e din pricină că n-are cu cine discuta\". Ca urmare, deşi evită inițial angajarea, structura sa caracterială va fi angrenată într-o serie de conflicte ce impun, inevitabil, implicarea. De aici, cheia dramei lui Moromete, care intră în conflict cu propria familie, cu satul şi cu istoria.  "+
                "  Evocarea drumului la munte (caracterizare indirectă) relevă în personaj o neobişnuită mobilitate intelectuală, iar scena în care mocanca îl înfruntă, mari disponibilităţi afective. De altfel, toţi, mai cu seamă, Ţugurlan, observă că. Moromete avea darul ciudat de a descoperi laturile ascunse ale lucrurilor: „Ţugurlan se pomeni gândind fără, voia lui că niciodată până acum, nu se oprise atât de stăruitor asupra cuiva... Ce-i căşunase acum pe Moromete?.. Dar ceva cu neputinţă de explicat îi aduse la ureche, glasul acestuia, parcă aievea, cum stătea acolo la fierărie şi citea ziarul... Ce ciudat citea!\"  (caracterizare directă). Cu excepţia lui Niculae, toţi îl acuză că. „stă toată ziua\", „eşti mort după şedere şi după tutun\" (caracterizare directă). Într-adevăr, pentru Moromete, lumea e un spectacol, personjul are plăcerea vorbelor, a povestirii, plăcerea de a se distra pe seama prostiei celorlalți. "+
                "  La începutul celui de-al doilea volum, comportamentul său stă sub obsesia unei vinovății asumate. Tatăl are încredinţarea că este singurul răspunzător, prin felul său de a fi, de fuga copiilor. Tot ceea ce întreprinde până la întâlnirea cu fugarii, la Bucureşti, face având convingerea că ispăşeşte vina anterioară. Refuzul copiilor de a-l urma, definitiva înstrăinare a Catrinei, însingurarea lui Niculae determină nuanțe ale amărăciunii, totul culminând cu mâhnirea trăită de prăbuşirea clasei sale sociale. "+
                "  Lui Moromete place viața ca un miracol contemplat. Natura înconjurătoare oferă cadrul propice stării reflexive a acestuia, care analizează condiția țăranului în lume sau viața în general, fie în fundul grădinii, fie pe lotul lui de pamânt. Plăcerea vorbei este o pasiune pentru ţăranul mucalit, care profită de orice întâlnire cu câte cineva pentru a sta la taclale, deşi singurul cu care putea vorbi cu adevărat era prietenul său, Cocoşilă, cu care pierdea ceasuri întregi de dulce lenevie, spre supărarea Catrinei, care-l caracterizează direct: „Eşti mort după şedere şi tutun lovi-o-ar moartea de vorbă de care nu te mai saturi!\". "+
                "  Tehnica amânării este un alt concept al filosofiei de viaţă a lui Moromete, el încercând să tărăgăneze orice decizie sau atitudine care nu-i convenea. Scena cu Jupuitu este magistral construită de prozator, atmosfera, tensiunea, iritarea celorlalți fiind înadins provocate de Moromete pentru a se răzbuna pe cei care nu înţelegeau greutățile bietului ţăran, spunându-le poruncitor, ferm agenților, surprinşi de atitudinea acestuia: „N-am!\"."+
                "  Sociabilitatea, inteligenţa, umorul, bucuria contemplaţiei, arta disimulării fac din el un țăran neobişnuit, un observator şi un moralist. Celor dn jur le apare „ca un om sucit, cu toane, imprevizibil, închis într-o meditatie a sa obscură şi impenetrabilă\" (Ovid Crohmălniceanu). Tocmai această atitudine îl înstrăinează faţă de ceilalţi. Una dintre iluziile lui Moromete este aceea a comunicării. El bănuieşte că oamenii îl înţeleg, cel puţin, nevasta şi copiii, şi nu-şi poate reprima mirarea când aceştia îi interpretează faptele altfel decât crede el. "+
                "  Drama lui Moromete este aceea a contemplativității. Adică, după explicatia scriitorului, „este drama omului care, fără a disprețui activitatea, îşi dă seama că insul care-i numai activ îşi consumă viaţa şi nu înţelege nimic din ea, pentru că devine robul acțiunii\" (Florin Mugur, „Convorbiri cu Marin Preda\"). Muțenia în care alunecă Moromete, în urma experienţei tragice, simbolizează dispariția: „criza îl înstrăinează de fosta lui ipostază, pe care o priveşte cu ochi stăin. Eroul îşi înţelege finalmente drama, ceea ce face din el un om superior\" (Mihai Ungheanu). "+
                "  Acest personaj impune în literatura română stilul moromeţian, ale cărui particularităţi sunt umorul, ironia, disimularea şi interiorizarea. "+
                "  În opinia mea, Moromete îi propune cititorului o lume în care actul contemplației devine o bucurie a spiritului, iar plăcerea de a vorbi oferă vieţii un sens superior. În ciuda timpului care „nu mai avea răbdare\", protagonistul nu abdică de la idealurile sale. "+
                "  În concluzie, superioritea spirituală a lui Moromete se manifestă prin atitudinea sa de personaj contemplativ pentru el, timpul are „nesfârşită răbdare\" cu toate că, după cum afirma Eugen Simion, „ Moromete stă sub un clopot cosmic şi drumurile mari ale istoriei trec prin ograda lui\". ";
        stringBuilder.append(finallyEseu);
        e26.setText(stringBuilder.toString());
    }
}
