package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class morometiiRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_morometii_rel);

        TextView relMorometii = (TextView) findViewById(R.id.relMorometii);
        TextView e27 = (TextView) findViewById(R.id.e27);

        relMorometii.setText("Relația dintre Moromete și Catrina");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  Marin Preda cultivă o literatură inspirată din realităţile contemporane lui, cu intenția de a transmite adevăruri sociale şi psihologice. Temele abordate de acest scriitor, morale sau existențiale, sunt dezvoltate într-o manieră epică, fondată pe observaţia psihologică. "+
                "  Pregătit de nuvelele care prefigurează motive, întâmplări şi personaje din roman, „Moromeții\" este publicat în două volume, elaborate la doisprezece ani distanţă: volumul I, în 1955, volumul al II-lea, în 1967. "+
                "  Relaţiile dintre Moromete şi Catrina sunt evidenţiate de tema familiei, situată în centrul romanului. Acţiunea primului volum este structurată pe mai multe planuri narative, dintre care unele surprind condiţia tatălui autoritar şi a mamei ce încearcă să armonizeze copiii proveniţi din două căsătorii ale lui Ilie Moromete. Conflictul dintre soț şi soţie este schiţat în primul volum şi dezvoltat în cel de-al doilea, când se evocă înstrăinarea Catrinei, care se duce să locuiască „în vale\", la Alboaica, fata ei din prima căsătorie. Construcţia subiectului din primul, dar şi din cel de-al doilea volum, este organizată cronologic, fapt ce conferă echilibrul discursului narativ; Moromete şi Catrina sunt personaje asupra cărora autorul revine pentru a sugera modul în care relaţiile dintre soţi sunt influenţate de relaţiile cu ceilalţi membri ai familiei şi de starea economică."+
                "  Ilie Moromete este un personaj exponenţial, al cărui destin exprimă moartea unei lumi: „cel din urmă țăran\" reprezintă concepţia tradiţională, ţărănească, faţă de pământ şi de familie; criza satului arhaic se reflectă în conştiinţa unui personaj confruntat, tragic, cu legile implacabile ale istoriei, cu timpul nerăbdător. Problema paternităţii (esenţială în roman) contribuie la deghizarea problemei sociale generale. "+
                "  Originalitatea tipului de ţăran creat de M. Preda este realizată pornind de la atitudinea faţă de pământ: spre deosebire de țăranul lui Liviu Rebreanu, dornic de a dobândi pământul, care înseamnă demnitate socială şi umană, Moromete trebuie doar să-l păstreze; pământul reprezintă, pentru Moromete, garanția unității familiei şi şansa de a se manifesta contemplativ sau senin, cu acele bucurii ale spiritului (de exemplu, politica) în care s-a refugiat, din dorinţa unei relaţii pozitive cu lumea. El este particularizat printre ceilalți ţărani, prin trăsăturile care aduc prestigiul în sat: bucuria contemplaţiei, plăcerea de a vorbi, darul povestirii, sociabilitatea, inteligenţa, fantezia, umorul, ironia. El are capacitatea de a-şi disimula gândurile şi sentimentele, de aceea ceilalți consideră că are un comportament bizar. Acest fapt determină înstrăinarea de familie. Cele două ipostaze diferite, înfăţişate în cele două volume, sunt motivate de confruntarea personajului cu timpul. Moromete este portretizat în mişcare, prin acumularea detaliilor. Obiectivitatea observaţiei (vorbirea, gestica şi mimica, prezentarea comportamentului) este dublată de fineţea analizei interioare, de prezentarea jocului gândurilor lui Moromete. "+
                "  Catrina, a doua soţie a lui Ilie Moromete, este mama vitregă a lui Paraschiv, Nilă și Achim şi mama naturală a Ilincăi, a Titei şi a lui Niculae. Multe scene din roman o prezintă copleșită de treburi, împărţindu-şi puterile între muncile câmpului și gospodărie. Acest fapt produce adesea izbucniri mânioase: „Veniţi de la deal şi vă lungiți ca vitele și eu să îndop singură o ceată de haidamaci...\", ce sunt stopate cu umor de Ilie Moromete. Ea este unul dintre puţinele personaje ale cărui coordonate, faţă de primul volum, nu se schimbă, în linii mari. În volumul I, capitolul XXIV, sunt evocate momente semnificative pentru prezentarea relaţiilor dintre Moromete și Catrina. Aceasta se întorsese de la biserică „şi se oprise lângă stănoagă.\". Apostrofat de soţie, pentru absenţa spiritului religios, Ilie Moromete reacţionează ironic, întocmai ca Ştefan a Petrei, personajul „Amintirilor din copilărie\", la adresa Smarandei. Soțul Catrinei este departe de a fi un evlavios şi, imitând limbajul bisericesc, insinuează faptul că numai cei slabi de minte ascultă cuvântul preotului: „...şi dă-ne nouă, Doamne, cât mai multe leturghii şi colive... adu cât mai multe proaste la biserică . Slavă Tatălui şi Fiului şi Sfântului Duh...\". Deşi credincioasă, Catrina „era furioasă că ţinea totuşi la el, aşa păcătos cum era.\""+
                "  O altă scenă semnificativă, sugerând relaţiile dintre Ilie Moromete şi Catrina este, la inceputul volumului al II-lea, aceea în care se evocă faptul că Moromeţii rămaşi la Silistea-Gumeşti primesc o scrisoare şi o fotografie de la „cei trei\" (Paraschiv, Nilă. şi Achim). Mucalit, dar aparent nepăsător, Moromete înţelege că fiii săi nu ajunseseră atât de bine pe cât pretindeau. Ironia ascuțită şi spiritul ludic îl detetermină, totuşi, să-şi păstreze stăpânirea de sine. De altfel, disimularea este o trăsătură definitorie a firil lui. Moromete, prezentă în cele mai multe scene din roman. \n"+
                "  Reacţia Catrinei la aflarea veştilor din scrisoare şi la contemplarea fotografiei atestă statutul ei, de femeie simplă, care se încadrează în anumite tipare de gândire. Catrina poate fi raportată la vreuna dintre aprecierile criticii literare, referitoare la Moromete. Dacă Moromete intuieşte faptul că viața celor trei fii mai mari nu se schimbase prea mult in bine (implicit, filosofia lor de viaţă), Catrina crede, în mod naiv, că „ura lor contra mamei a fraţilor vitregi se stinsese\". "+
                "  Ilie Moromete este un personaj dominant, simbolic. „Filosof\", „naiv\", „actor\", „inocent\", „disimulant\" sunt câteva epitete care se asociază în mod curent cu acest personaj. Actor, Moromete îşi exprimă uimirea, nedumerirea sau supărarea, calculând efectul fiecărui cuvânt, modelându-şi intensitatea vocii, căutând clipa potrivită pentru a-şi lansa replica. Moromete are şi o mare capacitate de disimulare, ilustrative fiind secvenţele în care hotărăşte vânzarea salcâmului, sau în care îl înfruntă pe agentul fiscal: „Paraschiv nu-i răspunse; nici nu se vedea unde este. Moromete rămase câteva clipe cu spatele intors spre cei doi de pe prispă, apoi deodată se răsuci pe călcâie şi strigă: «N-am!»\" Ilie Moromete este un stăpân neinduplecat, vocea lui răsună, într-o variată tonalitate, de la fineţea ironică, la sarcasmul ucigător: „- Unde vii, mă, cu ei, Nilă? îl întrebă batjocoritor. - Cum unde viu? răspunse Nilă, nedumerit.- Adică da! exclamă Moromete. Treci cu ei încoa să cadă salcâmul pe ei.\" Nimic nu se întamplă în gospodărie fără încuviinţarea lui prealabilă. Idealul de viaţă moromeţian este condiționat de aceeaşi conştiinţă patriarhală. Nu îi este suficient să trăiască, ci vrea să fie respectat şi chezăşia respectului o asigură statutul social. De aceea, Moromete doreşte păstrarea integrității pământului. El nu este un spirit activ, ci un contemplativ căruia ii place să-şi analizeze faptele în singurătate: „Cineva întrebase odată în glumă de ce vorbeşte singur şi Moromete îi răspunse serios că asta e din pricină că n-are cu cine discuta\". "+
                "  Ca urmare, deşi evită inițial angajarea, structura sa caracterială va fi angrenată într-o serie de conflicte ce impun, inevitabil, implicarea. De aici, cheia dramei lui Moromete, care intră în conflict cu propria familie, cu satul şi cu istoria. "+
                "  Relatarea drumului la munte relevă în personaj o neobişnuită mobilitate intelectuală, iar scena în care mocanca îl înfruntă, mari disponibilităţi afective. De altfel, toţi, mai cu seamă, Țugurlan, observă că Moromete avea darul ciudat de a descoperi laturile ascunse ale lucrurilor: „Țugurlan se pomeni gândind fără voia lui ca niciodată până acum nu se oprise atât de stăruitor asupra cuiva... Ce-i căpşunase acum pe Moromete?... Dar ceva cu neputință de explicat îi aduse la ureche glasul acestuia, parcă aievea, cum stătea acolo la fierărie şi citea ziarul... Ce ciudat citea!\". Cu excepţia lui Niculae, toţi îl acuză „că stă toată ziua\", „eşti mort după şedere şi tutun\". Într-adevăr, pentru Moromete, lumea e un spectacol, personajul are plăcerea vorbelor, a povestirii, plăcerea de a se distra pe seama prostiei celorlalţi. \n"+
                "  La începutul celui de-al doilea volum, comportamentul său stă sub obsesia unei vinovăţii asumate. Tatăl are încredințarea că este singurul răspunzator, prin felul său de a fi, de fuga copiilor. Tot ceea ce întreprinde până la întâlnirea cu fugarii, la Bucureşti, face din convingerea că ispăşeşte vina anterioară. Refuzul copiilor de a-l urma, definitiva instrăinare a Catrinei, însingurarea lui Niculae determină nuanţe ale amărăciunii, totul culminând cu mâhnirea trăită la prăbuşirea clasei sale sociale. \n"+
                "  Celor din jur le apare „ca un om sucit, cu toane, imprevizibil, închis într-o meditație a sa, obscură şi impenetrabilă..\". (Ovid Crohmălniceanu) Tocmai această atitudine îl instrăinează față de ceilalti. Una dintre iluziile lui Moromete este aceea a comunicării. El bănuieşte că oamenii îl înteleg, cel puţin, nevasta şi copiii, şi nu-şi poate reprima mirarea când aceştia îi interpretează faptele altfel decât crede el. "+
                "  Drama lui Moromete este una a contemplativităţii, adică, după explicaţia scriitorului, „este drama omului care, fără a dispreţui activitatea, îşi dă seama că insul care-i numai activ îşi consumă viaţa şi nu înţelege nimic din ea, pentru că devine robul acțiunii\" (Florin Mugur, Convorbiri cu Marin Preda). Muţenia în care alunecă, Moromete, în urma experienţei tragice, simbolizează dispariţia: „Criza îl înstrăinează de fosta lui ipostază, pe care o priveşte cu ochi străin. Eroul îşi înţelege finalmente drama, ceea ce face din el un personaj superior\" (Mihai Ungheanu). \n"+
                "  Relaţiile lui Ilie Moromete cu Catrina conturează unul dintre conflictele romanului. Între Moromete şi Catrina, soţia sa, există un conflict surd, evocat pe parcursul celor două volume. Aceasta primise, la reforma agrară, un lot. La puţină vreme, din cauza foametei, Moromete vânduse un pogon din lotul soţiei, promiţându-i, în schimb, că va trece casa şi pe numele ei, dar nu se ţinuse de cuvânt. Acum, când fetele se făcuseră mari şi erau de măritat, Catrina pretindea insistent pogonul vândut. Cu timpul, atitudinea lui Achim şi Paraschiv o face să înţeleagă că avusese dreptate să se teamă că va fi dată afară din casă. Deşi Catrina îi crescuse pe cei trei, rudele, mai ales Guica, îi invăţase „că mama vitregă eravinovată.\" că se trăia greu la ei şi că, dacă n-or s-o dea afară din casă o să pună mâna pe averea tatălui.\" \n"+
                "  Înspăimântată, Catrina găseşte alinare în biserică În vohunul al doilea, se ilustrează modul în care Catrina sincepe să se indepărte tot mai mult de căsă, stăpânită de o ură amenintătoare. Paraschiv, Nilă şi Achim nu au de gând să se întoarcă de la Bucureşti, Ilinca şi Tita sunt nemulţumite, iar Catinca continuă să-l ameninţe pe Moromete că va pleca de acasă. Pleacă împreună cu fetele la Alboaica (fiica din prima căsătorie), dar Ilinca o convinge să revină acasă. La întoarce Moromete se scoală din pat, hotărât s-o bată. Catrina pleacă iar, pretinzându-i Ilincăi s-o urmeze şi o amenintă că, in caz contrar, nu-i va mai da loturile de pământ cuvenite. Moromete, la insistentele lui Niculae, se hotărăşte să treacă \" jumătate din locul casă\", dar nu pe numele Catrinei, ci pe numele Ilincăi. Catrina află că Moromete trecu pe numele Ilincăi trei pogoane şi vine s-o ameninte. Tita, căreia Moromete nu-i lăsa nimic, este şi ea supărată şi pretinde ca mama ei să se intoarcă acasă şi să-i dea ce i cuvine. Catrina intelege că Moromete a câştigat contra ei şi că fetele, pe care ea se bi zuise, o părăseau. Moromete slăbeşte din zi în zi, dar, cu toate acestea, n-are răbdare să stea acasă deşi nu-l mai ţin picioarele. "+
                "  Într-o zi, pleacă de acasă la Alboaica şi, certat de Catrina are încă puterea s-o lovească. Pe patul de moarte, Ilie Moromete îşi concentrează întreaga filosofie de viață cele câteva cuvinte adresate cu satisfacţie doctorului: „Domnule [...], eu totdeauna am dus o viată independentă.\". Acest fapt dovedeşte, încă o dată, că, prin „Moromeții\", autorul ilustrează convingerea, potrivit căreia țărănimea nu este stăpânită doar de instinct, ci dimpotrivă, este capabilă de reacţii sufleteşti nebănuite\" (Al. Piru). \n"+
                "  În opinia mea, modul în care tema textului narativ se reflectă în evoluţia relației : dintre cele două personaje se bazează pe caracterul simbolic al acestora. Personaj exponențial, prototip al țăranului patriarhal, Moromete ilustrează concepția tradițională față de pământ şi de familie. Faptul că ura Catrinei se transformă într-o înstrăinare definitivă accentuează tragismul personajului. \n"+
                "  În concluzie, romanul conţine elemente caracteristice romanului tradiţional, îmbinate cu cele moderne."
                ;
        stringBuilder.append(finallyEseu);
        e27.setText(stringBuilder.toString());
    }
}
