package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class morometiiTema extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_morometii_tema);

        TextView eseuMorometii = (TextView) findViewById(R.id.eseuMorometii);
        TextView e25 = (TextView) findViewById(R.id.e25);

        eseuMorometii.setText("Moromeții, de Marin Preda");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  Pregătit de nuvelele care prefigurează motive, întâmplări şi personaje din roman, „Moromeții\" este publicat în două volume, elaborate la doisprezece ani distanță: volumul I, în 1955, volumul al II-lea, în 1967. Romanul prezintă simbolica destrămare a unei familii de ţărani din Câmpia Dunării, în anii din preajma celui de-al Doilea Război Mondial. Deși diferă modalitatea artistică şi problematica celor două volume, romanul este unitar, deoarece principalele personaje sunt urmărite până la finalul deceniului al IV-lea si reconstituie imaginea satului românesc într-o perioadă de criză, înregistrând transformări ale mentalităţilor şi ale institutițiilor."+
                "  Specie a epicii culte, de mare întindere, cu o acţiune polifonică, în care sunt prezente numeroase personaje, acest roman realist ilustrează un narator obiectiv, omniscient şi omniprezent. Naraţiunea de tip obiectiv permite şi intervenţia reflectorilor (Ilie Moromete, în volumul I şi Niculae, în volumul al II-lea), dar şi aceea a informatorilor (personaje-martori ai evenimentelor, precum Parizianu, care va relata, ullterior, despre vizita lui Moromete la Bucureşti). \n"+
                "  Există o relaţie între tehnica de compoziţie şi tema timpului: în volumul I, asistăm la tehnica decupajului, naraţiunea fiind lentă, de la aparenţa timpului care „avea cu oamenii nesfârşită răbdare; viața se scurgea aici fără conflicte mari\" (incipit), la „Timpul nu mai avea răbdare\" (final); în volumul al II-lea, tehnica este cea rezumativă, a selecţionării evenimentelor, cu întoarceri în timp (acronie) și eliminări de fapte - oamenii se confruntă cu „viclenia timpului\".  \n"+
                "  Titlul, alcătuit dintr-un substantiv propriu, are o funcţie anticipativă, orientând lectorul spre evocarea vieţii unei familii. \n"+
                "  Primul volum prezintă familia şi gospodăria, viața unui sat din Câmpia Dunării, Siliştea-Gumeşti, în vara anului 1937, în preajma celui de-al Doilea Război Mondial, tema fiind reprezentată de povestea unei familii de țărani. Volumul este alcătuit din trei părți: acţiunea din prima parte se petrece de sâmbătă seara până duminică, noaptea, cu scene ilustrând monografic viaţa rurală: cina, tăierea salcâmului, întâlnirea duminicală din poiana fierăriei lui Iocan, hora; partea a II-a se derulează pe parcursul a două săptămâni,  începând cu plecarea lui Achim cu oile, la Bucureşti; ultima parte, de la seceriş până la sfârşitul verii, se încheie cu fuga feciorilor. "+
                "  În volumul al doilea, alcătuit din cinci părţi, prin tehnica rezumativă, se prezintă viaţa rurală, de la reforma agrară din 1945, cu prefacerile aduse în transformarea „socialistă\" a agriculturii după 1949, până la finalul deceniului al VI-lea. Vechea imagine a lui Ilie Moromete este distrusă, fiind înlocuită cu o alta, lipsită de glorie. Autoritatea lui în sat se diminuează, iar unitatea familiei nu se reface. Satul intră într-un proces de disoluție în locul vechilor mentalități fiind aşezate altele noi, derulându-se o istorie tulbure. "+
                "  Volumul I este cartea tatălui, personaj-reflector şi purtător al unei mentalități traditionale, iar volumul al II-lea este cartea „un antimoromețian ca filosofie a existenţei\" (Nicolae Manolescu). „În <<Moromeţii>>; interesantă e problema lui Niculae, căci conflictul dintre Moromete simbolizează conflictul dintre două concepţii de viață ale țăranului. Tocmai din această cauză, Moromete şi Niculae devin reflectori: motivațiile lor lăuntrice interesează nu numai ca expresie a adaptării sau dezadaptării spontane la o lume, ci şi ca filosofie de existență\" (Nicolae Manolescu, „Arca lui Noe\") ."+
                "  Acțiunea primului-volum este plasată la câtiva ani înaintea celui de-al Doilea Război Mondial, în 1937, de la începutul verii până spre sfârşitul aceluiaşi anotimp, volumul fiind alcătuit din trei părţi.\n"+
                "  În planul romanului, reperele temporale sunt bine determinate: acţiunea din prima parte începe într-o sâmbătă seara, continuă noaptea spre duminică, pănă după-amiaza. Umanitatea comunei Siliştea-Gumeşti este pusă în mişcare pe laturile ei fundamentale: dragostea dintre Polina şi Birică, foamea de avere a lui Tudor Bălosu şi a fiului său, Victor, răzvrătirea lui Ţugurlan, spiritul distructiv întruchipat de Guica. Duminica dimineaţa predomină manifestările colective: participarea tineretului la pregătirea militară, adunarea din poiana fierăriei lui Iocan, modul în care decurg relațiile sătenilor cu agentul fiscal, spectacolul căluşului. Această parte se încheie prin fuga,Polinei cu Birică. "+
                "  A doua mare secvență epică surpinde satul în febra secerişului și, în afara acestui moment principal, mai surprinde şi altele secundare: plecarea lui Achim la Bucureşti, tentativa de fugă a lui Nilă şi Paraschiv , conflictul Polinei cu tatăl şi fratele său, episodul premierii lui Niculae, împrumutul pe care-l face Moromete de la Aristide. "+
                "  Ultima secvenţă înfăţişează conflictul direct dintre Ilie Moromete şi fiii săi. Toate secvenţele epice sunt cimentate, în interior, de ideea ireversibilitătii temporale. Dacă, iniţial, timpul părea a avea răbdare, în partea a doua, timpul se precipită: prețul grâului scade vertiginos, impozitele nu mai pot fi amânate, Aristide pretinde restituirea imediată a împrumutului, Niculae trebuie înscris la şcoală, iar negustorul de găini Scămosu îi mărturiseşte lui Ilie Moromete că cei doi feciori vor să fugă, de acasă. "+
                "  Conflictul romanului este triplu. Mai intâi, există dezacordul ditre tată şi fiii din prima căsătorie, care se naște dintr-un mod diferit de a vedea lumea. Ilie Moromete nu prevăzuse niciodată latura comercială a produselor pământului. Pentru el, ca şi pentru Ion, personajul lui Liviu Rebreanu, pământul semnifică o condiție etică, a individului, asigurându-i independenţa în mijlocul lumii."+
                "  Atitudinea aceasta este motivată de o retrospectivă biografică. Înainte de răscoala din 1907, când se ducea la moşia boierului Guma, tatăl lui Ilie Moromete se făcea de nerecunoscut: „îşi lua căciula de pe cap şi avea un glas care, şi acum, când îşi amintea de el, Moromete se întuneca şi se făcea crunt la faţă.\" În 1920, după reforma agrară, Moromete trăieşte bucuria de a fi proprietar şi dorința lui e să-şi păstreze lotul întreg: „De ani de zile mă zbat să nu vând din el să plătesc fonciirea fără să vând, să vă rămâie vouă întreg, orbilor şi sălbaticilor la minte [...]:Pământul rămas întreg,Paraschive, smintitule, acolo e munca voastră! Bolnavule după avere\". "+
                "  Ceea ce pune în mişcare nemulţumirea fiilor este un obscur sentiment de nelinişte în faţa sorții de țăran. Cei trei acționează în spiritul veacului şi dorinţa lor de a face bani se subordonează tendinței generale de a produce marfă pentru piaţă. Conflictul izvorăşte, deci, din existenţa a două mentalități diferite. Cu multe ocolişuri, prefăcându-se interesaţi de datoriile ce amenințau gospodăria, îi dau de înţeles tatălui că ar fi bine, ca Achim să plece la Bucureşti cu oile, Nilă şi Paraschiv plănuind să fugă mai târziu, luând şi caii. Nu intenţia plecării este greşită, ci forma prin care se realizează, deoarece dorinţa de a-şi schimba viaţa scoate la iveală aspecte negative ale caracterului copiilor. Nilă şovăie, tocmai pentru că intuieşte în Achim şi Paraschiv existenţa unor sentimente imunde. În vorbele fratelui său, descoperă o nejustificată ură împotriva tatălui. De aceea, la propunerea de a fugi înainte de seceriş, Nilă protestează: „Bă, eu v-am mai spus: fugim, dar nu putem să luăm caii din grajd, află lumea şi ne facem de râs.\" "+
                "  Moromete nu sesizează amploarea nemulțumirii copiilor, observă numai latura lor caracterială. Este hotărât să distrugă foamea de avere a acestora şi, de aceea, le încuviințează plecarea cu porumb la munte, deşi ştia că afluxul de cereale va duce la scăderea prețurilor. În concluzie, Achim, Nilă, Paraschiv şi Niculae refuză modul de viață oferit de Moromete şi acesta va rămâne singur. \n"+
                "  Al doilea conflict izbucneşte între Moromete şi Catrina, soția sa. Ultimul conflict familial, mai ascuns, se desfăşoară între Moromete şi sora sa, Maria, poreclită Guica. Ea ar fi vrut ca fratele ei să nu se mai fi căsătorit a doua oară şi să o fi ţinut pe ea în casă, pentru a se ocupa de gospodărie şi de creşterea celor trei copii. Moromete însă îi cumpărase un loc şi-i construise un bordei, departe de curtea lui. Considerându-se nedreptăţită, ea e cuprinsă de ură împotriva fratelui său, aţâţându-i pe cei trei fraţi. "+
                "  Este vizibilă intenția lui Marin Preda de a realiza în „Moromeții\", aşa cum Liviu Rebreanu a creat în „Ion\", o imagine monografică a lumii rurale. Hotărârea lui Moromete de a cere bani cu împrumut primarului Aristide prilejuieşte romancierului, la începutul părţii a doua, descrierea centrului comunei. Este o „hartă\" pe care pot fi localizate instituțiile şi locuinţele notabilităţilor, creând sentimentul realului. Descrierea are rolul de a sugera ierarhia socială a satului, aşa după cum Liviu Rebreanu grupa personajele, în primul capitol al romanului Ion, cu identică intenţie. "+
                "  Personajele romanului sunt angrenate în toate evenimentele timpului, tehnica folosită fiind aceea a colajului, ceea ce conferă modernitate acestei opere literare. Satul românesc din deceniul al IV-lea nu poate fi imaginat fără corvoada „premilităriei, a cărei absurditate o intuieşte confuz Nilă, în timpul exerciţiului de ocupare a gării. Pagini memorabile realizează romancierul prin secvenţele din cancelaria şcolii, evidenţiind conflictul dintre învăţătorul Teodorescu şi directorul şcolii, Toderici. Serbarea şcolară de sfârşit de an polarizează atenţia întregului sat. Episodul ce înfăţişează sosirea lui Vasile Boţoghină la spitalul din Udupu surprinde o zi de consultaţie la medicul de plasă. Justiţia rurală este văzută, din perspectiva şefului de post, în secvenţa întâlnirii cu Țugurlan, acasă, la acesta din urmă. "+
                "  Marin Preda a fost atras şi de spiritualitatea ancestrală a clasei ţărăneşti, jocul căluşului constituind o pagină de epos autentic. Fascinaţia locuitorilor o constituie poiana din faţa fierănei lui Iocan, unde, fiecare duminică dimineaţa au loc dezbaterile ideatice ale satului moromeţian pentru întâia oară. În literatura română de inspiraţie rurală, sătenii renunţă la horă şi la cârciumă pentru un spectacol intelectual. "+
                "  Scriitorul abordează, într-o viziune inedită, problema pământului. Umanitatea imaginată de Liviu Rebreanu în „Ion\" şi „Răscoala\" este dominată de pasiunea pentru pământ. Acesta constituie un element esenţial şi în relaţiile dintre oamenii universului moromeţian, dar şi-a pierdut forţa mistuitoare din romanele lui Rebreanu. Satul moromeţian este unul de ţărani împroprietăriţi prin reforma agrară, de după război, iar excepţiile sunt puține (Ţugurlan). Pământul rămâne modalitatea hotărâtoare de existeriţă şi posesiunea lui decisivă, pământul semnificând independenţa materială pe care se clădeşte prestigiul social. Posibilitatea unei înstrăinări determină reacţii imprevizibile: de la expresia „rece\" care se aşterne pe chipul surorilor lui Birică, până la glasul nemilos al Anghelinei Boţoghină. Substantivul „pământ\" este repetat şi în familia lui Moromete şi este cauza dezbinării dintre soți. "+
                "  Cu toate acestea, o detaşare definitivă de vraja pământului acţionează permanent. Din pIanurile de viitor ale lui Paraschiv, Nilă şi Achim, pământul este exclus. Mai presus de pământ, Vasile Boţoghină pune propria viaţă, iar Niculae, studiul. Renunţarea la pământ pentru un motiv concret sau o pasiune de natură intelectuală reprezintă noutatea esențială adusă de Marin Preda în perioada postbelică.  "+
                "  Viziunea inedită despre existenţă este evidenţiată şi cu ajutorul unor secvenţe epice, având o puternică încărcătură simbolică: scena cinei, a secerişului, a tăierii salcâmului, convorbirea sătenilor din poiana fierăriei lui Iocan. Acestea impun o viziune realistă despre existenţă, un weltanschaung (concepţie despre lume) care ilustrează tehnicile specifice acestui tip de proză: mimetism, veridicitate, verosimilitate. "+
                "  Scena tăierii salcâmului surprinde drama pierderii acestui arbore, adevăra axis mundi: „Grădina, caii, Moremete însuşi arătau bicisnici\" şi, în mod simbolic, este anticipată dispariţia lui Ilie Moromete, dar şi a clasei sociale pe care acesta o reprezenta. Moromete taie salcâmul pentru a achita o parte din datoriile familiei, fără a vinde pământ sau oi. Cu toate acestea, „nimeni nu înţelegea că hotărându-se, în sfârşit, plecarea lui Achim a București, însemna că trebuie să li se facă celor trei pe plac până la capăt, să nu se mai atingă nimeni de oi şi cum altceva n-aveau ce vinde, salcâmul trebuia tăiat\". "+
                "  Pe patul de moarte, Ilie Moromete concentrează întreaga filosofie de viaţă în cele câteva cuvinte adresate cu satisfacție doctorului: ,Domnule [...], eu totdeauna am dus o viaţă independentă. Acest fapt dovedeşte, o dată mai mult, că, prin „Moromeții\", autorul ilustrează convingerea, potrivit căreia țărănimea nu este stăpânită doar de instinct, ci, dimpotrivă este capabilă de „reacții sufleteşti nebănuite\"(Al. Piru). "+
                "  În opinia mea, complexitatea romanului constă în faptul că alternează proza de creaţie cu proza de analiză psihologică. Personajele au independenţă de mişcare şi de exprimare, iar protagonistul impune un modus vivendi, numit de critică literară „moromețianism\", caracterizat prin capacitatea de disimulare, ironie şi plăcerea conversaţiei."+
                "  În concluzie, tema fundamentală a operei este aceea a relaţiei dintre personaj şi istorie. „Moromeții\" este un demers literar ce evocă soarta lumii ţărăneşti în confruntarea brutală, cu istoria. ";
        stringBuilder.append(finallyEseu);
        e25.setText(stringBuilder.toString());
    }
}
