package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class ultimaTema extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ultima_tema);

        TextView eseuUltima = (TextView) findViewById(R.id.eseuUltima);
        TextView e16 = (TextView) findViewById(R.id.e16);

        eseuUltima.setText("Ultima noapte de dragoste, întâia noapte de război, de Camil Petrescu ");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  Scriitor care a trăit în orizontul cunoașterii, pâtruns de gustul amar al filosofiei, Camil Petrescu exemplifică, prin bogata sa experiență spirituală, natura artistului lucid. Teoretician al noului roman („Noua structură și opera lui Marcel Proust\"), Camil Petrescu susține perspectiva proustiană asupra literaturii ce exprimă autenticitatea trăirilor. Acesta  afirmă: „Să nu descriu decât ceea ce văd, ceea ce aud, ceea ce înregistrează simțurile mele. Din mine însumi nu pot ieși\". Romanul „Ultima noapte de dragoste, întâia noapte de război\" suprinde, din punct de vedere tematic, drama intelectualului lucid, dornic de cunoaștere, de experiențe absolute. Este un roman de analiză psihologică, întreprinsă în raport cu doi factori capabili să shimbe cursul vieții: iubirea și războiul.\n"+
                "  Apărut în 1930, după ce fusese anunţat sub mai multe titluri, romanul urmărește trei ani (1914-1917) din experienţa lui Ștefan Gheorghidiu. În roman sunt dezbătute, respinse sau anticipate idei din filosofia lui Kant, Hegel, Bergson, Husserl, din creaţia şi estetica lui Proust. „Ultima noapte de dragoste, întâia noapte de război\" este un roman modern, de tip subiectiv, având drept particularităţi: unitatea perspectivei narative, redactarea la timpul prezent, memoria involuntară, luciditatea autoanalizei. De asemenea, scriitorul pune în discuţie anticalofilismul, apreciind că „stilul frumos este opus artei\". "+
                "  Romanul este scris la persoana I, sub forma unei confesiuni a personajului principal, Ștefan Gheorghidiu. Naratorul este protagonistul romanului, perspectiva narativă fiind subiectivă şi unică. (trăsătură a romanului modern, de tip subiectiv). Naratorul omniscient, obiectiv şi naraţiunea la persoana a III-a (specifice romanului tradiţional, obiectiv) sunt înlocuite, în romanul modern de tip subiectiv, prin naraţiunea la persoana I, cu focalizare exclusiv internă/viziunea împreună cu. \n"+
                "  Naraţiunea la persoana I presupune existenţa unui narator implicat. Punctul de vedere unic şi subiectiv, al personajului-narator, face ca cititorul să cunoască despre personaje tot atât cât ştie şi personajul principal. Situarea eului narativ în centrul povestirii conferă autenticitate, iar faptele și personajele sunt prezentate ca evenimente interioare, interpretate, analizate. \n"+
                "  Prin monolog interior, Ștefan Gheorghidiu analizează, alternând sau interferând, aspecte ale planului interior (trăiri, sentimente, refiectii) şi ale planului exterior (fapte, tipuri umane, relaţii cu alţii).\n"+
                "  Textul narativ este structurat în două părţi, precizate în titlu, care indică temele romanului, în acelaşi timp, cele două experienţe fundamentale de cunoaştere trăite de protagonist: dragostea şi războiul. Dacă prima parte reprezintă rememorarea iubirii matrimoniale eşuate (dintre Ștefan şi Ela), partea a doua, construită sub forma jurnalului de campanie al lui Gheorghidiu, urmăreşte experiența de pe front, în timpul Primului Război Mondial. Prima parte este în întregime fictională, în timp ce a doua valorifică jurnalul de campanie al autorului, articole şi documente de epocă, ceea ce conferă autenticitate romanului."+
                "  Stilul anticalofil pentru care optează romancierul sustine autenticitatea limbajului. Scriitorul nu refuză corectitudinea limbii, ci efectul de artificialitate, ruptura de limbajul cotidian pe care o provoca emfaza din limbajul personajelor în romanul tradiţional. De aceea banalizează, de pildă, obiectul, dar şi limbajul în care se poartă discuţia de la popotă. Personajul-narator comentează astfel conversaţia ofiţerilor: „Platitudini, poncife din cărţi şi formule curente...\". Aceasta nu este doar o critică la adresa pretenţiei de cultură a ofiţerilor, ci mai ales a unui „mod neautentic de a vorbi\" (Nicolae Manolescu-„Arca lui Noe\"), teatralizat, mimetic, fals. „Ultima noapte de dragoste, întâia noapte de război\" este, prin urmare, un roman modern de tip subiectiv, având drept caracteristici: unicitatea perspectivei narative, timpul prezent şi subiectiv, memoria afectivă, naraţiunea la persoana I şi autenticitatea trăirii. Cele două părți nu trebuie privite separat, aşa cum au fost tentaţi să o facă G. Călinescu sau Eugen Lovinescu, ci într-o unitate bazată pe structura interioară a protagonistului. Un factor unificator îl constituie memoria involuntară, cea care permite structurarea operei fără respectarea cronologiei faptelor (acronie). În acest sens, romanul debutează printr-un artificiu compoziţional: acţiunea primului capitol, „La Piatra Craiului în munte\", este posterioară întâmplărilor relatate în restul Cărţii I. Capitolul pune în evidenţă cele două planuri temporale din discursul narativ: timpul narării (prezentul frontului) şi timpul narat (trecutul poveştii de iubire). Reperele spaţiale şi temporale evidenţiază cadrul în care se desfăşoară evenimentele. "+
                "  În primăvara lui 1916, în timpul unei concentrări pe Valea Prahovei, Gheorghidiu asistă, la popota ofiţerilor, la o discuţie despre dragoste şi fidelitate, pornind de la un fapt divers aflat din presă: un bărbat care şi-a ucis soţia infidelă a fost achitat de tribunal. Această discuţie declanşează memoria afectivă a protagonistului, trezindu-i amintirile legate de cei doi ani şi jumătate de căsnicie cu Ela. Fiecare opinie este corelată cu trăsături ale susţinătorului acestei opinii, demonstrând o latură a artei de portretist a lui Camil Petrescu. De exemplu, căpitanul Dimiu, ardelean conformist, are rosturi gospodăreşti şi împărtăşeşte opinia juraţilor: „Nevasta trebuie să fie nevastă şi casa, casă\". Căpitanul Corabu, un tânăr format la şcoala germană şi considerat „spaima regimentului\", este adeptul exprimării libere a sufletului omenesc, în afara oricăror oprelişti impuse de reguli şi convenţii sociale: „Cu ce drept să ucizi o femeie care nu te mai iubeşte? N-ai decât să te desparţi\". Pentru căpitanul Floroiu, „dreptul la dragoste e sfânt... unei femei trebuie să-i fie îngăduit să-şi caute fericirea\". Spre deosebire de aceste opinii, pornite din exterior sau bazate doar pe argumente raţionale, intervenţia lui Ştefan Gheorghidiu reflectă o convingere bazată pe o experienţă sentimentală dură, Gheorghidiu îşi simte rana sufletului nevindecată, atinsă de conversaţia puerilă şi simplificatoare a camarazilor săi pe care-i combate cu tenacitatea caracteristică celui care a suferit îndelung: „...o iubire mare e mai curând un proces de autosugestie... Trebuie timp și trebuie complicitate pentru formarea ei... Orice iubire e ca un monoideism, voluntar la început, patologic pe urmă\"."+
                "  Tehnica memoriei involuntare creează o unitate de ansamblu a operei: un eveniment exterior (discuția de la popotă) declanşează rememorarea unor întâmplări sau  stări. În vreme ce la Marcel Proust, personajul-narator retrăieşte trecutul, la Camil Petrescu se observă analiza trecutului, fapt care generează sfârşitul iluziilor. Într-un moment al dezechilibrului sufletesc, personajul-narator, prin intermediul memoriei involuntare, îşi rememoreză iubirea. Cel de-al doilea capitol, „Diagonalele unui testament\", debutează abrupt, prin ilustrarea stării de incertitudine a protagonistului: „Eram însurat de doi ani și jumătate cu o colegă de la Universitate si bănuiam că mă înşală\". Acum începe să se deruleze retrospectiva iubirii dintre protagonist şi Ela. Ștefan Gheorghidiu, student la Filosofie, este un intelectual superior, cu o mare acuitate analitică, astfel că subiectul romanului se organizează în jurul dramei sale de conştiinţă. Tânărul se căsătoreste din dragoste cu Ela, orfană crescută de o mătuşă. Ea este studentă la litere şi Ștefan mărturiseste: „...deşi nu-mi plăcea, începusem totuşi să fiu măgulit de admiraţia pe care o avea mai toată lumea pentru mine, fiindcă, eram atât de pătimaş iubit de una dintre cele mai frumoase studente şi cred că acest orgoliu a constituit baza viitoarei mele iubiri\". După, căsătorie, cei doi soţi trăiesc modest, dar sunt fericiţi. "+
                "  Echilibrul tinerei familii este tulburat de o moştenire pe care Gheorghidiu o primeşte la moartea unchiului său avar, Tache. Ela se implică in discuţiile despre bani, lucru care lui Gheorghidiu îi displace profund: „Aş fi vrut-o mereu feminină,, deasupra acestor discuţii vulgare\". Mai fi mult, spre deosebire de soţul său, Ela este atrasă de viaţa mondenă, la care noul statut al familiei îi oferă acces. Cuplul evoluează spre o inevitabilă criză matrimonială, al cărei moment culminant inteivine cu prilejul excursiei de la Odobeşti, de sărbătoarea Sfinților Constantin şi Elena. \n"+
                "  În timpul şederii la Odobeşti, se pare că Ela îi acordă o atenție exagerată unui anume G., care, după opinia personajului-narator, va deveni mai târziu amant. După o scurtă despărţire, Ela şi Ștefan se împacă. Înrolat pe frontul românesc, Gheorghidiu cere o permisie, spre a o întâlni pe soţia sa la Câmpulung. Înţelege, dezolat, că este înşelat cu G. A doua experienţă în planul cunoaşterii existențiale o reprezintă războiul, iar „Ab-solutul morţii eclipsează absolutul iubirii\" (D. Micu, „În căutarea autenticității\"). Imaginea războiului este demitizată, în descendentă stendhaliană: „...romanul reflectă, curând, aspectele neglijate şi neglijabile ale războiului: frigul, durerile de stomac, întâmplările comice şi absurde... contează mult pentru romancier, sunt mai autentice, decât planul complet al bătăliei\" (N. Mano escu, „Arca lui Noe\"). Frontul înseamnă haos, mizerie, măsuri absurde, învălmăşeală, dezordine. Se observă diferenţa dintre romanul tradițional de război (Lev Tolstoi, „Război şi pace\") și romanul modern: „renunțarea la ierarhia de semnificație a evenimentelor exterioare sau, în orice caz, reducerea ei drastică, cultivarea, în consecință, a evenimentului comun, banal\"(N. Manolescu, „Arca lui Noe\").\n"+
                "  Capitolul „Ne-a acoperit pământul lui Dumnezeu\" ilustrează absurdul războiului și tragismul confruntărilor cu moartea. Viața combatanților ține de hazard, iar eroismul este înlocuit de spaima de moarte, care păstrează doar instinctul de supravețuire și automatismul: „Nu mai e nimic omenesc în noi\". Individul se pierde, se simte anulat în iureșul colectiv. Drama colectivă a războiului pune în umbră drama individuală a iubirii.\n"+
                "  Rănit şi spitalizat, Gheorghidiu se întoarce acasă, la Bucureşti, dar se simte detaşat de tot ce legase de Ela. Obosit să  mai  caute certitudini şi să se mai îndoiască, o priveşte acum cu indiferenţa „cu care priveşti un tablou\" şi hotărăşte să o părăsească: „I-am scris că îi las absolut tot ce e în casă, de la obiecte de preț la cărți... de la lucruri personale la amintiri. Adică tot trecutul\". Relatarea şi povestirea sunt înlocuite în proza modernă cu analiza şi introspecția, de unde impresia de epic evenimenţial sărac, în favoarea analizei. Masa de la unchiul Tache este prezentată ca o scenă balzaciană: aşezarea personajelor, interesul pentru moştenire, portetul bătrânului avar, arivistul linguşitor Nae Gheorghidiu."+
                "  În opinia mea, „Ultima noapte de dragoste, întâia noapte de război\" reprezintă un moment de referinţă pentru literatura națională, ilustrând efortul scriitorilor români de a se racorda la înnoirile propuse de literatura europeană. Stilul lui Camil Petrescu se caracterizează prin claritate, sobrietate, anticalofilism. \n"+
                "  În concluzie, tehnicile de creație ale lui Camil Petrescu sunt aceea a „tricotajului\" (se finisează fluxul epic) şi a „arhitectului\" (se adaugă câteva capitole care fixează interpretarea Iogică). Acronia evidenţiază discordanţa dintre timpul real şi modalităţile narării.  ";
        stringBuilder.append(finallyEseu);
        e16.setText(stringBuilder.toString());
    }
}
