package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class ultimaCaract extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ultima_caract);

        TextView caractUltima = (TextView) findViewById(R.id.caractUltima);
        TextView e17 = (TextView) findViewById(R.id.e17);

        caractUltima.setText("Caracterizarea lui Ștefan Gheorghidiu");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  „Ultima noapte de dragoste, intâia noapte de război\" este un roman modern, de tip sublectiv, având drept particularităţi: unitatea perspectivei narative, redactarea la timpul prezent, memoria involuntară, luciditatea autoanalizei. De asemenea, scriitorul pune în discuţie anticalofilismul, apreciind că „stilul frumos este opus artei\". \n"+
                "  Redactat la persoana I, sub forma unei confesiuni a personajului principal, Ștefan Gheorghidiu, romanul dobândește o perspectivă subiectivă şi unică. Naratorul este protagonistul romanului în consecință, construcția românescă se bazează pe autenticitate, pe trăirea lucidă a unor experienţe esențiale. Naratorul omniscient, obiectiv şi naraţiunea la persoana a III-a (specifice romanului tradițional, obiectiv) sunt înlocuite, în romanul modern de tip subiectiv, cu naraţiunea la persoana I, cu focalizare exclusiv internă /viziunea împreună cu. "+
                "  Naraţiunea la persoana I presupune existenţa unui narator implicat. Punctul de vedere unic şi subiectiv, al personajului-narator face ca cititorul să cunoască despre personaje tot atât cât ştie şi personajul principal. Situarea eului narativ în centrul povestirii conferă autenticitate, iar faptele și personajele sunt prezentate ca evenimente interioare, interpretate, analizate. "+
                "  Prin monolog interior, Ștefan Gheorghidiu analizează, alternând sau interferând, aspecte ale planului interior (trăiri, sentimente, reflecţii) şi ale planului exterior (fapte, tipuri umane, relaţii cu alţii). "+
                "  Tehnica memoriei involuntare creează o unitate de ansamblu a operei: un eveniment exterior (discuţia de la popotă) declanşează rememorarea unor întâmplări sau stări. În vreme ce la Marcel Proust, personajul-narator retrăieşte trecutul, la Camil Petrescu se observă analiza trecutului, fapt care generează sfârşitul iluziilor.\n"+
                "  În articolul intitulat „De ce nu avem roman?\", Camil Petrescu aduce unele lă.muriri în legătură cu tehnicile de construcţie apersonajului aparţinând romanului subiectiv. Camil Petrescu este de părere ca protagonistul trebuie să filtreze prin propria conştiintă marile probleme ale existenței; „Eroul de roman presupune un zbucium interior,... convingere profundă, un simţ al răspunderii dincolo de contingenţele obişnuite\". "+
                "  Astfel, particularităţile de construcție a personajului Ștefan Gheorghidiu sunt specifice romanului modern, subiectiv, de influență proustiană: este vorba despre deplasarea accentului spre conflictul interior, autoanaliza, fluxul conştiinţei, aceste aspecte fiind redate cu ajutorul monologului interior. Portretul fizic detaliat, specific romanului tradiţional, este înlocuit cu un complex portret moral, folosindu-se caracterizarea directă, indirectă şi autocaracterizarea. \n"+
                "  Cel de-al doilea capitol, „Diagonalele unui testament\", debutează abrupt, prin ilustrarea stării de incertitudine a protagonistului: „Eram însurat de doi ani şi jumătate cu o colegă de la Universitate şi bănuiam că mă inșală\". Acum începe să se deruleze retrospectiva iubirii dintre protagonist şi Ela. Ștefan Gheorghidiu, student la Filosofie, este un intelectual superior, cu o mare acuitate analitică, astfel că subiectul romanului se organizează în jurul dramei sale de conştiinţă. Tânărul se căsătoreşte din dragoste cu Ela, orfană, crescută de o mătuşă. Ea este studentă la Litere şi Ștefan mărturiseste: „... deşi nu-mi plăcea, începusem totuşi să fiu măgulit de admiraţia pe care o avea mai toată lumea pentru mine, fiindcă eram atât de pătimaş iubit de una dintre cele mai frumoase studente si cred că acest orgoliu a constituit baza viitoarei mele iubiri\". "+
                "  Pentru protagonist, iubirea e „un teritoriu de luptă\", în scopul menţinerii orgolioase a supremației, uneori mascată sau amânată. Aspirând la iubirea absolută, Gheorghidiu doreşte ca întreaga existenţă a femeii să se desfăşoare raportându-se mereu la el.Reflectând asupra iubirii, eroul constată că satisfacţiile şi voluptatea provin din oglindirea unuia în celălalt. "+
                "  Ștefan este un analist, el are pretenţia să judece totul. Are un orgoliu nemăsurat, care-i provoacă o angoasă terorizantă. Iubirea, răsucită pe toate feţele, naşte gelozia şi incertitudinea. Gelosul, însetat de certitudini, va transforma iubirea şi convieţuirea familială într-o pândă ce se va dovedi autodevoratoare: „Pentru mine dragostea aceasta era o luptă neîntreruptă, în care eram veşnic de veghe, cu toate simțurile la pândă, gata să previn orice pericol\" (autocaracterizare). Într-un astfel de moment al dezechilibrului sufletesc, personajul-narator, prin intermediul memoriei involuntare, care asociază fără cronologie evenimente ale trecutului, îşi rememorează iubirea."+
                "  Ștefan Gheorghidiu filtrează evenimentele exterioare prin conştiinta sa. Gândurile şi sentimentele celorlalte personaje sunt percepute subiectiv, sistematizate, fapt ce declanşează impresia izolării de lumea exterioară. El ar vrea să o atragă şi pe Ela în universul înălţării intelectuale şi filosofice, dar ea se va dovedi o fiinţă mediocră; de aici, amploarea dramei existenţiale a eroului. La un moment dat, comunicarea dintre cei doi dispare. Frământările interioare duc la schimbarea perspectivei asupra comportamentului soţiei: „Nu Ela se schimbă, ci felul în care o vede Ștefan. În acest caz, putem afirma că singurele evenimente veritabile nu sunt acelea obiective, ci acelea din conştiinţa lui Gheorghidiu. Numai pe acestea le putem povesti fără riscul de a greşi\" (Nicolae Manolescu, „Arca lui Noe\"). "+
                "  Din prima fază a confesiunii (capitolul al II-lea), aflăm cauza nefericirii eroului, bănuiala că sotia îl înşală. Această bănuială tulbură cursul normal al vieţii, studentul nu-şi mai dă examenele la timp, îşi spionează tot timpul nevasta. Amândoi studenţi săraci, se căsătoriseră din dragoste, iubirea născându-se din orgoliu, dar şi din admiraţie reciprocă. Moştenirea unei parţi din averea unchiului Tache dă o nouă turnură vieţii celor doi, care părăsesc spaţiul intim al existenţei de până atunci, intrând în viaţa mondenă, acolo unde acţionează legea banului, luxul, moda, petrecerile. "+
                "  Spre deosebire de Ela, Gheorghidiu nu acceptă acest mediu meschin și mercantil, fiind surprins de o serie de manifestări ale soției: el constată cu furie că aceasta e interesată de afaceri,  că îi  reproşează lipsa de abilitate în relaţiile cu ceilalţi (caracterizare directă), că nu doreşte un copil, că preferă un alt partener în timpul călătoriilor şi al petrecerilor. Simţind cum pierde teren într-o competiție cu un adversar nedeclarat, Gheorghidiu alunecă pe panta geloziei, deşi refuză s-o recunoască. "+
                "  Hipersensibilul analist trăieşte momente chinuitoare în neputinţa de a obţine certitudinea infidelităţii soţiei, fapt care generează principalul conflict al romanului. Sosind pe neaşteptate de la Azuga, unde fusese concentrat, nu-şi descoperă sotia acasă, iar servitoarea nu-i poate da nicio explicaţie. Simţind umilinţa, complexarea, pericolul anihilării personalității, Ștefan încearcă să se desprindă de imaginea ei. O primă modalitate a detaşării o constituie provocarea unei suferinţe identice cu cele trăite de el sub teroarea geloziei, a doua o reprezintă înlocuirea ocazională cu o altă femeie. "+
                "  Ieşirea din „noaptea de dragoste\" se face prin intrarea în „noaptea de război\". Aceasta îl scoate din tenebrele incertitudinilor în care îl târâse gelozia şi îi deschide o altă perspectivă asupra vieții. Războiul are o functie purificatoare, astfel încât protagonistul, îmbogățit prin această experiență, îşi poate reconsidera atitudinea faţă de Ela, faţă de sine şi față de lume. Acum, Ștefan Gheorghidiu se poate distanţa de Ela, lăsându-i, alături de avere, „tot trecutul\". "+
                "  Scenele semnificative pentru a înţelege perspectiva protagonistului asupra existenței sunt: discuția de la popotă; discuțiile cu Ela; întâlnirea din casa unchiului său, Tache Gheorghidiu, și discuţiile privind moștenirea; înrolarea voluntară în armată, în condiţiile Primului Război Mondial. O discuție în contradictoriu, la popotă, referitoare la achitarea unui bărbat care își ucisese soția adulterină, pune evidență convingerile lui Ștefan privind absolutul iubirii: „Trebuie să se stie că și iubirea are riscurile ei. Căci aceia care se iubesc au drept de viaţă și de moarte unul asupra celuilalt\". Protagonistul este dezgustat de mediocritatea opiniilor celorlalţi, cărora le mărturiseste: „- Discuţia dunmeavoastră e copilăroasă și primară. Nu cunoasteţi nimic din psihologia dragostei. Folosiţi un material nediferenţiat\". Deosebirea de perspectivă asupra realităţii se evidențiază si în relaţia cu unchiul său, Nae Gheorghidiu. Acesta îl ironizează pentru faptul că s-a însurat din dragoste, cu o fată fară zestre, întocmai ca tatăl său, dar Stefan răspunde, fără să ezite: ,,...părintele care lasă avere copiilor le transmite și calităţile prin care a făcut averea: un obraz mai gros [...], neapărat o șiră a spinării flexibilă ca nuiaua\". Într-un alt moment, unchiul Nae îl caracterizează direct, reproșându-i lipsa de pragmatism: „Cu filosofia dumitale nu faci doi bani\". \n"+
                "  În opinia mea, „Ultima noapte de dragoste, întâia noapte de război\" ilustrează un personaj cu o experienţă morală superioară. Ştefan Gheorghidiu este considerat de G. Călinescu: „un om inteligent [...], plin de subtilitate, de pătrundere psihologică\". "+
                "  În concluzie, „Ultima noapte de dragoste, întâia noapte de război\" este un roman al inadaptabilităţii. În viziunea lui Camil Petrescu, intelectualii nu se pot adapta lumii burgheze, iar aceasta îi desconsideră. Din aceeaşi categorie a inadaptaților fac parte şi alte personaje camilpetresciene: George Demetru Ladima, Gelu Ruscanu, Andrei Pietraru.\n";
        stringBuilder.append(finallyEseu);
        e17.setText(stringBuilder.toString());
    }
}
