package com.example.esee4bac;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class ultimaRel extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ultima_rel);

        TextView relUltima = (TextView) findViewById(R.id.relUltima);
        TextView e18 = (TextView) findViewById(R.id.e18);

        relUltima.setText("Relația dintre Ștefan și Ela");

        StringBuilder stringBuilder = new StringBuilder();
        String finallyEseu = "  Sub imperiul direcţiilor impuse prozei românești de către E.Lovinescu în studiul „Creația obiectivă\", problema intelectualului va deveni o ipoteză de gândire şi de lucru pentru scriitorii români. Fascinaţia intelectuală în literatură va avea astfel două consecințe: romanul superior, ca scriitură elevată, dar şi personajul cu statut de intelectual. "+
                "  Romanul „Ultima noapte de dragoste, intâia noapte de război\" ilustrează, într-un mod peremptoriu, ambele consecinţe. Romanul surprinde drama personajului în două momente importante: viaţă-moarte, reliefând singurătatea omului modern, care nu poate înţelege lumea, nu găseşte un punct de comunicare durabil cu aceasta.  "+
                "  Relaţiile dintre personajele Ștefan Gheorghidiu şi Ela sunt evidențiate de cele două teme, sugerate chiar din titlu: dragostea şi războiul. Acțiunea, ilustrată modern, prin artificiul compozițional de răstrurnare a planurilor temporale, evidentiază relaţiile protagonistului cu Ela. Întregul conflict gravitează în jurul suferinţei lui Ştefan, generate de drama incertitudinii. Construcţia subiectului (ce aminteşte de Proust, prin activarea memoriei afective a protagonistului) este menită să pună în evidenţă cele două planuri temporale ale discursului narativ: prezentul frontului şi trecutul poveştii de dragoste. Protagonistui ilustrează concepția lui Camil Petrescu: „eroul de roman presupune un zbucium interior, loialitate, convingere profundă, [...] caractere monumentale, în real conflict cu societatea\". El este superior moral celorlalţi prin aspiraţia către ideal, iubire.\n"+
                "  Ștefan Gheorghidiu este o conştiință incapabilă de compromisuri, neputând glorifica înşelăciunea (el se va retrage din afacerile cu Nae Gheorghidiu). Este introspectiv, conştient de supremaţia lucidități „Atenția, luciditatea nu omoară voluptatea reală, , ci o sporesc aşa cum, de altfel, atenția sporeşte şi durerea de dinți. Marii voluptuoşi şi cei care trăiesc intens viaţa, sunt, neapărat şi ultralucizi\". Personajul este un inadaptat superior într-o lume comună, societatea fiind pentru el un veritabil „pat al lui Procust\"; este un hipersensibil care amplifică semnificaţia unui gest, a unei priviri, cuvânt, până la proporțiiie unei catastrofe: „Gestul acesta avea o eleganţă acum naturală, dar la început trebuie să fi fost socotit de ea, cu convingere, ca un semn de distincție. Acum nu mai era, mai aproape vorbind, decât un gest de acreală distinsă...N-aveam nicio dovadă că mă înșeală, dar aveam acum certitudinea că acest gest vine dintr-o deprindere de a poza goală, de a face impresie\".\n"+
                "  Este un om de o inteligenţă incontestabilă, ancorată nu numai în domeniul profesiunii sale, în care realizările sunt arbitrare: „Cuvântul e oricând mijloc imperfect de comunicare. Tot ce e scris, tot ce e adevăr, tot ce e conţinut real scapă, printre silabe şi propozițiuni, ca aburul prin ţevile plesnite\"."+
                "  Imaginea Elei este construită numai prin ochii bărbatului însetat de absolutul iubirii al cărui crez nu făcea concesii sentimentului. Ela este o expresie a mediocrităţii şi a superficialităţii. Maniera de construcţie a personajului este cea romantică. Atât timp cât ea este detaşată de vulgaritate, se află deasupra celorlate femei prin imaginea pe care păstrează în mintea lui Gheorghidiu: nu este numită, este menţinută într-un anonimat superior şi misterios („nevastă-mea, fata asta, ea\"). În momentul în care, coborâtă depe soclu, se amestecă în gloată, în societatea mediocră, frivolă, meschină, este numită Ela. "+
                "  Dialogul despre iubire de la popotă provoacă o reacţie violentă a eroului, care consideră că „cei care se iubesc au drept de viaţă şi de moarte unul asupra celuilalt\". Astfel, prin memorie involuntară, se declanşează amintirea propriei poveşti de dragoste, pe care o consemnează. În jurnalul de front: „Eram însurat de doi ani şi jumătate cu o colegă de la Universitate şi bănuiam că mă înşală\". Eroul, natură reflexivă, analizează cu luciditate stările interioare, însetat de certitudini şi de adevăr. Plimbarea de la Odobeşti declanşează criza de gelozie, punând sub semnul incertitudinii fidelitatea Elei. Mici incidente, gesturi fără importanţă, priviri schimbate de ea cu domnul G., avocat obscur, dar bărbat monden, sporeşte suspiciunile: „Nevastă-mea avea o voce uşor emoţionată\".\n"+
                "  Incertitudinea iubirii devine, în curând, „o tortura\", nu mai putea citi „nicio carte\",aşa că, Stefan se desparte de soţia sa, deşi respinge ideea geloziei: „Nu, n-am fost nicio secundă gelos, deşi am suferit atâta din cauza iubirii\". Gheorghidiu văzuse în Ela idolul său  de feminitate și iubire, către care aspira cu toată fiinţa lui şi a cărui prăbuşire îi provoacă întreaga dramă. \n"+
                "  Venit pe neaşteptate acasă într-o noapte, după o absenţă mai lungă, incertitudinea lui se accentuează şi casa îi pare „goală ca un mormânt, fără nevastă-mea\". Eroul trăieşte în lumea ideilor pure, aspirând la dragostea absolută, dar se simte obosit şi hotărăşte să se despartă de Ela, pe care o priveşte acum cu indiferenţa „cu care priveşti un tablou\". "+
                "  A doua experienţă fundamentală de cunoaştere a lui Gheorghidiu este cea a frontului. Spiritul polemic al personajului-narator evidențiază discuțiile demagogice din Parlament, inconştienţa şi cinismul politicienilor, falsul patriotism şi realitatea războiului care este demitizat: acesta este tragic, absurd şi nu are nimic înălțător. "+
                "  În prima parte, fiind un prototip al iubirii absolute, portretul ei se conturează din lexeme aparţinând unui câmp semantic al frumosului, al inefabilului („crini\", „cleştar\", „minunat\"), iar în cea de-a doua, unde nu reprezintă decât un exponent al societății lipsite de semnificaţie, abundă lexemele din câmpul semantic al banalului, al vulgarului („femeie\", „ailaltă\", „grasă\", „acreală\"). \n"+
                "  Trăsăturile morale ale acesteia reies, indirect, din referirile lui Ștefan, ce analizează cu luciditate fiecare gest al Elei, care cu domnul G.: „trăgeam cu urechea, nervos, să prind crâmpeie din convorbirile pe care nevastă-mea le avea cu domnul elegant de alături de ea\". În plimbarea la Odobeşti, Ela se comportă ca o cochetă, devenind din ce în ce mai superficială. Ștefan observă mimica şi gesturile femeii care gustă cu familiaritate din farfuria lui G. şi care are o expresie deznădăjduită atunci când acesta stă de vorbă cu altă femeie. "+
                "  Ela se transformă dintr-un ideal de feminitate într-o femeie oarecare şi, pentru că aceasta nu a răspuns aşteptărilor lui Ștefan, „Falimentul iubirii, dacă iubire a fost, e şi falimentul minţii\". "+
                "  În opinia mea, modul în care mesajul operei se reflectă în evoluția relației dintre cele două personaje se bazează pe faptul că atmosfera apocaliptică a războiului aduce „falimentul lubirii\". De altfel, Pompiliu Constantinescu aprecia: „Jurnalul de campanie al Gheorghidiu e mărturia unui combatant şi inovaţia unui artist care îşi confesează propria mutilare morală.\n"+
                "  În concluzie, romanul lui Camil Petrescu are în vedere principii moderniste formulate de E. Lovinescu: trecerea prozei de la mediul rural, la cel urban, prezenţa intelectualului ca tip de personaj. ";
        stringBuilder.append(finallyEseu);
        e18.setText(stringBuilder.toString());
    }
}
